// Code generated by the Lingua Franca compiler from:
// file://home/plutonh/project/src/Lab3.lf
#define LOG_LEVEL 2
#define TARGET_FILES_DIRECTORY "/home/plutonh/project/src-gen/Lab3"
#include "include/ctarget/ctarget.h"
#include "core/threaded/reactor_threaded.c"
#include "core/threaded/scheduler.h"
#include "core/mixed_radix.h"
int main(int argc, char* argv[]) {
    return lf_reactor_c_main(argc, argv);
}
void _lf_set_default_command_line_options() {}
// =============== START reactor class LogicalAction
typedef struct {
    int value;
    bool is_present;
    int num_destinations;
    lf_token_t* token;
    int length;
    void (*destructor) (void* value);
    void* (*copy_constructor) (void* value);
} logicalaction_out_t;
typedef struct {
    trigger_t* trigger;
    bool is_present;
    bool has_value;
    lf_token_t* token;
} logicalaction_a_t;
typedef struct {
    struct self_base_t base;
    int count;
    logicalaction_a_t _lf_a;
    logicalaction_out_t _lf_out;
    int _lf_out_width;
    reaction_t _lf__reaction_0;
    trigger_t _lf__startup;
    reaction_t* _lf__startup_reactions[1];
    trigger_t _lf__a;
    reaction_t* _lf__a_reactions[1];
} logicalaction_self_t;
// ***** Start of method declarations.
// ***** End of method declarations.
#include "include/ctarget/set.h"
void logicalactionreaction_function_0(void* instance_args) {
    #pragma GCC diagnostic push
    #pragma GCC diagnostic ignored "-Wunused-variable"
    logicalaction_self_t* self = (logicalaction_self_t*)instance_args;
    // Expose the action struct as a local variable whose name matches the action name.
    logicalaction_a_t* a = &self->_lf_a;
    // Set the fields of the action struct to match the current trigger.
    a->is_present = (bool)self->_lf__a.status;
    a->has_value = ((self->_lf__a.token) != NULL && (self->_lf__a.token)->value != NULL);
    a->token = (self->_lf__a.token);
    logicalaction_out_t* out = &self->_lf_out;
    #pragma GCC diagnostic pop
    if(self->count == 0) {
        lf_set(out, self->count);
        lf_schedule(a, SEC(1));
        self->count += 1;
    }
    else if(self->count == 1) {
        lf_set(out, self->count);
        lf_schedule(a, SEC(1));
        self->count += 2;
    }
    else if((self->count == 3) || (self->count == 13) || (self->count == 23)) {
        lf_set(out, self->count);
        lf_schedule(a, 0);
        self->count += 10;
    }
}
#include "include/ctarget/set_undef.h"
logicalaction_self_t* new_LogicalAction() {
    logicalaction_self_t* self = (logicalaction_self_t*)_lf_new_reactor(sizeof(logicalaction_self_t));
    self->_lf_a.trigger = &self->_lf__a;
    self->_lf__reaction_0.number = 0;
    self->_lf__reaction_0.function = logicalactionreaction_function_0;
    self->_lf__reaction_0.self = self;
    self->_lf__reaction_0.deadline_violation_handler = NULL;
    self->_lf__reaction_0.STP_handler = NULL;
    self->_lf__reaction_0.name = "?";
    self->_lf__reaction_0.mode = NULL;
    self->_lf__startup_reactions[0] = &self->_lf__reaction_0;
    self->_lf__startup.last = NULL;
    self->_lf__startup.reactions = &self->_lf__startup_reactions[0];
    self->_lf__startup.number_of_reactions = 1;
    self->_lf__startup.is_timer = false;
    self->_lf__a.last = NULL;
    self->_lf__a_reactions[0] = &self->_lf__reaction_0;
    self->_lf__a.reactions = &self->_lf__a_reactions[0];
    self->_lf__a.number_of_reactions = 1;
    self->_lf__a.is_physical = false;
    
    self->_lf__a.element_size = 0;
    return self;
}
// =============== END reactor class LogicalAction
// =============== START reactor class Printer
typedef struct {
    int value;
    bool is_present;
    int num_destinations;
    lf_token_t* token;
    int length;
    void (*destructor) (void* value);
    void* (*copy_constructor) (void* value);
} printer_in_t;
typedef struct {
    struct self_base_t base;
    printer_in_t* _lf_in;
    // width of -2 indicates that it is not a multiport.
    int _lf_in_width;
    // Default input (in case it does not get connected)
    printer_in_t _lf_default__in;
    reaction_t _lf__reaction_0;
    trigger_t _lf__in;
    reaction_t* _lf__in_reactions[1];
} printer_self_t;
// ***** Start of method declarations.
// ***** End of method declarations.
#include "include/ctarget/set.h"
void printerreaction_function_0(void* instance_args) {
    #pragma GCC diagnostic push
    #pragma GCC diagnostic ignored "-Wunused-variable"
    printer_self_t* self = (printer_self_t*)instance_args;
    printer_in_t* in = self->_lf_in;
    int in_width = self->_lf_in_width;
    #pragma GCC diagnostic pop
    lf_print("In: %d, Logical Elapsed Time: %lld nsec, Micro step: %d"
    , in -> value, lf_time_logical_elapsed(), lf_tag().microstep);
}
#include "include/ctarget/set_undef.h"
printer_self_t* new_Printer() {
    printer_self_t* self = (printer_self_t*)_lf_new_reactor(sizeof(printer_self_t));
    // Set input by default to an always absent default input.
    self->_lf_in = &self->_lf_default__in;
    self->_lf__reaction_0.number = 0;
    self->_lf__reaction_0.function = printerreaction_function_0;
    self->_lf__reaction_0.self = self;
    self->_lf__reaction_0.deadline_violation_handler = NULL;
    self->_lf__reaction_0.STP_handler = NULL;
    self->_lf__reaction_0.name = "?";
    self->_lf__reaction_0.mode = NULL;
    self->_lf__in.last = NULL;
    self->_lf__in_reactions[0] = &self->_lf__reaction_0;
    self->_lf__in.reactions = &self->_lf__in_reactions[0];
    self->_lf__in.number_of_reactions = 1;
    self->_lf__in.element_size = sizeof(int);
    return self;
}
// =============== END reactor class Printer
// =============== START reactor class _lf_GenDelay_540193ca
typedef struct {
    int value;
    bool is_present;
    int num_destinations;
    lf_token_t* token;
    int length;
    void (*destructor) (void* value);
    void* (*copy_constructor) (void* value);
} _lf_gendelay_540193ca_inp_t;
typedef struct {
    int value;
    bool is_present;
    int num_destinations;
    lf_token_t* token;
    int length;
    void (*destructor) (void* value);
    void* (*copy_constructor) (void* value);
} _lf_gendelay_540193ca_out_t;
typedef struct {
    trigger_t* trigger;
    int value;
    bool is_present;
    bool has_value;
    lf_token_t* token;
} _lf_gendelay_540193ca_act_t;
typedef struct {
    struct self_base_t base;
    interval_t delay;
    _lf_gendelay_540193ca_act_t _lf_act;
    _lf_gendelay_540193ca_inp_t* _lf_inp;
    // width of -2 indicates that it is not a multiport.
    int _lf_inp_width;
    // Default input (in case it does not get connected)
    _lf_gendelay_540193ca_inp_t _lf_default__inp;
    _lf_gendelay_540193ca_out_t _lf_out;
    int _lf_out_width;
    reaction_t _lf__reaction_0;
    reaction_t _lf__reaction_1;
    trigger_t _lf__act;
    reaction_t* _lf__act_reactions[1];
    trigger_t _lf__inp;
    reaction_t* _lf__inp_reactions[1];
} _lf_gendelay_540193ca_self_t;
// ***** Start of method declarations.
// ***** End of method declarations.
#include "include/ctarget/set.h"
void _lf_gendelay_540193careaction_function_0(void* instance_args) {
    #pragma GCC diagnostic push
    #pragma GCC diagnostic ignored "-Wunused-variable"
    _lf_gendelay_540193ca_self_t* self = (_lf_gendelay_540193ca_self_t*)instance_args;
    // Expose the action struct as a local variable whose name matches the action name.
    _lf_gendelay_540193ca_act_t* act = &self->_lf_act;
    // Set the fields of the action struct to match the current trigger.
    act->is_present = (bool)self->_lf__act.status;
    act->has_value = ((self->_lf__act.token) != NULL && (self->_lf__act.token)->value != NULL);
    act->token = (self->_lf__act.token);
    if (act->has_value) {
        act->value = *(int*)(self->_lf__act.token)->value;
    }
    _lf_gendelay_540193ca_out_t* out = &self->_lf_out;
    #pragma GCC diagnostic pop
    lf_set(out, act->value);
}
#include "include/ctarget/set_undef.h"
#include "include/ctarget/set.h"
void _lf_gendelay_540193careaction_function_1(void* instance_args) {
    #pragma GCC diagnostic push
    #pragma GCC diagnostic ignored "-Wunused-variable"
    _lf_gendelay_540193ca_self_t* self = (_lf_gendelay_540193ca_self_t*)instance_args;
    _lf_gendelay_540193ca_inp_t* inp = self->_lf_inp;
    int inp_width = self->_lf_inp_width;
    _lf_gendelay_540193ca_act_t* act = &self->_lf_act;
    #pragma GCC diagnostic pop
    lf_schedule_copy(act, 0, &inp->value, 1);  // Length is 1.
}
#include "include/ctarget/set_undef.h"
_lf_gendelay_540193ca_self_t* new__lf_GenDelay_540193ca() {
    _lf_gendelay_540193ca_self_t* self = (_lf_gendelay_540193ca_self_t*)_lf_new_reactor(sizeof(_lf_gendelay_540193ca_self_t));
    self->_lf_act.trigger = &self->_lf__act;
    // Set input by default to an always absent default input.
    self->_lf_inp = &self->_lf_default__inp;
    self->_lf__reaction_0.number = 0;
    self->_lf__reaction_0.function = _lf_gendelay_540193careaction_function_0;
    self->_lf__reaction_0.self = self;
    self->_lf__reaction_0.deadline_violation_handler = NULL;
    self->_lf__reaction_0.STP_handler = NULL;
    self->_lf__reaction_0.name = "?";
    self->_lf__reaction_0.mode = NULL;
    self->_lf__reaction_1.number = 1;
    self->_lf__reaction_1.function = _lf_gendelay_540193careaction_function_1;
    self->_lf__reaction_1.self = self;
    self->_lf__reaction_1.deadline_violation_handler = NULL;
    self->_lf__reaction_1.STP_handler = NULL;
    self->_lf__reaction_1.name = "?";
    self->_lf__reaction_1.mode = NULL;
    self->_lf__act.last = NULL;
    self->_lf__act_reactions[0] = &self->_lf__reaction_0;
    self->_lf__act.reactions = &self->_lf__act_reactions[0];
    self->_lf__act.number_of_reactions = 1;
    self->_lf__act.is_physical = false;
    
    self->_lf__act.element_size = sizeof(int);
    self->_lf__inp.last = NULL;
    self->_lf__inp_reactions[0] = &self->_lf__reaction_1;
    self->_lf__inp.reactions = &self->_lf__inp_reactions[0];
    self->_lf__inp.number_of_reactions = 1;
    self->_lf__inp.element_size = sizeof(int);
    return self;
}
// =============== END reactor class _lf_GenDelay_540193ca
// =============== START reactor class Lab3
typedef struct {
    struct self_base_t base;
} lab3_self_t;
// ***** Start of method declarations.
// ***** End of method declarations.
lab3_self_t* new_Lab3() {
    lab3_self_t* self = (lab3_self_t*)_lf_new_reactor(sizeof(lab3_self_t));
    return self;
}
// =============== END reactor class Lab3
// Array of pointers to timer triggers to be scheduled in _lf_initialize_timers().
trigger_t** _lf_timer_triggers = NULL;
int _lf_timer_triggers_size = 0;
// Array of pointers to startup triggers.
reaction_t* _lf_startup_reactions[1];
int _lf_startup_reactions_size = 1;
// Array of pointers to shutdown triggers.
reaction_t** _lf_shutdown_reactions = NULL;
int _lf_shutdown_reactions_size = 0;
// Array of pointers to reset triggers.
reaction_t** _lf_reset_reactions = NULL;
int _lf_reset_reactions_size = 0;
trigger_t* _lf_action_for_port(int port_id) {
        return NULL;
}
void _lf_initialize_trigger_objects() {
    // Initialize the _lf_clock
    lf_initialize_clock();
    _lf_tokens_with_ref_count_size = 2;
    _lf_tokens_with_ref_count = (token_present_t*)calloc(2, sizeof(token_present_t));
    if (_lf_tokens_with_ref_count == NULL) lf_print_error_and_exit("Out of memory!");
    // Create the array that will contain pointers to is_present fields to reset on each step.
    _lf_is_present_fields_size = 4;
    _lf_is_present_fields = (bool**)calloc(4, sizeof(bool*));
    if (_lf_is_present_fields == NULL) lf_print_error_and_exit("Out of memory!");
    _lf_is_present_fields_abbreviated = (bool**)calloc(4, sizeof(bool*));
    if (_lf_is_present_fields_abbreviated == NULL) lf_print_error_and_exit("Out of memory!");
    _lf_is_present_fields_abbreviated_size = 0;
    int _lf_startup_reactions_count = 0;
    int _lf_shutdown_reactions_count = 0;
    int _lf_reset_reactions_count = 0;
    int _lf_timer_triggers_count = 0;
    int _lf_tokens_with_ref_count_count = 0;
    lab3_self_t* lab3_self[1];
    logicalaction_self_t* lab3_first_self[1];
    printer_self_t* lab3_second_self[1];
    _lf_gendelay_540193ca_self_t* lab3_delay_self[1];
    // ***** Start initializing Lab3 of class Lab3
    lab3_self[0] = new_Lab3();
    int bank_index = 0;
    {
        // ***** Start initializing Lab3.first of class LogicalAction
        lab3_first_self[0] = new_LogicalAction();
        int bank_index = 0;
        // width of -2 indicates that it is not a multiport.
        lab3_first_self[0]->_lf_out_width = -2;
        _lf_startup_reactions[_lf_startup_reactions_count++] = &lab3_first_self[0]->_lf__reaction_0;
        { // For scoping
            static int _initial = 0;
            lab3_first_self[0]->count = _initial;
        } // End scoping.
        // Initializing action Lab3.first.a
        lab3_first_self[0]->_lf__a.offset = 0;
        lab3_first_self[0]->_lf__a.period = -1;
        lab3_first_self[0]->_lf__a.mode = NULL;
        lab3_first_self[0]->_lf__a.token = _lf_create_token(0);
        lab3_first_self[0]->_lf__a.status = absent;
        _lf_tokens_with_ref_count[_lf_tokens_with_ref_count_count].token = &lab3_first_self[0]->_lf__a.token;
        _lf_tokens_with_ref_count[_lf_tokens_with_ref_count_count].status = &lab3_first_self[0]->_lf__a.status;
        _lf_tokens_with_ref_count[_lf_tokens_with_ref_count_count++].reset_is_present = true;
        lab3_first_self[0]->_lf__reaction_0.deadline = NEVER;
        //***** End initializing Lab3.first
    }
    {
        // ***** Start initializing Lab3.second of class Printer
        lab3_second_self[0] = new_Printer();
        int bank_index = 0;
        // width of -2 indicates that it is not a multiport.
        lab3_second_self[0]->_lf_in_width = -2;
        lab3_second_self[0]->_lf__reaction_0.deadline = NEVER;
        //***** End initializing Lab3.second
    }
    {
        // ***** Start initializing Lab3.delay of class _lf_GenDelay_540193ca
        lab3_delay_self[0] = new__lf_GenDelay_540193ca();
        int bank_index = 0;
        lab3_delay_self[0]->delay = SEC(1);
        // width of -2 indicates that it is not a multiport.
        lab3_delay_self[0]->_lf_out_width = -2;
        // width of -2 indicates that it is not a multiport.
        lab3_delay_self[0]->_lf_inp_width = -2;
        // Initializing action Lab3.delay.act
        lab3_delay_self[0]->_lf__act.offset = SEC(1);
        lab3_delay_self[0]->_lf__act.period = -1;
        lab3_delay_self[0]->_lf__act.mode = NULL;
        lab3_delay_self[0]->_lf__act.token = _lf_create_token(sizeof(int));
        lab3_delay_self[0]->_lf__act.status = absent;
        _lf_tokens_with_ref_count[_lf_tokens_with_ref_count_count].token = &lab3_delay_self[0]->_lf__act.token;
        _lf_tokens_with_ref_count[_lf_tokens_with_ref_count_count].status = &lab3_delay_self[0]->_lf__act.status;
        _lf_tokens_with_ref_count[_lf_tokens_with_ref_count_count++].reset_is_present = true;
        lab3_delay_self[0]->_lf__reaction_0.deadline = NEVER;
        lab3_delay_self[0]->_lf__reaction_1.deadline = NEVER;
        //***** End initializing Lab3.delay
    }
    //***** End initializing Lab3
    // **** Start deferred initialize for Lab3
    {
        // **** Start deferred initialize for Lab3.first
        {
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_0 of Lab3.first.
            lab3_first_self[0]->_lf__reaction_0.num_outputs = 1;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            lab3_first_self[0]->_lf__reaction_0.triggers = (trigger_t***)_lf_allocate(
                    1, sizeof(trigger_t**),
                    &lab3_first_self[0]->base.allocations);
            lab3_first_self[0]->_lf__reaction_0.triggered_sizes = (int*)_lf_allocate(
                    1, sizeof(int),
                    &lab3_first_self[0]->base.allocations);
            lab3_first_self[0]->_lf__reaction_0.output_produced = (bool**)_lf_allocate(
                    1, sizeof(bool*),
                    &lab3_first_self[0]->base.allocations);
            {
                int count = 0;
                {
                    lab3_first_self[0]->_lf__reaction_0.output_produced[count++] = &lab3_first_self[0]->_lf_out.is_present;
                }
            }
            
            // ** End initialization for reaction 0 of Lab3.first
        }
        // **** End of deferred initialize for Lab3.first
        // **** Start deferred initialize for Lab3.second
        {
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_0 of Lab3.second.
            lab3_second_self[0]->_lf__reaction_0.num_outputs = 0;
            {
                int count = 0;
            }
            
            // ** End initialization for reaction 0 of Lab3.second
        }
        // **** End of deferred initialize for Lab3.second
        // **** Start deferred initialize for Lab3.delay
        {
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_0 of Lab3.delay.
            lab3_delay_self[0]->_lf__reaction_0.num_outputs = 1;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            lab3_delay_self[0]->_lf__reaction_0.triggers = (trigger_t***)_lf_allocate(
                    1, sizeof(trigger_t**),
                    &lab3_delay_self[0]->base.allocations);
            lab3_delay_self[0]->_lf__reaction_0.triggered_sizes = (int*)_lf_allocate(
                    1, sizeof(int),
                    &lab3_delay_self[0]->base.allocations);
            lab3_delay_self[0]->_lf__reaction_0.output_produced = (bool**)_lf_allocate(
                    1, sizeof(bool*),
                    &lab3_delay_self[0]->base.allocations);
            {
                int count = 0;
                {
                    lab3_delay_self[0]->_lf__reaction_0.output_produced[count++] = &lab3_delay_self[0]->_lf_out.is_present;
                }
            }
            
            // ** End initialization for reaction 0 of Lab3.delay
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of Lab3.delay.
            lab3_delay_self[0]->_lf__reaction_1.num_outputs = 0;
            {
                int count = 0;
            }
            
            // ** End initialization for reaction 1 of Lab3.delay
        }
        // **** End of deferred initialize for Lab3.delay
    }
    // **** End of deferred initialize for Lab3
    // **** Start non-nested deferred initialize for Lab3
    // **** Start non-nested deferred initialize for Lab3.first
    // For reference counting, set num_destinations for port Lab3.first.out.
    // Iterate over range Lab3.first.out(0,1)->[Lab3.delay.inp(0,1)].
    {
        int src_runtime = 0; // Runtime index.
        int src_channel = 0; // Channel index.
        int src_bank = 0; // Bank index.
        int range_count = 0;
        lab3_first_self[src_runtime]->_lf_out.num_destinations = 1;
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range Lab3.first.out(0,1)->[Lab3.delay.inp(0,1)].
        {
            int src_runtime = 0; // Runtime index.
            int src_channel = 0; // Channel index.
            int src_bank = 0; // Bank index.
            int range_count = 0;
            // Reaction 0 of Lab3.first triggers 1 downstream reactions
            // through port Lab3.first.out.
            lab3_first_self[src_runtime]->_lf__reaction_0.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 0 of Lab3.first, allocate an
            // array of trigger pointers for downstream reactions through port Lab3.first.out
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &lab3_first_self[src_runtime]->base.allocations); 
            lab3_first_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges Lab3.first.out(0,1)->[Lab3.delay.inp(0,1)] and Lab3.delay.inp(0,1).
        {
            int src_runtime = 0; // Runtime index.
            int src_channel = 0; // Channel index.
            int src_bank = 0; // Bank index.
            // Iterate over range Lab3.delay.inp(0,1).
            {
                int dst_runtime = 0; // Runtime index.
                int dst_channel = 0; // Channel index.
                int dst_bank = 0; // Bank index.
                int range_count = 0;
                // Point to destination port Lab3.delay.inp's trigger struct.
                lab3_first_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime] + src_channel][0] = &lab3_delay_self[dst_runtime]->_lf__inp;
            }
        }
    }
    // **** End of non-nested deferred initialize for Lab3.first
    // **** Start non-nested deferred initialize for Lab3.second
    // **** End of non-nested deferred initialize for Lab3.second
    // **** Start non-nested deferred initialize for Lab3.delay
    // For reference counting, set num_destinations for port Lab3.delay.out.
    // Iterate over range Lab3.delay.out(0,1)->[Lab3.second.in(0,1)].
    {
        int src_runtime = 0; // Runtime index.
        int src_channel = 0; // Channel index.
        int src_bank = 0; // Bank index.
        int range_count = 0;
        lab3_delay_self[src_runtime]->_lf_out.num_destinations = 1;
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range Lab3.delay.out(0,1)->[Lab3.second.in(0,1)].
        {
            int src_runtime = 0; // Runtime index.
            int src_channel = 0; // Channel index.
            int src_bank = 0; // Bank index.
            int range_count = 0;
            // Reaction 0 of Lab3.delay triggers 1 downstream reactions
            // through port Lab3.delay.out.
            lab3_delay_self[src_runtime]->_lf__reaction_0.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 0 of Lab3.delay, allocate an
            // array of trigger pointers for downstream reactions through port Lab3.delay.out
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &lab3_delay_self[src_runtime]->base.allocations); 
            lab3_delay_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges Lab3.delay.out(0,1)->[Lab3.second.in(0,1)] and Lab3.second.in(0,1).
        {
            int src_runtime = 0; // Runtime index.
            int src_channel = 0; // Channel index.
            int src_bank = 0; // Bank index.
            // Iterate over range Lab3.second.in(0,1).
            {
                int dst_runtime = 0; // Runtime index.
                int dst_channel = 0; // Channel index.
                int dst_bank = 0; // Bank index.
                int range_count = 0;
                // Point to destination port Lab3.second.in's trigger struct.
                lab3_delay_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime] + src_channel][0] = &lab3_second_self[dst_runtime]->_lf__in;
            }
        }
    }
    // **** End of non-nested deferred initialize for Lab3.delay
    // **** End of non-nested deferred initialize for Lab3
    // Connect inputs and outputs for reactor Lab3.
    // Connect inputs and outputs for reactor Lab3.first.
    // Connect Lab3.first.out(0,1)->[Lab3.delay.inp(0,1)] to port Lab3.delay.inp(0,1)
    // Iterate over ranges Lab3.first.out(0,1)->[Lab3.delay.inp(0,1)] and Lab3.delay.inp(0,1).
    {
        int src_runtime = 0; // Runtime index.
        int src_channel = 0; // Channel index.
        int src_bank = 0; // Bank index.
        // Iterate over range Lab3.delay.inp(0,1).
        {
            int dst_runtime = 0; // Runtime index.
            int dst_channel = 0; // Channel index.
            int dst_bank = 0; // Bank index.
            int range_count = 0;
            lab3_delay_self[dst_runtime]->_lf_inp = (_lf_gendelay_540193ca_inp_t*)&lab3_first_self[src_runtime]->_lf_out;
        }
    }
    // Connect inputs and outputs for reactor Lab3.second.
    // Connect inputs and outputs for reactor Lab3.delay.
    // Connect Lab3.delay.out(0,1)->[Lab3.second.in(0,1)] to port Lab3.second.in(0,1)
    // Iterate over ranges Lab3.delay.out(0,1)->[Lab3.second.in(0,1)] and Lab3.second.in(0,1).
    {
        int src_runtime = 0; // Runtime index.
        int src_channel = 0; // Channel index.
        int src_bank = 0; // Bank index.
        // Iterate over range Lab3.second.in(0,1).
        {
            int dst_runtime = 0; // Runtime index.
            int dst_channel = 0; // Channel index.
            int dst_bank = 0; // Bank index.
            int range_count = 0;
            lab3_second_self[dst_runtime]->_lf_in = (printer_in_t*)&lab3_delay_self[src_runtime]->_lf_out;
        }
    }
    {
        {
            // Add action Lab3.first.a to array of is_present fields.
            _lf_is_present_fields[0] 
                    = &lab3_first_self[0]->_lf_a.is_present;
        }
    }
    {
    }
    {
        {
            // Add action Lab3.delay.act to array of is_present fields.
            _lf_is_present_fields[1] 
                    = &lab3_delay_self[0]->_lf_act.is_present;
        }
    }
    {
        int count = 0;
        {
            // Add port Lab3.first.out to array of is_present fields.
            _lf_is_present_fields[2 + count] = &lab3_first_self[0]->_lf_out.is_present;
            count++;
        }
    }
    {
        int count = 0;
        {
            // Add port Lab3.delay.out to array of is_present fields.
            _lf_is_present_fields[3 + count] = &lab3_delay_self[0]->_lf_out.is_present;
            count++;
        }
    }
    // Set reaction priorities for ReactorInstance Lab3
    {
        // Set reaction priorities for ReactorInstance Lab3.first
        {
            lab3_first_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 0 and 
            // deadline 140737488355327 shifted left 16 bits.
            lab3_first_self[0]->_lf__reaction_0.index = 0x7fffffffffff0000LL;
        }
        // Set reaction priorities for ReactorInstance Lab3.second
        {
            lab3_second_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 1 and 
            // deadline 140737488355327 shifted left 16 bits.
            lab3_second_self[0]->_lf__reaction_0.index = 0x7fffffffffff0001LL;
        }
        // Set reaction priorities for ReactorInstance Lab3.delay
        {
            lab3_delay_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 0 and 
            // deadline 140737488355327 shifted left 16 bits.
            lab3_delay_self[0]->_lf__reaction_0.index = 0x7fffffffffff0000LL;
            lab3_delay_self[0]->_lf__reaction_1.chain_id = 1;
            // index is the OR of level 1 and 
            // deadline 140737488355327 shifted left 16 bits.
            lab3_delay_self[0]->_lf__reaction_1.index = 0x7fffffffffff0001LL;
        }
    }
    // Initialize the scheduler
    size_t num_reactions_per_level[2] = 
        {2, 2};
    sched_params_t sched_params = (sched_params_t) {
                            .num_reactions_per_level = &num_reactions_per_level[0],
                            .num_reactions_per_level_size = (size_t) 2};
    lf_sched_init(
        (size_t)_lf_number_of_workers,
        &sched_params
    );
}
void _lf_trigger_startup_reactions() {
    for (int i = 0; i < _lf_startup_reactions_size; i++) {
        if (_lf_startup_reactions[i] != NULL) {
            _lf_trigger_reaction(_lf_startup_reactions[i], -1);
        }
    }
}
void _lf_initialize_timers() {
}
void logical_tag_complete(tag_t tag_to_send) {
}
bool _lf_trigger_shutdown_reactions() {
    return false;
}
void terminate_execution() {}
