// Code generated by the Lingua Franca compiler from:
// file://home/plutonh/project/fed-gen/WaitingLine/src/SM.lf
#define LOG_LEVEL 2
#define TARGET_FILES_DIRECTORY "/home/plutonh/project/fed-gen/WaitingLine/src-gen/SM"
#include "include/api/api.h"
#include "core/reactor.h"
#include "core/reactor_common.h"
#include "core/threaded/scheduler.h"
#include "core/mixed_radix.h"
#include "core/port.h"
int lf_reactor_c_main(int argc, const char* argv[]);
#include "core/federated/federate.h"
#include "core/federated/net_common.h"
#include "include/_SM_preamble.h"
int main(int argc, const char* argv[]) {
    return lf_reactor_c_main(argc, argv);
}
const char* _lf_default_argv[] = { "dummy", "-k", "true" };
void _lf_set_default_command_line_options() {
        default_argc = 3;
        default_argv = _lf_default_argv;
}
// =============== START reactor class StepMotor
typedef struct {
    token_type_t type;
    lf_token_t* token;
    size_t length;
    bool is_present;
    lf_sparse_io_record_t* sparse_record;
    int destination_channel;
    int num_destinations;
    int value;
    #ifdef FEDERATED
    #ifdef FEDERATED_DECENTRALIZED
    tag_t intended_tag;
    #endif
    interval_t physical_time_of_arrival;
    #endif
} stepmotor_result_t;
typedef struct {
    struct self_base_t base;
    #line 17 "/home/plutonh/project/fed-gen/WaitingLine/src/SM.lf"
    stepmotor_result_t* _lf_result;
    #line 17 "/home/plutonh/project/fed-gen/WaitingLine/src/SM.lf"
    // width of -2 indicates that it is not a multiport.
    #line 17 "/home/plutonh/project/fed-gen/WaitingLine/src/SM.lf"
    int _lf_result_width;
    #line 17 "/home/plutonh/project/fed-gen/WaitingLine/src/SM.lf"
    // Default input (in case it does not get connected)
    #line 17 "/home/plutonh/project/fed-gen/WaitingLine/src/SM.lf"
    stepmotor_result_t _lf_default__result;
    #line 17 "/home/plutonh/project/fed-gen/WaitingLine/src/SM.lf"
    trigger_t _lf__result;
    #ifdef FEDERATED
    
    #endif // FEDERATED
} stepmotor_self_t;
// ***** Start of method declarations.
// ***** End of method declarations.
stepmotor_self_t* new_StepMotor() {
    stepmotor_self_t* self = (stepmotor_self_t*)_lf_new_reactor(sizeof(stepmotor_self_t));
    #line 17 "/home/plutonh/project/fed-gen/WaitingLine/src/SM.lf"
    // Set input by default to an always absent default input.
    #line 17 "/home/plutonh/project/fed-gen/WaitingLine/src/SM.lf"
    self->_lf_result = &self->_lf_default__result;
    #line 17 "/home/plutonh/project/fed-gen/WaitingLine/src/SM.lf"
    self->_lf__result.last = NULL;
    #line 17 "/home/plutonh/project/fed-gen/WaitingLine/src/SM.lf"
    #ifdef FEDERATED_DECENTRALIZED
    #line 17 "/home/plutonh/project/fed-gen/WaitingLine/src/SM.lf"
    self->_lf__result.intended_tag = (tag_t) { .time = NEVER, .microstep = 0u};
    #line 17 "/home/plutonh/project/fed-gen/WaitingLine/src/SM.lf"
    #endif // FEDERATED_DECENTRALIZED
    self->_lf__result.tmplt.type.element_size = sizeof(int);
    return self;
}
// =============== END reactor class StepMotor
// =============== START reactor class SM
typedef struct {
    token_type_t type;
    lf_token_t* token;
    size_t length;
    bool is_present;
    bool has_value;
    trigger_t* trigger;
    #ifdef FEDERATED
    #ifdef FEDERATED_DECENTRALIZED
    tag_t intended_tag;
    #endif
    interval_t physical_time_of_arrival;
    #endif
} sm_inputControlReactionTrigger_0_t;
typedef struct {
    token_type_t type;
    lf_token_t* token;
    size_t length;
    bool is_present;
    bool has_value;
    trigger_t* trigger;
    int value;
    #ifdef FEDERATED
    #ifdef FEDERATED_DECENTRALIZED
    tag_t intended_tag;
    #endif
    interval_t physical_time_of_arrival;
    #endif
} sm_networkMessage_0_t;
typedef struct {
    struct self_base_t base;
    #line 24 "/home/plutonh/project/fed-gen/WaitingLine/src/SM.lf"
    sm_inputControlReactionTrigger_0_t _lf_inputControlReactionTrigger_0;
    #line 25 "/home/plutonh/project/fed-gen/WaitingLine/src/SM.lf"
    sm_networkMessage_0_t _lf_networkMessage_0;
    struct {
        #line 17 "/home/plutonh/project/fed-gen/WaitingLine/src/SM.lf"
        stepmotor_result_t result;
    } _lf_SM;
    int _lf_SM_width;
    #line 28 "/home/plutonh/project/fed-gen/WaitingLine/src/SM.lf"
    reaction_t _lf__reaction_0;
    #line 35 "/home/plutonh/project/fed-gen/WaitingLine/src/SM.lf"
    reaction_t _lf__reaction_1;
    #line 24 "/home/plutonh/project/fed-gen/WaitingLine/src/SM.lf"
    trigger_t _lf__inputControlReactionTrigger_0;
    #line 24 "/home/plutonh/project/fed-gen/WaitingLine/src/SM.lf"
    reaction_t* _lf__inputControlReactionTrigger_0_reactions[1];
    #line 25 "/home/plutonh/project/fed-gen/WaitingLine/src/SM.lf"
    trigger_t _lf__networkMessage_0;
    #line 25 "/home/plutonh/project/fed-gen/WaitingLine/src/SM.lf"
    reaction_t* _lf__networkMessage_0_reactions[1];
} sm_main_self_t;
// ***** Start of method declarations.
// ***** End of method declarations.
#include "include/api/set.h"
void sm_mainreaction_function_0(void* instance_args) {
    sm_main_self_t* self = (sm_main_self_t*)instance_args; SUPPRESS_UNUSED_WARNING(self);
    struct SM {
        stepmotor_result_t* result;
    
    } SM;
    // Expose the action struct as a local variable whose name matches the action name.
    sm_inputControlReactionTrigger_0_t* inputControlReactionTrigger_0 = &self->_lf_inputControlReactionTrigger_0;
    // Set the fields of the action struct to match the current trigger.
    inputControlReactionTrigger_0->is_present = (bool)self->_lf__inputControlReactionTrigger_0.status;
    inputControlReactionTrigger_0->has_value = ((self->_lf__inputControlReactionTrigger_0.tmplt.token) != NULL && (self->_lf__inputControlReactionTrigger_0.tmplt.token)->value != NULL);
    _lf_replace_template_token((token_template_t*)inputControlReactionTrigger_0, (self->_lf__inputControlReactionTrigger_0.tmplt.token));
    SM.result = &(self->_lf_SM.result);
    #line 30 "/home/plutonh/project/fed-gen/WaitingLine/src/SM.lf"
    // **** This reaction is unordered.
    interval_t max_STP = 0LL;
    // Wait until the port status is known
    wait_until_port_status_known(0, max_STP);
}
#include "include/api/set_undef.h"
#include "include/api/set.h"
void sm_mainreaction_function_1(void* instance_args) {
    sm_main_self_t* self = (sm_main_self_t*)instance_args; SUPPRESS_UNUSED_WARNING(self);
    struct SM {
        stepmotor_result_t* result;
    
    } SM;
    // Expose the action struct as a local variable whose name matches the action name.
    sm_networkMessage_0_t* networkMessage_0 = &self->_lf_networkMessage_0;
    // Set the fields of the action struct to match the current trigger.
    networkMessage_0->is_present = (bool)self->_lf__networkMessage_0.status;
    networkMessage_0->has_value = ((self->_lf__networkMessage_0.tmplt.token) != NULL && (self->_lf__networkMessage_0.tmplt.token)->value != NULL);
    _lf_replace_template_token((token_template_t*)networkMessage_0, (self->_lf__networkMessage_0.tmplt.token));
    if (networkMessage_0->has_value) {
        networkMessage_0->value = *(int*)(self->_lf__networkMessage_0.tmplt.token)->value;
    }
    SM.result = &(self->_lf_SM.result);
    #line 37 "/home/plutonh/project/fed-gen/WaitingLine/src/SM.lf"
    // **** This reaction is unordered.
    SM.result->physical_time_of_arrival = self->_lf__networkMessage_0.physical_time_of_arrival;
    lf_set(SM.result, networkMessage_0->value);
}
#include "include/api/set_undef.h"
sm_main_self_t* new_SM() {
    sm_main_self_t* self = (sm_main_self_t*)_lf_new_reactor(sizeof(sm_main_self_t));
    #line 24 "/home/plutonh/project/fed-gen/WaitingLine/src/SM.lf"
    self->_lf_inputControlReactionTrigger_0.trigger = &self->_lf__inputControlReactionTrigger_0;
    #line 25 "/home/plutonh/project/fed-gen/WaitingLine/src/SM.lf"
    self->_lf_networkMessage_0.trigger = &self->_lf__networkMessage_0;
    // Set the _width variable for all cases. This will be -2
    // if the reactor is not a bank of reactors.
    self->_lf_SM_width = -2;
    #line 28 "/home/plutonh/project/fed-gen/WaitingLine/src/SM.lf"
    self->_lf__reaction_0.number = 0;
    #line 28 "/home/plutonh/project/fed-gen/WaitingLine/src/SM.lf"
    self->_lf__reaction_0.function = sm_mainreaction_function_0;
    #line 28 "/home/plutonh/project/fed-gen/WaitingLine/src/SM.lf"
    self->_lf__reaction_0.self = self;
    #line 28 "/home/plutonh/project/fed-gen/WaitingLine/src/SM.lf"
    self->_lf__reaction_0.deadline_violation_handler = NULL;
    #line 28 "/home/plutonh/project/fed-gen/WaitingLine/src/SM.lf"
    self->_lf__reaction_0.STP_handler = NULL;
    #line 28 "/home/plutonh/project/fed-gen/WaitingLine/src/SM.lf"
    self->_lf__reaction_0.name = "?";
    #line 28 "/home/plutonh/project/fed-gen/WaitingLine/src/SM.lf"
    self->_lf__reaction_0.mode = NULL;
    #line 35 "/home/plutonh/project/fed-gen/WaitingLine/src/SM.lf"
    self->_lf__reaction_1.number = 1;
    #line 35 "/home/plutonh/project/fed-gen/WaitingLine/src/SM.lf"
    self->_lf__reaction_1.function = sm_mainreaction_function_1;
    #line 35 "/home/plutonh/project/fed-gen/WaitingLine/src/SM.lf"
    self->_lf__reaction_1.self = self;
    #line 35 "/home/plutonh/project/fed-gen/WaitingLine/src/SM.lf"
    self->_lf__reaction_1.deadline_violation_handler = NULL;
    #line 35 "/home/plutonh/project/fed-gen/WaitingLine/src/SM.lf"
    self->_lf__reaction_1.STP_handler = NULL;
    #line 35 "/home/plutonh/project/fed-gen/WaitingLine/src/SM.lf"
    self->_lf__reaction_1.name = "?";
    #line 35 "/home/plutonh/project/fed-gen/WaitingLine/src/SM.lf"
    self->_lf__reaction_1.mode = NULL;
    #line 24 "/home/plutonh/project/fed-gen/WaitingLine/src/SM.lf"
    self->_lf__inputControlReactionTrigger_0.last = NULL;
    #line 24 "/home/plutonh/project/fed-gen/WaitingLine/src/SM.lf"
    #ifdef FEDERATED_DECENTRALIZED
    #line 24 "/home/plutonh/project/fed-gen/WaitingLine/src/SM.lf"
    self->_lf__inputControlReactionTrigger_0.intended_tag = (tag_t) { .time = NEVER, .microstep = 0u};
    #line 24 "/home/plutonh/project/fed-gen/WaitingLine/src/SM.lf"
    #endif // FEDERATED_DECENTRALIZED
    #line 24 "/home/plutonh/project/fed-gen/WaitingLine/src/SM.lf"
    #line 24 "/home/plutonh/project/fed-gen/WaitingLine/src/SM.lf"
    self->_lf__inputControlReactionTrigger_0_reactions[0] = &self->_lf__reaction_0;
    #line 24 "/home/plutonh/project/fed-gen/WaitingLine/src/SM.lf"
    self->_lf__inputControlReactionTrigger_0.reactions = &self->_lf__inputControlReactionTrigger_0_reactions[0];
    #line 24 "/home/plutonh/project/fed-gen/WaitingLine/src/SM.lf"
    self->_lf__inputControlReactionTrigger_0.number_of_reactions = 1;
    #line 24 "/home/plutonh/project/fed-gen/WaitingLine/src/SM.lf"
    #ifdef FEDERATED
    #line 24 "/home/plutonh/project/fed-gen/WaitingLine/src/SM.lf"
    self->_lf__inputControlReactionTrigger_0.physical_time_of_arrival = NEVER;
    #line 24 "/home/plutonh/project/fed-gen/WaitingLine/src/SM.lf"
    #endif // FEDERATED
    self->_lf__inputControlReactionTrigger_0.is_physical = false;
    
    self->_lf__inputControlReactionTrigger_0.tmplt.type.element_size = 0;
    self->_lf_inputControlReactionTrigger_0.type.element_size = 0;
    #line 25 "/home/plutonh/project/fed-gen/WaitingLine/src/SM.lf"
    self->_lf__networkMessage_0.last = NULL;
    #line 25 "/home/plutonh/project/fed-gen/WaitingLine/src/SM.lf"
    #ifdef FEDERATED_DECENTRALIZED
    #line 25 "/home/plutonh/project/fed-gen/WaitingLine/src/SM.lf"
    self->_lf__networkMessage_0.intended_tag = (tag_t) { .time = NEVER, .microstep = 0u};
    #line 25 "/home/plutonh/project/fed-gen/WaitingLine/src/SM.lf"
    #endif // FEDERATED_DECENTRALIZED
    #line 25 "/home/plutonh/project/fed-gen/WaitingLine/src/SM.lf"
    #line 25 "/home/plutonh/project/fed-gen/WaitingLine/src/SM.lf"
    self->_lf__networkMessage_0_reactions[0] = &self->_lf__reaction_1;
    #line 25 "/home/plutonh/project/fed-gen/WaitingLine/src/SM.lf"
    self->_lf__networkMessage_0.reactions = &self->_lf__networkMessage_0_reactions[0];
    #line 25 "/home/plutonh/project/fed-gen/WaitingLine/src/SM.lf"
    self->_lf__networkMessage_0.number_of_reactions = 1;
    #line 25 "/home/plutonh/project/fed-gen/WaitingLine/src/SM.lf"
    #ifdef FEDERATED
    #line 25 "/home/plutonh/project/fed-gen/WaitingLine/src/SM.lf"
    self->_lf__networkMessage_0.physical_time_of_arrival = NEVER;
    #line 25 "/home/plutonh/project/fed-gen/WaitingLine/src/SM.lf"
    #endif // FEDERATED
    self->_lf__networkMessage_0.is_physical = false;
    
    self->_lf__networkMessage_0.tmplt.type.element_size = sizeof(int);
    self->_lf_networkMessage_0.type.element_size = sizeof(int);
    return self;
}
// =============== END reactor class SM
// Array of pointers to timer triggers to be scheduled in _lf_initialize_timers().
trigger_t** _lf_timer_triggers = NULL;
int _lf_timer_triggers_size = 0;
// Array of pointers to startup triggers.
reaction_t** _lf_startup_reactions = NULL;
int _lf_startup_reactions_size = 0;
// Array of pointers to shutdown triggers.
reaction_t** _lf_shutdown_reactions = NULL;
int _lf_shutdown_reactions_size = 0;
// Array of pointers to reset triggers.
reaction_t** _lf_reset_reactions = NULL;
int _lf_reset_reactions_size = 0;
void _lf_initialize_trigger_objects() {
    // Initialize the _lf_clock
    lf_initialize_clock();
    // Create the array that will contain pointers to is_present fields to reset on each step.
    _lf_is_present_fields_size = 3;
    _lf_is_present_fields = (bool**)calloc(3, sizeof(bool*));
    if (_lf_is_present_fields == NULL) lf_print_error_and_exit("Out of memory!");
    _lf_is_present_fields_abbreviated = (bool**)calloc(3, sizeof(bool*));
    if (_lf_is_present_fields_abbreviated == NULL) lf_print_error_and_exit("Out of memory!");
    _lf_is_present_fields_abbreviated_size = 0;
    #ifdef FEDERATED_DECENTRALIZED
    // Create the array that will contain pointers to intended_tag fields to reset on each step.
    _lf_intended_tag_fields_size = 3;
    _lf_intended_tag_fields = (tag_t**)malloc(_lf_intended_tag_fields_size * sizeof(tag_t*));
    
    #endif // FEDERATED_DECENTRALIZED
    int _lf_startup_reactions_count = 0;
    SUPPRESS_UNUSED_WARNING(_lf_startup_reactions_count);
    int _lf_shutdown_reactions_count = 0;
    SUPPRESS_UNUSED_WARNING(_lf_shutdown_reactions_count);
    int _lf_reset_reactions_count = 0;
    SUPPRESS_UNUSED_WARNING(_lf_reset_reactions_count);
    int _lf_timer_triggers_count = 0;
    SUPPRESS_UNUSED_WARNING(_lf_timer_triggers_count);
    int bank_index;
    SUPPRESS_UNUSED_WARNING(bank_index);
    sm_main_self_t* sm_main_self[1];
    SUPPRESS_UNUSED_WARNING(sm_main_self);
    stepmotor_self_t* sm_sm_self[1];
    SUPPRESS_UNUSED_WARNING(sm_sm_self);
    // ***** Start initializing SM of class SM
    sm_main_self[0] = new_SM();
    bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
    // Initializing action SM.inputControlReactionTrigger_0
    sm_main_self[0]->_lf__inputControlReactionTrigger_0.offset = 0;
    sm_main_self[0]->_lf__inputControlReactionTrigger_0.period = -1;
    sm_main_self[0]->_lf__inputControlReactionTrigger_0.mode = NULL;
    // Initializing action SM.networkMessage_0
    sm_main_self[0]->_lf__networkMessage_0.offset = 0;
    sm_main_self[0]->_lf__networkMessage_0.period = -1;
    sm_main_self[0]->_lf__networkMessage_0.mode = NULL;
    _lf_initialize_template((token_template_t*)
            &(sm_main_self[0]->_lf__inputControlReactionTrigger_0),
    0);
    sm_main_self[0]->_lf__inputControlReactionTrigger_0.status = absent;
    _lf_initialize_template((token_template_t*)
            &(sm_main_self[0]->_lf__networkMessage_0),
    sizeof(int));
    sm_main_self[0]->_lf__networkMessage_0.status = absent;
    sm_main_self[0]->_lf__reaction_0.deadline = NEVER;
    sm_main_self[0]->_lf__reaction_1.deadline = NEVER;
    {
        // ***** Start initializing SM.SM of class StepMotor
        sm_sm_self[0] = new_StepMotor();
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        // width of -2 indicates that it is not a multiport.
        sm_sm_self[0]->_lf_result_width = -2;
        //***** End initializing SM.SM
    }
    //***** End initializing SM
    // **** Start deferred initialize for SM
    {
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_0 of SM.
        sm_main_self[0]->_lf__reaction_0.num_outputs = 1;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        sm_main_self[0]->_lf__reaction_0.triggers = (trigger_t***)_lf_allocate(
                1, sizeof(trigger_t**),
                &sm_main_self[0]->base.allocations);
        sm_main_self[0]->_lf__reaction_0.triggered_sizes = (int*)_lf_allocate(
                1, sizeof(int),
                &sm_main_self[0]->base.allocations);
        sm_main_self[0]->_lf__reaction_0.output_produced = (bool**)_lf_allocate(
                1, sizeof(bool*),
                &sm_main_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                sm_main_self[0]->_lf__reaction_0.output_produced[count++] = &sm_main_self[0]->_lf_SM.result.is_present;
            }
        }
        
        // ** End initialization for reaction 0 of SM
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_1 of SM.
        sm_main_self[0]->_lf__reaction_1.num_outputs = 1;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        sm_main_self[0]->_lf__reaction_1.triggers = (trigger_t***)_lf_allocate(
                1, sizeof(trigger_t**),
                &sm_main_self[0]->base.allocations);
        sm_main_self[0]->_lf__reaction_1.triggered_sizes = (int*)_lf_allocate(
                1, sizeof(int),
                &sm_main_self[0]->base.allocations);
        sm_main_self[0]->_lf__reaction_1.output_produced = (bool**)_lf_allocate(
                1, sizeof(bool*),
                &sm_main_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                sm_main_self[0]->_lf__reaction_1.output_produced[count++] = &sm_main_self[0]->_lf_SM.result.is_present;
            }
        }
        
        // ** End initialization for reaction 1 of SM
        // **** Start deferred initialize for SM.SM
        {
        }
        // **** End of deferred initialize for SM.SM
    }
    // **** End of deferred initialize for SM
    // **** Start non-nested deferred initialize for SM
    // Set number of destination reactors for port SM.result.
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
    }
    // **** Start non-nested deferred initialize for SM.SM
    // **** End of non-nested deferred initialize for SM.SM
    // **** End of non-nested deferred initialize for SM
    // Connect inputs and outputs for reactor SM.
    // Connect inputs and outputs for reactor SM.SM.
    {
    }
    // Add port SM.SM.result to array of is_present fields.
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            {
                _lf_is_present_fields[0 + count] = &sm_main_self[0]->_lf_SM.result.is_present;
                #ifdef FEDERATED_DECENTRALIZED
                _lf_intended_tag_fields[0 + count] = &sm_main_self[0]->_lf_SM.result.intended_tag;
                #endif // FEDERATED_DECENTRALIZED
                count++;
            }
        }
    }
    {
        // Add action SM.inputControlReactionTrigger_0 to array of is_present fields.
        _lf_is_present_fields[1] 
                = &sm_main_self[0]->_lf_inputControlReactionTrigger_0.is_present;
        #ifdef FEDERATED_DECENTRALIZED
        // Add action SM.inputControlReactionTrigger_0 to array of intended_tag fields.
        _lf_intended_tag_fields[1] 
                = &sm_main_self[0]->_lf_inputControlReactionTrigger_0.intended_tag;
        #endif // FEDERATED_DECENTRALIZED
    }
    {
        // Add action SM.networkMessage_0 to array of is_present fields.
        _lf_is_present_fields[2] 
                = &sm_main_self[0]->_lf_networkMessage_0.is_present;
        #ifdef FEDERATED_DECENTRALIZED
        // Add action SM.networkMessage_0 to array of intended_tag fields.
        _lf_intended_tag_fields[2] 
                = &sm_main_self[0]->_lf_networkMessage_0.intended_tag;
        #endif // FEDERATED_DECENTRALIZED
    }
    // Set reaction priorities for ReactorInstance SM
    {
        sm_main_self[0]->_lf__reaction_0.chain_id = 1;
        // index is the OR of level 0 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        sm_main_self[0]->_lf__reaction_0.index = 0xffffffffffff0000LL;
        sm_main_self[0]->_lf__reaction_1.chain_id = 1;
        // index is the OR of level 0 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        sm_main_self[0]->_lf__reaction_1.index = 0xffffffffffff0000LL;
    }
    // Initialize the scheduler
    size_t num_reactions_per_level[1] = 
        {2};
    sched_params_t sched_params = (sched_params_t) {
                            .num_reactions_per_level = &num_reactions_per_level[0],
                            .num_reactions_per_level_size = (size_t) 1};
    lf_sched_init(
        (size_t)_lf_number_of_workers,
        &sched_params
    );
    #ifdef EXECUTABLE_PREAMBLE
    _lf_executable_preamble();
    #endif
    #ifdef FEDERATED
    initialize_triggers_for_federate();
    #endif // FEDERATED
}
void _lf_trigger_startup_reactions() {}
void _lf_initialize_timers() {

}
void logical_tag_complete(tag_t tag_to_send) {
#ifdef FEDERATED_CENTRALIZED
        _lf_logical_tag_complete(tag_to_send);
#endif // FEDERATED_CENTRALIZED

}
bool _lf_trigger_shutdown_reactions() {
    return false;
}
#ifndef FEDERATED
void terminate_execution() {}
#endif
