// Code generated by the Lingua Franca compiler from:
// file://home/plutonh/project/src/CountC.lf
#define LOG_LEVEL 2
#define TARGET_FILES_DIRECTORY "/home/plutonh/project/src-gen/CountC"
#include "include/ctarget/ctarget.h"
#include "core/threaded/reactor_threaded.c"
#include "core/threaded/scheduler.h"
#include "core/mixed_radix.h"
int main(int argc, char* argv[]) {
    return lf_reactor_c_main(argc, argv);
}
char* _lf_default_argv[] = { "dummy", "-o", "5", "sec" };
void _lf_set_default_command_line_options() {
        default_argc = 4;
        default_argv = _lf_default_argv;
}
// =============== START reactor class Counter
typedef struct {
    int value;
    bool is_present;
    int num_destinations;
    lf_token_t* token;
    int length;
    void (*destructor) (void* value);
    void* (*copy_constructor) (void* value);
} counter_out_t;
typedef struct {
    struct self_base_t base;
    interval_t offset;
    interval_t period;
    int stride;
    int count;
    counter_out_t _lf_out;
    int _lf_out_width;
    reaction_t _lf__reaction_0;
    trigger_t _lf__t;
    reaction_t* _lf__t_reactions[1];
} counter_self_t;
// ***** Start of method declarations.
// ***** End of method declarations.
#include "include/ctarget/set.h"
void counterreaction_function_0(void* instance_args) {
    #pragma GCC diagnostic push
    #pragma GCC diagnostic ignored "-Wunused-variable"
    counter_self_t* self = (counter_self_t*)instance_args;
    counter_out_t* out = &self->_lf_out;
    #pragma GCC diagnostic pop
    lf_set(out, self->count);
    self->count += self->stride;
}
#include "include/ctarget/set_undef.h"
counter_self_t* new_Counter() {
    counter_self_t* self = (counter_self_t*)_lf_new_reactor(sizeof(counter_self_t));
    self->_lf__reaction_0.number = 0;
    self->_lf__reaction_0.function = counterreaction_function_0;
    self->_lf__reaction_0.self = self;
    self->_lf__reaction_0.deadline_violation_handler = NULL;
    self->_lf__reaction_0.STP_handler = NULL;
    self->_lf__reaction_0.name = "?";
    self->_lf__reaction_0.mode = NULL;
    self->_lf__t.last = NULL;
    self->_lf__t_reactions[0] = &self->_lf__reaction_0;
    self->_lf__t.reactions = &self->_lf__t_reactions[0];
    self->_lf__t.number_of_reactions = 1;
    self->_lf__t.is_timer = true;
    return self;
}
// =============== END reactor class Counter
// =============== START reactor class Printer
typedef struct {
    int value;
    bool is_present;
    int num_destinations;
    lf_token_t* token;
    int length;
    void (*destructor) (void* value);
    void* (*copy_constructor) (void* value);
} printer_in_t;
typedef struct {
    struct self_base_t base;
    printer_in_t* _lf_in;
    // width of -2 indicates that it is not a multiport.
    int _lf_in_width;
    // Default input (in case it does not get connected)
    printer_in_t _lf_default__in;
    reaction_t _lf__reaction_0;
    reaction_t _lf__reaction_1;
    trigger_t _lf__shutdown;
    reaction_t* _lf__shutdown_reactions[1];
    trigger_t _lf__in;
    reaction_t* _lf__in_reactions[1];
} printer_self_t;
// ***** Start of method declarations.
// ***** End of method declarations.
#include "include/ctarget/set.h"
void printerreaction_function_0(void* instance_args) {
    #pragma GCC diagnostic push
    #pragma GCC diagnostic ignored "-Wunused-variable"
    printer_self_t* self = (printer_self_t*)instance_args;
    printer_in_t* in = self->_lf_in;
    int in_width = self->_lf_in_width;
    #pragma GCC diagnostic pop
    lf_print("Hello World! %d\n", in->value);
}
#include "include/ctarget/set_undef.h"
#include "include/ctarget/set.h"
void printerreaction_function_1(void* instance_args) {
    #pragma GCC diagnostic push
    #pragma GCC diagnostic ignored "-Wunused-variable"
    printer_self_t* self = (printer_self_t*)instance_args;
    #pragma GCC diagnostic pop
    lf_print("Shutdown Invoked!\n");
}
#include "include/ctarget/set_undef.h"
printer_self_t* new_Printer() {
    printer_self_t* self = (printer_self_t*)_lf_new_reactor(sizeof(printer_self_t));
    // Set input by default to an always absent default input.
    self->_lf_in = &self->_lf_default__in;
    self->_lf__reaction_0.number = 0;
    self->_lf__reaction_0.function = printerreaction_function_0;
    self->_lf__reaction_0.self = self;
    self->_lf__reaction_0.deadline_violation_handler = NULL;
    self->_lf__reaction_0.STP_handler = NULL;
    self->_lf__reaction_0.name = "?";
    self->_lf__reaction_0.mode = NULL;
    self->_lf__reaction_1.number = 1;
    self->_lf__reaction_1.function = printerreaction_function_1;
    self->_lf__reaction_1.self = self;
    self->_lf__reaction_1.deadline_violation_handler = NULL;
    self->_lf__reaction_1.STP_handler = NULL;
    self->_lf__reaction_1.name = "?";
    self->_lf__reaction_1.mode = NULL;
    self->_lf__shutdown_reactions[0] = &self->_lf__reaction_1;
    self->_lf__shutdown.last = NULL;
    self->_lf__shutdown.reactions = &self->_lf__shutdown_reactions[0];
    self->_lf__shutdown.number_of_reactions = 1;
    self->_lf__shutdown.is_timer = false;
    self->_lf__in.last = NULL;
    self->_lf__in_reactions[0] = &self->_lf__reaction_0;
    self->_lf__in.reactions = &self->_lf__in_reactions[0];
    self->_lf__in.number_of_reactions = 1;
    self->_lf__in.element_size = sizeof(int);
    return self;
}
// =============== END reactor class Printer
// =============== START reactor class CountC
typedef struct {
    struct self_base_t base;
} countc_self_t;
// ***** Start of method declarations.
// ***** End of method declarations.
countc_self_t* new_CountC() {
    countc_self_t* self = (countc_self_t*)_lf_new_reactor(sizeof(countc_self_t));
    return self;
}
// =============== END reactor class CountC
// Array of pointers to timer triggers to be scheduled in _lf_initialize_timers().
trigger_t* _lf_timer_triggers[1];
int _lf_timer_triggers_size = 1;
// Array of pointers to startup triggers.
reaction_t** _lf_startup_reactions = NULL;
int _lf_startup_reactions_size = 0;
// Array of pointers to shutdown triggers.
reaction_t* _lf_shutdown_reactions[1];
int _lf_shutdown_reactions_size = 1;
// Array of pointers to reset triggers.
reaction_t** _lf_reset_reactions = NULL;
int _lf_reset_reactions_size = 0;
trigger_t* _lf_action_for_port(int port_id) {
        return NULL;
}
void _lf_initialize_trigger_objects() {
    // Initialize the _lf_clock
    lf_initialize_clock();
    // Create the array that will contain pointers to is_present fields to reset on each step.
    _lf_is_present_fields_size = 1;
    _lf_is_present_fields = (bool**)calloc(1, sizeof(bool*));
    if (_lf_is_present_fields == NULL) lf_print_error_and_exit("Out of memory!");
    _lf_is_present_fields_abbreviated = (bool**)calloc(1, sizeof(bool*));
    if (_lf_is_present_fields_abbreviated == NULL) lf_print_error_and_exit("Out of memory!");
    _lf_is_present_fields_abbreviated_size = 0;
    int _lf_startup_reactions_count = 0;
    int _lf_shutdown_reactions_count = 0;
    int _lf_reset_reactions_count = 0;
    int _lf_timer_triggers_count = 0;
    int _lf_tokens_with_ref_count_count = 0;
    countc_self_t* countc_self[1];
    counter_self_t* countc_c_self[1];
    printer_self_t* countc_p_self[1];
    // ***** Start initializing CountC of class CountC
    countc_self[0] = new_CountC();
    int bank_index = 0;
    {
        // ***** Start initializing CountC.c of class Counter
        countc_c_self[0] = new_Counter();
        int bank_index = 0;
        countc_c_self[0]->offset = 0;
        countc_c_self[0]->period = SEC(1);
        countc_c_self[0]->stride = 5;
        // width of -2 indicates that it is not a multiport.
        countc_c_self[0]->_lf_out_width = -2;
        { // For scoping
            static int _initial = 0;
            countc_c_self[0]->count = _initial;
        } // End scoping.
        // Initializing timer CountC.c.t.
        countc_c_self[0]->_lf__t.offset = 0;
        countc_c_self[0]->_lf__t.period = SEC(1);
        _lf_timer_triggers[_lf_timer_triggers_count++] = &countc_c_self[0]->_lf__t;
        countc_c_self[0]->_lf__t.mode = NULL;
        countc_c_self[0]->_lf__reaction_0.deadline = NEVER;
        //***** End initializing CountC.c
    }
    {
        // ***** Start initializing CountC.p of class Printer
        countc_p_self[0] = new_Printer();
        int bank_index = 0;
        // width of -2 indicates that it is not a multiport.
        countc_p_self[0]->_lf_in_width = -2;
        _lf_shutdown_reactions[_lf_shutdown_reactions_count++] = &countc_p_self[0]->_lf__reaction_1;
        countc_p_self[0]->_lf__reaction_0.deadline = NEVER;
        countc_p_self[0]->_lf__reaction_1.deadline = NEVER;
        //***** End initializing CountC.p
    }
    //***** End initializing CountC
    // **** Start deferred initialize for CountC
    {
        // **** Start deferred initialize for CountC.c
        {
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_0 of CountC.c.
            countc_c_self[0]->_lf__reaction_0.num_outputs = 1;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            countc_c_self[0]->_lf__reaction_0.triggers = (trigger_t***)_lf_allocate(
                    1, sizeof(trigger_t**),
                    &countc_c_self[0]->base.allocations);
            countc_c_self[0]->_lf__reaction_0.triggered_sizes = (int*)_lf_allocate(
                    1, sizeof(int),
                    &countc_c_self[0]->base.allocations);
            countc_c_self[0]->_lf__reaction_0.output_produced = (bool**)_lf_allocate(
                    1, sizeof(bool*),
                    &countc_c_self[0]->base.allocations);
            {
                int count = 0;
                {
                    countc_c_self[0]->_lf__reaction_0.output_produced[count++] = &countc_c_self[0]->_lf_out.is_present;
                }
            }
            
            // ** End initialization for reaction 0 of CountC.c
        }
        // **** End of deferred initialize for CountC.c
        // **** Start deferred initialize for CountC.p
        {
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_0 of CountC.p.
            countc_p_self[0]->_lf__reaction_0.num_outputs = 0;
            {
                int count = 0;
            }
            
            // ** End initialization for reaction 0 of CountC.p
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of CountC.p.
            countc_p_self[0]->_lf__reaction_1.num_outputs = 0;
            {
                int count = 0;
            }
            
            // ** End initialization for reaction 1 of CountC.p
        }
        // **** End of deferred initialize for CountC.p
    }
    // **** End of deferred initialize for CountC
    // **** Start non-nested deferred initialize for CountC
    // **** Start non-nested deferred initialize for CountC.c
    // For reference counting, set num_destinations for port CountC.c.out.
    // Iterate over range CountC.c.out(0,1)->[CountC.p.in(0,1)].
    {
        int src_runtime = 0; // Runtime index.
        int src_channel = 0; // Channel index.
        int src_bank = 0; // Bank index.
        int range_count = 0;
        countc_c_self[src_runtime]->_lf_out.num_destinations = 1;
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range CountC.c.out(0,1)->[CountC.p.in(0,1)].
        {
            int src_runtime = 0; // Runtime index.
            int src_channel = 0; // Channel index.
            int src_bank = 0; // Bank index.
            int range_count = 0;
            // Reaction 0 of CountC.c triggers 1 downstream reactions
            // through port CountC.c.out.
            countc_c_self[src_runtime]->_lf__reaction_0.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 0 of CountC.c, allocate an
            // array of trigger pointers for downstream reactions through port CountC.c.out
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &countc_c_self[src_runtime]->base.allocations); 
            countc_c_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges CountC.c.out(0,1)->[CountC.p.in(0,1)] and CountC.p.in(0,1).
        {
            int src_runtime = 0; // Runtime index.
            int src_channel = 0; // Channel index.
            int src_bank = 0; // Bank index.
            // Iterate over range CountC.p.in(0,1).
            {
                int dst_runtime = 0; // Runtime index.
                int dst_channel = 0; // Channel index.
                int dst_bank = 0; // Bank index.
                int range_count = 0;
                // Point to destination port CountC.p.in's trigger struct.
                countc_c_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime] + src_channel][0] = &countc_p_self[dst_runtime]->_lf__in;
            }
        }
    }
    // **** End of non-nested deferred initialize for CountC.c
    // **** Start non-nested deferred initialize for CountC.p
    // **** End of non-nested deferred initialize for CountC.p
    // **** End of non-nested deferred initialize for CountC
    // Connect inputs and outputs for reactor CountC.
    // Connect inputs and outputs for reactor CountC.c.
    // Connect CountC.c.out(0,1)->[CountC.p.in(0,1)] to port CountC.p.in(0,1)
    // Iterate over ranges CountC.c.out(0,1)->[CountC.p.in(0,1)] and CountC.p.in(0,1).
    {
        int src_runtime = 0; // Runtime index.
        int src_channel = 0; // Channel index.
        int src_bank = 0; // Bank index.
        // Iterate over range CountC.p.in(0,1).
        {
            int dst_runtime = 0; // Runtime index.
            int dst_channel = 0; // Channel index.
            int dst_bank = 0; // Bank index.
            int range_count = 0;
            countc_p_self[dst_runtime]->_lf_in = (printer_in_t*)&countc_c_self[src_runtime]->_lf_out;
        }
    }
    // Connect inputs and outputs for reactor CountC.p.
    {
    }
    {
    }
    {
        int count = 0;
        {
            // Add port CountC.c.out to array of is_present fields.
            _lf_is_present_fields[0 + count] = &countc_c_self[0]->_lf_out.is_present;
            count++;
        }
    }
    // Set reaction priorities for ReactorInstance CountC
    {
        // Set reaction priorities for ReactorInstance CountC.c
        {
            countc_c_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 0 and 
            // deadline 140737488355327 shifted left 16 bits.
            countc_c_self[0]->_lf__reaction_0.index = 0x7fffffffffff0000LL;
        }
        // Set reaction priorities for ReactorInstance CountC.p
        {
            countc_p_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 1 and 
            // deadline 140737488355327 shifted left 16 bits.
            countc_p_self[0]->_lf__reaction_0.index = 0x7fffffffffff0001LL;
            countc_p_self[0]->_lf__reaction_1.chain_id = 1;
            // index is the OR of level 2 and 
            // deadline 140737488355327 shifted left 16 bits.
            countc_p_self[0]->_lf__reaction_1.index = 0x7fffffffffff0002LL;
        }
    }
    // Initialize the scheduler
    size_t num_reactions_per_level[3] = 
        {1, 1, 1};
    sched_params_t sched_params = (sched_params_t) {
                            .num_reactions_per_level = &num_reactions_per_level[0],
                            .num_reactions_per_level_size = (size_t) 3};
    lf_sched_init(
        (size_t)_lf_number_of_workers,
        &sched_params
    );
}
void _lf_trigger_startup_reactions() {}
void _lf_initialize_timers() {
    for (int i = 0; i < _lf_timer_triggers_size; i++) {
        if (_lf_timer_triggers[i] != NULL) {
            _lf_initialize_timer(_lf_timer_triggers[i]);
        }
    }
}
void logical_tag_complete(tag_t tag_to_send) {
}
bool _lf_trigger_shutdown_reactions() {
    for (int i = 0; i < _lf_shutdown_reactions_size; i++) {
        if (_lf_shutdown_reactions[i] != NULL) {
            _lf_trigger_reaction(_lf_shutdown_reactions[i], -1);
        }
    }
    return true;
}
void terminate_execution() {}
