// Code generated by the Lingua Franca compiler from:
// file://home/plutonh/project/fed-gen/WaitingLine/src/H.lf
#define LOG_LEVEL 2
#define TARGET_FILES_DIRECTORY "/home/plutonh/project/fed-gen/WaitingLine/src-gen/H"
#include "include/api/api.h"
#include "core/reactor.h"
#include "core/reactor_common.h"
#include "core/threaded/scheduler.h"
#include "core/mixed_radix.h"
#include "core/port.h"
int lf_reactor_c_main(int argc, const char* argv[]);
#include "core/federated/federate.h"
#include "core/federated/net_common.h"
#include "include/_H_preamble.h"
int main(int argc, const char* argv[]) {
    return lf_reactor_c_main(argc, argv);
}
const char* _lf_default_argv[] = { "dummy", "-k", "true" };
void _lf_set_default_command_line_options() {
        default_argc = 3;
        default_argv = _lf_default_argv;
}
// =============== START reactor class HTTPServer
typedef struct {
    token_type_t type;
    lf_token_t* token;
    size_t length;
    bool is_present;
    lf_sparse_io_record_t* sparse_record;
    int destination_channel;
    int num_destinations;
    int value;
    #ifdef FEDERATED
    #ifdef FEDERATED_DECENTRALIZED
    tag_t intended_tag;
    #endif
    interval_t physical_time_of_arrival;
    #endif
} httpserver_result_t;
typedef struct {
    token_type_t type;
    lf_token_t* token;
    size_t length;
    bool is_present;
    lf_sparse_io_record_t* sparse_record;
    int destination_channel;
    int num_destinations;
    int value;
    #ifdef FEDERATED
    #ifdef FEDERATED_DECENTRALIZED
    tag_t intended_tag;
    #endif
    interval_t physical_time_of_arrival;
    #endif
} httpserver_control_t;
typedef struct {
    struct self_base_t base;
    #line 17 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    httpserver_result_t* _lf_result;
    #line 17 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    // width of -2 indicates that it is not a multiport.
    #line 17 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    int _lf_result_width;
    #line 17 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    // Default input (in case it does not get connected)
    #line 17 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    httpserver_result_t _lf_default__result;
    #line 18 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    httpserver_control_t _lf_control;
    #line 18 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    int _lf_control_width;
    #line 17 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    trigger_t _lf__result;
    #ifdef FEDERATED
    
    #endif // FEDERATED
} httpserver_self_t;
// ***** Start of method declarations.
// ***** End of method declarations.
httpserver_self_t* new_HTTPServer() {
    httpserver_self_t* self = (httpserver_self_t*)_lf_new_reactor(sizeof(httpserver_self_t));
    #line 17 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    // Set input by default to an always absent default input.
    #line 17 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    self->_lf_result = &self->_lf_default__result;
    #line 17 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    self->_lf__result.last = NULL;
    #line 17 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    #ifdef FEDERATED_DECENTRALIZED
    #line 17 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    self->_lf__result.intended_tag = (tag_t) { .time = NEVER, .microstep = 0u};
    #line 17 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    #endif // FEDERATED_DECENTRALIZED
    self->_lf__result.tmplt.type.element_size = sizeof(int);
    return self;
}
// =============== END reactor class HTTPServer
// =============== START reactor class H
typedef struct {
    token_type_t type;
    lf_token_t* token;
    size_t length;
    bool is_present;
    bool has_value;
    trigger_t* trigger;
    #ifdef FEDERATED
    #ifdef FEDERATED_DECENTRALIZED
    tag_t intended_tag;
    #endif
    interval_t physical_time_of_arrival;
    #endif
} h_outputControlReactionTrigger_t;
typedef struct {
    token_type_t type;
    lf_token_t* token;
    size_t length;
    bool is_present;
    bool has_value;
    trigger_t* trigger;
    #ifdef FEDERATED
    #ifdef FEDERATED_DECENTRALIZED
    tag_t intended_tag;
    #endif
    interval_t physical_time_of_arrival;
    #endif
} h_inputControlReactionTrigger_t;
typedef struct {
    token_type_t type;
    lf_token_t* token;
    size_t length;
    bool is_present;
    bool has_value;
    trigger_t* trigger;
    int value;
    #ifdef FEDERATED
    #ifdef FEDERATED_DECENTRALIZED
    tag_t intended_tag;
    #endif
    interval_t physical_time_of_arrival;
    #endif
} h_networkMessage_t;
typedef struct {
    struct self_base_t base;
    #line 25 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    h_outputControlReactionTrigger_t _lf_outputControlReactionTrigger;
    #line 26 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    h_inputControlReactionTrigger_t _lf_inputControlReactionTrigger;
    #line 27 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    h_networkMessage_t _lf_networkMessage;
    struct {
        #line 17 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
        httpserver_result_t result;
        #line 18 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
        httpserver_control_t* control;
        #line 18 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
        trigger_t control_trigger;
        #line 18 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
        reaction_t* control_reactions[1];
    } _lf_H;
    int _lf_H_width;
    #line 30 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    reaction_t _lf__reaction_0;
    #line 37 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    reaction_t _lf__reaction_1;
    #line 43 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    reaction_t _lf__reaction_2;
    #line 51 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    reaction_t _lf__reaction_3;
    #line 25 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    trigger_t _lf__outputControlReactionTrigger;
    #line 25 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    reaction_t* _lf__outputControlReactionTrigger_reactions[1];
    #line 26 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    trigger_t _lf__inputControlReactionTrigger;
    #line 26 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    reaction_t* _lf__inputControlReactionTrigger_reactions[1];
    #line 27 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    trigger_t _lf__networkMessage;
    #line 27 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    reaction_t* _lf__networkMessage_reactions[1];
} h_main_self_t;
// ***** Start of method declarations.
// ***** End of method declarations.
#include "include/api/set.h"
void h_mainreaction_function_0(void* instance_args) {
    h_main_self_t* self = (h_main_self_t*)instance_args; SUPPRESS_UNUSED_WARNING(self);
    struct H {
        httpserver_result_t* result;
    
    } H;
    // Expose the action struct as a local variable whose name matches the action name.
    h_inputControlReactionTrigger_t* inputControlReactionTrigger = &self->_lf_inputControlReactionTrigger;
    // Set the fields of the action struct to match the current trigger.
    inputControlReactionTrigger->is_present = (bool)self->_lf__inputControlReactionTrigger.status;
    inputControlReactionTrigger->has_value = ((self->_lf__inputControlReactionTrigger.tmplt.token) != NULL && (self->_lf__inputControlReactionTrigger.tmplt.token)->value != NULL);
    _lf_replace_template_token((token_template_t*)inputControlReactionTrigger, (self->_lf__inputControlReactionTrigger.tmplt.token));
    H.result = &(self->_lf_H.result);
    #line 32 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    // **** This reaction is unordered.
    interval_t max_STP = 0LL;
    // Wait until the port status is known
    wait_until_port_status_known(0, max_STP);
}
#include "include/api/set_undef.h"
#include "include/api/set.h"
void h_mainreaction_function_1(void* instance_args) {
    h_main_self_t* self = (h_main_self_t*)instance_args; SUPPRESS_UNUSED_WARNING(self);
    struct H {
        httpserver_result_t* result;
    
    } H;
    // Expose the action struct as a local variable whose name matches the action name.
    h_networkMessage_t* networkMessage = &self->_lf_networkMessage;
    // Set the fields of the action struct to match the current trigger.
    networkMessage->is_present = (bool)self->_lf__networkMessage.status;
    networkMessage->has_value = ((self->_lf__networkMessage.tmplt.token) != NULL && (self->_lf__networkMessage.tmplt.token)->value != NULL);
    _lf_replace_template_token((token_template_t*)networkMessage, (self->_lf__networkMessage.tmplt.token));
    if (networkMessage->has_value) {
        networkMessage->value = *(int*)(self->_lf__networkMessage.tmplt.token)->value;
    }
    H.result = &(self->_lf_H.result);
    #line 39 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    // **** This reaction is unordered.
    H.result->physical_time_of_arrival = self->_lf__networkMessage.physical_time_of_arrival;
    lf_set(H.result, networkMessage->value);
}
#include "include/api/set_undef.h"
#include "include/api/set.h"
void h_mainreaction_function_2(void* instance_args) {
    h_main_self_t* self = (h_main_self_t*)instance_args; SUPPRESS_UNUSED_WARNING(self);
    struct H {
        httpserver_control_t* control;
    
    } H;
    H.control = self->_lf_H.control;
    #line 45 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    // **** This reaction is unordered.
    // Sending from H.control in federate H to A.control in federate A
    if (!H.control->is_present) return;
    size_t message_length = sizeof(int);
    send_timed_message(NEVER, MSG_TYPE_TAGGED_MESSAGE, 4, 0, "federate 0 via the RTI", message_length, (unsigned char*)&H.control->value);
}
#include "include/api/set_undef.h"
#include "include/api/set.h"
void h_mainreaction_function_3(void* instance_args) {
    h_main_self_t* self = (h_main_self_t*)instance_args; SUPPRESS_UNUSED_WARNING(self);
    struct H {
        httpserver_control_t* control;
    
    } H;
    // Expose the action struct as a local variable whose name matches the action name.
    h_outputControlReactionTrigger_t* outputControlReactionTrigger = &self->_lf_outputControlReactionTrigger;
    // Set the fields of the action struct to match the current trigger.
    outputControlReactionTrigger->is_present = (bool)self->_lf__outputControlReactionTrigger.status;
    outputControlReactionTrigger->has_value = ((self->_lf__outputControlReactionTrigger.tmplt.token) != NULL && (self->_lf__outputControlReactionTrigger.tmplt.token)->value != NULL);
    _lf_replace_template_token((token_template_t*)outputControlReactionTrigger, (self->_lf__outputControlReactionTrigger.tmplt.token));
    H.control = self->_lf_H.control;
    #line 53 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    // **** This reaction is unordered.
    // If the output port has not been lf_set for the current logical time,
    // send an ABSENT message to the receiving federate
    LF_PRINT_LOG("Contemplating whether to send port "
              "absent for port %d to federate %d.",
              4, 0);
    if (H.control == NULL || !H.control->is_present) {
        // The output port is NULL or it is not present.
        send_port_absent_to_federate(NEVER, 4, 0);
    }
}
#include "include/api/set_undef.h"
h_main_self_t* new_H() {
    h_main_self_t* self = (h_main_self_t*)_lf_new_reactor(sizeof(h_main_self_t));
    #line 25 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    self->_lf_outputControlReactionTrigger.trigger = &self->_lf__outputControlReactionTrigger;
    #line 26 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    self->_lf_inputControlReactionTrigger.trigger = &self->_lf__inputControlReactionTrigger;
    #line 27 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    self->_lf_networkMessage.trigger = &self->_lf__networkMessage;
    // Set the _width variable for all cases. This will be -2
    // if the reactor is not a bank of reactors.
    self->_lf_H_width = -2;
    #line 18 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    #ifdef FEDERATED_DECENTRALIZED
    #line 18 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    self->_lf_H.control_trigger.intended_tag = (tag_t) { .time = NEVER, .microstep = 0u};
    #line 18 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    #endif // FEDERATED_DECENTRALIZED
    #line 18 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    self->_lf_H.control_reactions[0] = &self->_lf__reaction_2;
    #line 18 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    self->_lf_H.control_trigger.reactions = self->_lf_H.control_reactions;
    #line 18 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    self->_lf_H.control_trigger.last = NULL;
    #line 18 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    self->_lf_H.control_trigger.number_of_reactions = 1;
    #line 18 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    #ifdef FEDERATED
    #line 18 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    self->_lf_H.control_trigger.physical_time_of_arrival = NEVER;
    #line 18 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    #endif // FEDERATED
    #line 30 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    self->_lf__reaction_0.number = 0;
    #line 30 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    self->_lf__reaction_0.function = h_mainreaction_function_0;
    #line 30 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    self->_lf__reaction_0.self = self;
    #line 30 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    self->_lf__reaction_0.deadline_violation_handler = NULL;
    #line 30 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    self->_lf__reaction_0.STP_handler = NULL;
    #line 30 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    self->_lf__reaction_0.name = "?";
    #line 30 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    self->_lf__reaction_0.mode = NULL;
    #line 37 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    self->_lf__reaction_1.number = 1;
    #line 37 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    self->_lf__reaction_1.function = h_mainreaction_function_1;
    #line 37 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    self->_lf__reaction_1.self = self;
    #line 37 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    self->_lf__reaction_1.deadline_violation_handler = NULL;
    #line 37 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    self->_lf__reaction_1.STP_handler = NULL;
    #line 37 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    self->_lf__reaction_1.name = "?";
    #line 37 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    self->_lf__reaction_1.mode = NULL;
    #line 43 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    self->_lf__reaction_2.number = 2;
    #line 43 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    self->_lf__reaction_2.function = h_mainreaction_function_2;
    #line 43 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    self->_lf__reaction_2.self = self;
    #line 43 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    self->_lf__reaction_2.deadline_violation_handler = NULL;
    #line 43 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    self->_lf__reaction_2.STP_handler = NULL;
    #line 43 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    self->_lf__reaction_2.name = "?";
    #line 43 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    self->_lf__reaction_2.mode = NULL;
    #line 51 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    self->_lf__reaction_3.number = 3;
    #line 51 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    self->_lf__reaction_3.function = h_mainreaction_function_3;
    #line 51 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    self->_lf__reaction_3.self = self;
    #line 51 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    self->_lf__reaction_3.deadline_violation_handler = NULL;
    #line 51 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    self->_lf__reaction_3.STP_handler = NULL;
    #line 51 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    self->_lf__reaction_3.name = "?";
    #line 51 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    self->_lf__reaction_3.mode = NULL;
    #line 25 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    self->_lf__outputControlReactionTrigger.last = NULL;
    #line 25 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    #ifdef FEDERATED_DECENTRALIZED
    #line 25 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    self->_lf__outputControlReactionTrigger.intended_tag = (tag_t) { .time = NEVER, .microstep = 0u};
    #line 25 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    #endif // FEDERATED_DECENTRALIZED
    #line 25 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    #line 25 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    self->_lf__outputControlReactionTrigger_reactions[0] = &self->_lf__reaction_3;
    #line 25 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    self->_lf__outputControlReactionTrigger.reactions = &self->_lf__outputControlReactionTrigger_reactions[0];
    #line 25 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    self->_lf__outputControlReactionTrigger.number_of_reactions = 1;
    #line 25 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    #ifdef FEDERATED
    #line 25 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    self->_lf__outputControlReactionTrigger.physical_time_of_arrival = NEVER;
    #line 25 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    #endif // FEDERATED
    self->_lf__outputControlReactionTrigger.is_physical = false;
    
    self->_lf__outputControlReactionTrigger.tmplt.type.element_size = 0;
    self->_lf_outputControlReactionTrigger.type.element_size = 0;
    #line 26 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    self->_lf__inputControlReactionTrigger.last = NULL;
    #line 26 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    #ifdef FEDERATED_DECENTRALIZED
    #line 26 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    self->_lf__inputControlReactionTrigger.intended_tag = (tag_t) { .time = NEVER, .microstep = 0u};
    #line 26 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    #endif // FEDERATED_DECENTRALIZED
    #line 26 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    #line 26 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    self->_lf__inputControlReactionTrigger_reactions[0] = &self->_lf__reaction_0;
    #line 26 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    self->_lf__inputControlReactionTrigger.reactions = &self->_lf__inputControlReactionTrigger_reactions[0];
    #line 26 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    self->_lf__inputControlReactionTrigger.number_of_reactions = 1;
    #line 26 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    #ifdef FEDERATED
    #line 26 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    self->_lf__inputControlReactionTrigger.physical_time_of_arrival = NEVER;
    #line 26 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    #endif // FEDERATED
    self->_lf__inputControlReactionTrigger.is_physical = false;
    
    self->_lf__inputControlReactionTrigger.tmplt.type.element_size = 0;
    self->_lf_inputControlReactionTrigger.type.element_size = 0;
    #line 27 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    self->_lf__networkMessage.last = NULL;
    #line 27 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    #ifdef FEDERATED_DECENTRALIZED
    #line 27 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    self->_lf__networkMessage.intended_tag = (tag_t) { .time = NEVER, .microstep = 0u};
    #line 27 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    #endif // FEDERATED_DECENTRALIZED
    #line 27 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    #line 27 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    self->_lf__networkMessage_reactions[0] = &self->_lf__reaction_1;
    #line 27 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    self->_lf__networkMessage.reactions = &self->_lf__networkMessage_reactions[0];
    #line 27 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    self->_lf__networkMessage.number_of_reactions = 1;
    #line 27 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    #ifdef FEDERATED
    #line 27 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    self->_lf__networkMessage.physical_time_of_arrival = NEVER;
    #line 27 "/home/plutonh/project/fed-gen/WaitingLine/src/H.lf"
    #endif // FEDERATED
    self->_lf__networkMessage.is_physical = false;
    
    self->_lf__networkMessage.tmplt.type.element_size = sizeof(int);
    self->_lf_networkMessage.type.element_size = sizeof(int);
    return self;
}
// =============== END reactor class H
// Array of pointers to timer triggers to be scheduled in _lf_initialize_timers().
trigger_t** _lf_timer_triggers = NULL;
int _lf_timer_triggers_size = 0;
// Array of pointers to startup triggers.
reaction_t** _lf_startup_reactions = NULL;
int _lf_startup_reactions_size = 0;
// Array of pointers to shutdown triggers.
reaction_t** _lf_shutdown_reactions = NULL;
int _lf_shutdown_reactions_size = 0;
// Array of pointers to reset triggers.
reaction_t** _lf_reset_reactions = NULL;
int _lf_reset_reactions_size = 0;
void _lf_initialize_trigger_objects() {
    // Initialize the _lf_clock
    lf_initialize_clock();
    // Create the array that will contain pointers to is_present fields to reset on each step.
    _lf_is_present_fields_size = 4;
    _lf_is_present_fields = (bool**)calloc(4, sizeof(bool*));
    if (_lf_is_present_fields == NULL) lf_print_error_and_exit("Out of memory!");
    _lf_is_present_fields_abbreviated = (bool**)calloc(4, sizeof(bool*));
    if (_lf_is_present_fields_abbreviated == NULL) lf_print_error_and_exit("Out of memory!");
    _lf_is_present_fields_abbreviated_size = 0;
    #ifdef FEDERATED_DECENTRALIZED
    // Create the array that will contain pointers to intended_tag fields to reset on each step.
    _lf_intended_tag_fields_size = 4;
    _lf_intended_tag_fields = (tag_t**)malloc(_lf_intended_tag_fields_size * sizeof(tag_t*));
    
    #endif // FEDERATED_DECENTRALIZED
    int _lf_startup_reactions_count = 0;
    SUPPRESS_UNUSED_WARNING(_lf_startup_reactions_count);
    int _lf_shutdown_reactions_count = 0;
    SUPPRESS_UNUSED_WARNING(_lf_shutdown_reactions_count);
    int _lf_reset_reactions_count = 0;
    SUPPRESS_UNUSED_WARNING(_lf_reset_reactions_count);
    int _lf_timer_triggers_count = 0;
    SUPPRESS_UNUSED_WARNING(_lf_timer_triggers_count);
    int bank_index;
    SUPPRESS_UNUSED_WARNING(bank_index);
    h_main_self_t* h_main_self[1];
    SUPPRESS_UNUSED_WARNING(h_main_self);
    httpserver_self_t* h_h_self[1];
    SUPPRESS_UNUSED_WARNING(h_h_self);
    // ***** Start initializing H of class H
    h_main_self[0] = new_H();
    bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
    // Initializing action H.outputControlReactionTrigger
    h_main_self[0]->_lf__outputControlReactionTrigger.offset = 0;
    h_main_self[0]->_lf__outputControlReactionTrigger.period = -1;
    h_main_self[0]->_lf__outputControlReactionTrigger.mode = NULL;
    // Initializing action H.inputControlReactionTrigger
    h_main_self[0]->_lf__inputControlReactionTrigger.offset = 0;
    h_main_self[0]->_lf__inputControlReactionTrigger.period = -1;
    h_main_self[0]->_lf__inputControlReactionTrigger.mode = NULL;
    // Initializing action H.networkMessage
    h_main_self[0]->_lf__networkMessage.offset = 0;
    h_main_self[0]->_lf__networkMessage.period = -1;
    h_main_self[0]->_lf__networkMessage.mode = NULL;
    _lf_initialize_template((token_template_t*)
            &(h_main_self[0]->_lf__outputControlReactionTrigger),
    0);
    h_main_self[0]->_lf__outputControlReactionTrigger.status = absent;
    _lf_initialize_template((token_template_t*)
            &(h_main_self[0]->_lf__inputControlReactionTrigger),
    0);
    h_main_self[0]->_lf__inputControlReactionTrigger.status = absent;
    _lf_initialize_template((token_template_t*)
            &(h_main_self[0]->_lf__networkMessage),
    sizeof(int));
    h_main_self[0]->_lf__networkMessage.status = absent;
    h_main_self[0]->_lf__reaction_0.deadline = NEVER;
    h_main_self[0]->_lf__reaction_1.deadline = NEVER;
    h_main_self[0]->_lf__reaction_2.deadline = NEVER;
    h_main_self[0]->_lf__reaction_3.deadline = NEVER;
    {
        // ***** Start initializing H.H of class HTTPServer
        h_h_self[0] = new_HTTPServer();
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        // width of -2 indicates that it is not a multiport.
        h_h_self[0]->_lf_control_width = -2;
        // width of -2 indicates that it is not a multiport.
        h_h_self[0]->_lf_result_width = -2;
        //***** End initializing H.H
    }
    //***** End initializing H
    // **** Start deferred initialize for H
    {
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_0 of H.
        h_main_self[0]->_lf__reaction_0.num_outputs = 1;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        h_main_self[0]->_lf__reaction_0.triggers = (trigger_t***)_lf_allocate(
                1, sizeof(trigger_t**),
                &h_main_self[0]->base.allocations);
        h_main_self[0]->_lf__reaction_0.triggered_sizes = (int*)_lf_allocate(
                1, sizeof(int),
                &h_main_self[0]->base.allocations);
        h_main_self[0]->_lf__reaction_0.output_produced = (bool**)_lf_allocate(
                1, sizeof(bool*),
                &h_main_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                h_main_self[0]->_lf__reaction_0.output_produced[count++] = &h_main_self[0]->_lf_H.result.is_present;
            }
        }
        
        // ** End initialization for reaction 0 of H
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_1 of H.
        h_main_self[0]->_lf__reaction_1.num_outputs = 1;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        h_main_self[0]->_lf__reaction_1.triggers = (trigger_t***)_lf_allocate(
                1, sizeof(trigger_t**),
                &h_main_self[0]->base.allocations);
        h_main_self[0]->_lf__reaction_1.triggered_sizes = (int*)_lf_allocate(
                1, sizeof(int),
                &h_main_self[0]->base.allocations);
        h_main_self[0]->_lf__reaction_1.output_produced = (bool**)_lf_allocate(
                1, sizeof(bool*),
                &h_main_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                h_main_self[0]->_lf__reaction_1.output_produced[count++] = &h_main_self[0]->_lf_H.result.is_present;
            }
        }
        
        // ** End initialization for reaction 1 of H
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_2 of H.
        h_main_self[0]->_lf__reaction_2.num_outputs = 0;
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
        }
        
        // ** End initialization for reaction 2 of H
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_3 of H.
        h_main_self[0]->_lf__reaction_3.num_outputs = 0;
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
        }
        
        // ** End initialization for reaction 3 of H
        // **** Start deferred initialize for H.H
        {
        }
        // **** End of deferred initialize for H.H
    }
    // **** End of deferred initialize for H
    // **** Start non-nested deferred initialize for H
    // Set number of destination reactors for port H.result.
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
    }
    // **** Start non-nested deferred initialize for H.H
    // For reference counting, set num_destinations for port H.H.control.
    // Iterate over range H.H.control(0,1)->[H.H.control(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        h_h_self[src_runtime]->_lf_control.num_destinations = 1;
    }
    // **** End of non-nested deferred initialize for H.H
    // **** End of non-nested deferred initialize for H
    // Connect inputs and outputs for reactor H.
    // Connect inputs and outputs for reactor H.H.
    {
    }
    // Add port H.H.result to array of is_present fields.
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            {
                _lf_is_present_fields[0 + count] = &h_main_self[0]->_lf_H.result.is_present;
                #ifdef FEDERATED_DECENTRALIZED
                _lf_intended_tag_fields[0 + count] = &h_main_self[0]->_lf_H.result.intended_tag;
                #endif // FEDERATED_DECENTRALIZED
                count++;
            }
        }
    }
    {
        // Add action H.outputControlReactionTrigger to array of is_present fields.
        _lf_is_present_fields[1] 
                = &h_main_self[0]->_lf_outputControlReactionTrigger.is_present;
        #ifdef FEDERATED_DECENTRALIZED
        // Add action H.outputControlReactionTrigger to array of intended_tag fields.
        _lf_intended_tag_fields[1] 
                = &h_main_self[0]->_lf_outputControlReactionTrigger.intended_tag;
        #endif // FEDERATED_DECENTRALIZED
    }
    {
        // Add action H.inputControlReactionTrigger to array of is_present fields.
        _lf_is_present_fields[2] 
                = &h_main_self[0]->_lf_inputControlReactionTrigger.is_present;
        #ifdef FEDERATED_DECENTRALIZED
        // Add action H.inputControlReactionTrigger to array of intended_tag fields.
        _lf_intended_tag_fields[2] 
                = &h_main_self[0]->_lf_inputControlReactionTrigger.intended_tag;
        #endif // FEDERATED_DECENTRALIZED
    }
    {
        // Add action H.networkMessage to array of is_present fields.
        _lf_is_present_fields[3] 
                = &h_main_self[0]->_lf_networkMessage.is_present;
        #ifdef FEDERATED_DECENTRALIZED
        // Add action H.networkMessage to array of intended_tag fields.
        _lf_intended_tag_fields[3] 
                = &h_main_self[0]->_lf_networkMessage.intended_tag;
        #endif // FEDERATED_DECENTRALIZED
    }
    // Set reaction priorities for ReactorInstance H
    {
        h_main_self[0]->_lf__reaction_0.chain_id = 1;
        // index is the OR of level 0 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        h_main_self[0]->_lf__reaction_0.index = 0xffffffffffff0000LL;
        h_main_self[0]->_lf__reaction_1.chain_id = 1;
        // index is the OR of level 0 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        h_main_self[0]->_lf__reaction_1.index = 0xffffffffffff0000LL;
        h_main_self[0]->_lf__reaction_2.chain_id = 1;
        // index is the OR of level 0 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        h_main_self[0]->_lf__reaction_2.index = 0xffffffffffff0000LL;
        h_main_self[0]->_lf__reaction_3.chain_id = 1;
        // index is the OR of level 0 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        h_main_self[0]->_lf__reaction_3.index = 0xffffffffffff0000LL;
    }
    // Initialize the scheduler
    size_t num_reactions_per_level[1] = 
        {4};
    sched_params_t sched_params = (sched_params_t) {
                            .num_reactions_per_level = &num_reactions_per_level[0],
                            .num_reactions_per_level_size = (size_t) 1};
    lf_sched_init(
        (size_t)_lf_number_of_workers,
        &sched_params
    );
    #ifdef EXECUTABLE_PREAMBLE
    _lf_executable_preamble();
    #endif
    #ifdef FEDERATED
    initialize_triggers_for_federate();
    #endif // FEDERATED
}
void _lf_trigger_startup_reactions() {}
void _lf_initialize_timers() {

}
void logical_tag_complete(tag_t tag_to_send) {
#ifdef FEDERATED_CENTRALIZED
        _lf_logical_tag_complete(tag_to_send);
#endif // FEDERATED_CENTRALIZED

}
bool _lf_trigger_shutdown_reactions() {
    return false;
}
#ifndef FEDERATED
void terminate_execution() {}
#endif
