// Code generated by the Lingua Franca compiler from:
// file://home/plutonh/project/fed-gen/FederatedCount/src/p.lf
#define LOG_LEVEL 2
#define TARGET_FILES_DIRECTORY "/home/plutonh/project/fed-gen/FederatedCount/src-gen/p"
#include "include/api/api.h"
#include "core/reactor.h"
#include "core/reactor_common.h"
#include "core/threaded/scheduler.h"
#include "core/mixed_radix.h"
#include "core/port.h"
int lf_reactor_c_main(int argc, const char* argv[]);
#include "core/federated/federate.h"
#include "core/federated/net_common.h"
#include "include/_p_preamble.h"
int main(int argc, const char* argv[]) {
    return lf_reactor_c_main(argc, argv);
}
const char* _lf_default_argv[] = { "dummy", "-k", "true" };
void _lf_set_default_command_line_options() {
        default_argc = 3;
        default_argv = _lf_default_argv;
}
// =============== START reactor class Print
typedef struct {
    token_type_t type;
    lf_token_t* token;
    size_t length;
    bool is_present;
    lf_sparse_io_record_t* sparse_record;
    int destination_channel;
    int num_destinations;
    int value;
    #ifdef FEDERATED
    #ifdef FEDERATED_DECENTRALIZED
    tag_t intended_tag;
    #endif
    interval_t physical_time_of_arrival;
    #endif
} print_in_t;
typedef struct {
    struct self_base_t base;
    #line 17 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    print_in_t* _lf_in;
    #line 17 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    // width of -2 indicates that it is not a multiport.
    #line 17 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    int _lf_in_width;
    #line 17 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    // Default input (in case it does not get connected)
    #line 17 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    print_in_t _lf_default__in;
    #line 19 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    reaction_t _lf__reaction_0;
    #line 17 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    trigger_t _lf__in;
    #line 17 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    reaction_t* _lf__in_reactions[1];
    #ifdef FEDERATED
    
    #endif // FEDERATED
} print_self_t;
// ***** Start of method declarations.
// ***** End of method declarations.
#include "include/api/set.h"
void printreaction_function_0(void* instance_args) {
    print_self_t* self = (print_self_t*)instance_args; SUPPRESS_UNUSED_WARNING(self);
    print_in_t* in = self->_lf_in;
    int in_width = self->_lf_in_width; SUPPRESS_UNUSED_WARNING(in_width);
    #line 22 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    lf_print("Received: %d at (%lld, %d)", in->value,
        lf_time_logical_elapsed(), lf_tag().microstep
    );
}
#include "include/api/set_undef.h"
print_self_t* new_Print() {
    print_self_t* self = (print_self_t*)_lf_new_reactor(sizeof(print_self_t));
    #line 17 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    // Set input by default to an always absent default input.
    #line 17 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    self->_lf_in = &self->_lf_default__in;
    #line 19 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    self->_lf__reaction_0.number = 0;
    #line 19 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    self->_lf__reaction_0.function = printreaction_function_0;
    #line 19 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    self->_lf__reaction_0.self = self;
    #line 19 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    self->_lf__reaction_0.deadline_violation_handler = NULL;
    #line 19 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    self->_lf__reaction_0.STP_handler = NULL;
    #line 19 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    self->_lf__reaction_0.name = "?";
    #line 19 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    self->_lf__reaction_0.mode = NULL;
    #line 17 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    self->_lf__in.last = NULL;
    #line 17 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    #ifdef FEDERATED_DECENTRALIZED
    #line 17 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    self->_lf__in.intended_tag = (tag_t) { .time = NEVER, .microstep = 0u};
    #line 17 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    #endif // FEDERATED_DECENTRALIZED
    #line 17 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    #line 17 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    self->_lf__in_reactions[0] = &self->_lf__reaction_0;
    #line 17 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    self->_lf__in.reactions = &self->_lf__in_reactions[0];
    #line 17 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    self->_lf__in.number_of_reactions = 1;
    #line 17 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    #ifdef FEDERATED
    #line 17 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    self->_lf__in.physical_time_of_arrival = NEVER;
    #line 17 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    #endif // FEDERATED
    self->_lf__in.tmplt.type.element_size = sizeof(int);
    return self;
}
// =============== END reactor class Print
// =============== START reactor class p
typedef struct {
    token_type_t type;
    lf_token_t* token;
    size_t length;
    bool is_present;
    bool has_value;
    trigger_t* trigger;
    #ifdef FEDERATED
    #ifdef FEDERATED_DECENTRALIZED
    tag_t intended_tag;
    #endif
    interval_t physical_time_of_arrival;
    #endif
} p_inputControlReactionTrigger_t;
typedef struct {
    token_type_t type;
    lf_token_t* token;
    size_t length;
    bool is_present;
    bool has_value;
    trigger_t* trigger;
    int value;
    #ifdef FEDERATED
    #ifdef FEDERATED_DECENTRALIZED
    tag_t intended_tag;
    #endif
    interval_t physical_time_of_arrival;
    #endif
} p_networkMessage_t;
typedef struct {
    struct self_base_t base;
    #line 32 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    p_inputControlReactionTrigger_t _lf_inputControlReactionTrigger;
    #line 33 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    p_networkMessage_t _lf_networkMessage;
    struct {
        #line 17 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
        print_in_t in;
    } _lf_p;
    int _lf_p_width;
    #line 36 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    reaction_t _lf__reaction_0;
    #line 43 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    reaction_t _lf__reaction_1;
    #line 32 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    trigger_t _lf__inputControlReactionTrigger;
    #line 32 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    reaction_t* _lf__inputControlReactionTrigger_reactions[1];
    #line 33 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    trigger_t _lf__networkMessage;
    #line 33 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    reaction_t* _lf__networkMessage_reactions[1];
} p_main_self_t;
// ***** Start of method declarations.
// ***** End of method declarations.
#include "include/api/set.h"
void p_mainreaction_function_0(void* instance_args) {
    p_main_self_t* self = (p_main_self_t*)instance_args; SUPPRESS_UNUSED_WARNING(self);
    struct p {
        print_in_t* in;
    
    } p;
    // Expose the action struct as a local variable whose name matches the action name.
    p_inputControlReactionTrigger_t* inputControlReactionTrigger = &self->_lf_inputControlReactionTrigger;
    // Set the fields of the action struct to match the current trigger.
    inputControlReactionTrigger->is_present = (bool)self->_lf__inputControlReactionTrigger.status;
    inputControlReactionTrigger->has_value = ((self->_lf__inputControlReactionTrigger.tmplt.token) != NULL && (self->_lf__inputControlReactionTrigger.tmplt.token)->value != NULL);
    _lf_replace_template_token((token_template_t*)inputControlReactionTrigger, (self->_lf__inputControlReactionTrigger.tmplt.token));
    p.in = &(self->_lf_p.in);
    #line 38 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    // **** This reaction is unordered.
    interval_t max_STP = 0LL;
    // Wait until the port status is known
    wait_until_port_status_known(0, max_STP);
}
#include "include/api/set_undef.h"
#include "include/api/set.h"
void p_mainreaction_function_1(void* instance_args) {
    p_main_self_t* self = (p_main_self_t*)instance_args; SUPPRESS_UNUSED_WARNING(self);
    struct p {
        print_in_t* in;
    
    } p;
    // Expose the action struct as a local variable whose name matches the action name.
    p_networkMessage_t* networkMessage = &self->_lf_networkMessage;
    // Set the fields of the action struct to match the current trigger.
    networkMessage->is_present = (bool)self->_lf__networkMessage.status;
    networkMessage->has_value = ((self->_lf__networkMessage.tmplt.token) != NULL && (self->_lf__networkMessage.tmplt.token)->value != NULL);
    _lf_replace_template_token((token_template_t*)networkMessage, (self->_lf__networkMessage.tmplt.token));
    if (networkMessage->has_value) {
        networkMessage->value = *(int*)(self->_lf__networkMessage.tmplt.token)->value;
    }
    p.in = &(self->_lf_p.in);
    #line 45 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    // **** This reaction is unordered.
    p.in->physical_time_of_arrival = self->_lf__networkMessage.physical_time_of_arrival;
    lf_set(p.in, networkMessage->value);
}
#include "include/api/set_undef.h"
p_main_self_t* new_p() {
    p_main_self_t* self = (p_main_self_t*)_lf_new_reactor(sizeof(p_main_self_t));
    #line 32 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    self->_lf_inputControlReactionTrigger.trigger = &self->_lf__inputControlReactionTrigger;
    #line 33 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    self->_lf_networkMessage.trigger = &self->_lf__networkMessage;
    // Set the _width variable for all cases. This will be -2
    // if the reactor is not a bank of reactors.
    self->_lf_p_width = -2;
    #line 36 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    self->_lf__reaction_0.number = 0;
    #line 36 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    self->_lf__reaction_0.function = p_mainreaction_function_0;
    #line 36 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    self->_lf__reaction_0.self = self;
    #line 36 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    self->_lf__reaction_0.deadline_violation_handler = NULL;
    #line 36 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    self->_lf__reaction_0.STP_handler = NULL;
    #line 36 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    self->_lf__reaction_0.name = "?";
    #line 36 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    self->_lf__reaction_0.mode = NULL;
    #line 43 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    self->_lf__reaction_1.number = 1;
    #line 43 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    self->_lf__reaction_1.function = p_mainreaction_function_1;
    #line 43 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    self->_lf__reaction_1.self = self;
    #line 43 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    self->_lf__reaction_1.deadline_violation_handler = NULL;
    #line 43 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    self->_lf__reaction_1.STP_handler = NULL;
    #line 43 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    self->_lf__reaction_1.name = "?";
    #line 43 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    self->_lf__reaction_1.mode = NULL;
    #line 32 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    self->_lf__inputControlReactionTrigger.last = NULL;
    #line 32 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    #ifdef FEDERATED_DECENTRALIZED
    #line 32 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    self->_lf__inputControlReactionTrigger.intended_tag = (tag_t) { .time = NEVER, .microstep = 0u};
    #line 32 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    #endif // FEDERATED_DECENTRALIZED
    #line 32 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    #line 32 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    self->_lf__inputControlReactionTrigger_reactions[0] = &self->_lf__reaction_0;
    #line 32 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    self->_lf__inputControlReactionTrigger.reactions = &self->_lf__inputControlReactionTrigger_reactions[0];
    #line 32 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    self->_lf__inputControlReactionTrigger.number_of_reactions = 1;
    #line 32 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    #ifdef FEDERATED
    #line 32 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    self->_lf__inputControlReactionTrigger.physical_time_of_arrival = NEVER;
    #line 32 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    #endif // FEDERATED
    self->_lf__inputControlReactionTrigger.is_physical = false;
    
    self->_lf__inputControlReactionTrigger.tmplt.type.element_size = 0;
    self->_lf_inputControlReactionTrigger.type.element_size = 0;
    #line 33 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    self->_lf__networkMessage.last = NULL;
    #line 33 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    #ifdef FEDERATED_DECENTRALIZED
    #line 33 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    self->_lf__networkMessage.intended_tag = (tag_t) { .time = NEVER, .microstep = 0u};
    #line 33 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    #endif // FEDERATED_DECENTRALIZED
    #line 33 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    #line 33 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    self->_lf__networkMessage_reactions[0] = &self->_lf__reaction_1;
    #line 33 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    self->_lf__networkMessage.reactions = &self->_lf__networkMessage_reactions[0];
    #line 33 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    self->_lf__networkMessage.number_of_reactions = 1;
    #line 33 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    #ifdef FEDERATED
    #line 33 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    self->_lf__networkMessage.physical_time_of_arrival = NEVER;
    #line 33 "/home/plutonh/project/fed-gen/FederatedCount/src/p.lf"
    #endif // FEDERATED
    self->_lf__networkMessage.is_physical = false;
    
    self->_lf__networkMessage.tmplt.type.element_size = sizeof(int);
    self->_lf_networkMessage.type.element_size = sizeof(int);
    return self;
}
// =============== END reactor class p
// Array of pointers to timer triggers to be scheduled in _lf_initialize_timers().
trigger_t** _lf_timer_triggers = NULL;
int _lf_timer_triggers_size = 0;
// Array of pointers to startup triggers.
reaction_t** _lf_startup_reactions = NULL;
int _lf_startup_reactions_size = 0;
// Array of pointers to shutdown triggers.
reaction_t** _lf_shutdown_reactions = NULL;
int _lf_shutdown_reactions_size = 0;
// Array of pointers to reset triggers.
reaction_t** _lf_reset_reactions = NULL;
int _lf_reset_reactions_size = 0;
void _lf_initialize_trigger_objects() {
    // Initialize the _lf_clock
    lf_initialize_clock();
    // Create the array that will contain pointers to is_present fields to reset on each step.
    _lf_is_present_fields_size = 3;
    _lf_is_present_fields = (bool**)calloc(3, sizeof(bool*));
    if (_lf_is_present_fields == NULL) lf_print_error_and_exit("Out of memory!");
    _lf_is_present_fields_abbreviated = (bool**)calloc(3, sizeof(bool*));
    if (_lf_is_present_fields_abbreviated == NULL) lf_print_error_and_exit("Out of memory!");
    _lf_is_present_fields_abbreviated_size = 0;
    #ifdef FEDERATED_DECENTRALIZED
    // Create the array that will contain pointers to intended_tag fields to reset on each step.
    _lf_intended_tag_fields_size = 3;
    _lf_intended_tag_fields = (tag_t**)malloc(_lf_intended_tag_fields_size * sizeof(tag_t*));
    
    #endif // FEDERATED_DECENTRALIZED
    int _lf_startup_reactions_count = 0;
    SUPPRESS_UNUSED_WARNING(_lf_startup_reactions_count);
    int _lf_shutdown_reactions_count = 0;
    SUPPRESS_UNUSED_WARNING(_lf_shutdown_reactions_count);
    int _lf_reset_reactions_count = 0;
    SUPPRESS_UNUSED_WARNING(_lf_reset_reactions_count);
    int _lf_timer_triggers_count = 0;
    SUPPRESS_UNUSED_WARNING(_lf_timer_triggers_count);
    int bank_index;
    SUPPRESS_UNUSED_WARNING(bank_index);
    p_main_self_t* p_main_self[1];
    SUPPRESS_UNUSED_WARNING(p_main_self);
    print_self_t* p_p_self[1];
    SUPPRESS_UNUSED_WARNING(p_p_self);
    // ***** Start initializing p of class p
    p_main_self[0] = new_p();
    bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
    // Initializing action p.inputControlReactionTrigger
    p_main_self[0]->_lf__inputControlReactionTrigger.offset = 0;
    p_main_self[0]->_lf__inputControlReactionTrigger.period = -1;
    p_main_self[0]->_lf__inputControlReactionTrigger.mode = NULL;
    // Initializing action p.networkMessage
    p_main_self[0]->_lf__networkMessage.offset = 0;
    p_main_self[0]->_lf__networkMessage.period = -1;
    p_main_self[0]->_lf__networkMessage.mode = NULL;
    _lf_initialize_template((token_template_t*)
            &(p_main_self[0]->_lf__inputControlReactionTrigger),
    0);
    p_main_self[0]->_lf__inputControlReactionTrigger.status = absent;
    _lf_initialize_template((token_template_t*)
            &(p_main_self[0]->_lf__networkMessage),
    sizeof(int));
    p_main_self[0]->_lf__networkMessage.status = absent;
    p_main_self[0]->_lf__reaction_0.deadline = NEVER;
    p_main_self[0]->_lf__reaction_1.deadline = NEVER;
    {
        // ***** Start initializing p.p of class Print
        p_p_self[0] = new_Print();
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        // width of -2 indicates that it is not a multiport.
        p_p_self[0]->_lf_in_width = -2;
        p_p_self[0]->_lf__reaction_0.deadline = NEVER;
        //***** End initializing p.p
    }
    //***** End initializing p
    // **** Start deferred initialize for p
    {
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_0 of p.
        p_main_self[0]->_lf__reaction_0.num_outputs = 1;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        p_main_self[0]->_lf__reaction_0.triggers = (trigger_t***)_lf_allocate(
                1, sizeof(trigger_t**),
                &p_main_self[0]->base.allocations);
        p_main_self[0]->_lf__reaction_0.triggered_sizes = (int*)_lf_allocate(
                1, sizeof(int),
                &p_main_self[0]->base.allocations);
        p_main_self[0]->_lf__reaction_0.output_produced = (bool**)_lf_allocate(
                1, sizeof(bool*),
                &p_main_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                p_main_self[0]->_lf__reaction_0.output_produced[count++] = &p_main_self[0]->_lf_p.in.is_present;
            }
        }
        
        // ** End initialization for reaction 0 of p
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_1 of p.
        p_main_self[0]->_lf__reaction_1.num_outputs = 1;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        p_main_self[0]->_lf__reaction_1.triggers = (trigger_t***)_lf_allocate(
                1, sizeof(trigger_t**),
                &p_main_self[0]->base.allocations);
        p_main_self[0]->_lf__reaction_1.triggered_sizes = (int*)_lf_allocate(
                1, sizeof(int),
                &p_main_self[0]->base.allocations);
        p_main_self[0]->_lf__reaction_1.output_produced = (bool**)_lf_allocate(
                1, sizeof(bool*),
                &p_main_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                p_main_self[0]->_lf__reaction_1.output_produced[count++] = &p_main_self[0]->_lf_p.in.is_present;
            }
        }
        
        // ** End initialization for reaction 1 of p
        // **** Start deferred initialize for p.p
        {
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_0 of p.p.
            p_p_self[0]->_lf__reaction_0.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 0 of p.p
        }
        // **** End of deferred initialize for p.p
    }
    // **** End of deferred initialize for p
    // **** Start non-nested deferred initialize for p
    // Set number of destination reactors for port p.in.
    // Iterate over range p.p.in(0,1)->[p.p.in(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        p_main_self[src_runtime]->_lf_p.in.num_destinations = 1;
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range p.p.in(0,1)->[p.p.in(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 0 of p triggers 1 downstream reactions
            // through port p.p.in.
            p_main_self[src_runtime]->_lf__reaction_0.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 0 of p, allocate an
            // array of trigger pointers for downstream reactions through port p.p.in
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &p_main_self[src_runtime]->base.allocations); 
            p_main_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges p.p.in(0,1)->[p.p.in(0,1)] and p.p.in(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range p.p.in(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port p.p.in's trigger struct.
                p_main_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime] + src_channel][0] = &p_p_self[dst_runtime]->_lf__in;
            }
        }
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range p.p.in(0,1)->[p.p.in(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 1 of p triggers 1 downstream reactions
            // through port p.p.in.
            p_main_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 1 of p, allocate an
            // array of trigger pointers for downstream reactions through port p.p.in
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &p_main_self[src_runtime]->base.allocations); 
            p_main_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges p.p.in(0,1)->[p.p.in(0,1)] and p.p.in(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range p.p.in(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port p.p.in's trigger struct.
                p_main_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &p_p_self[dst_runtime]->_lf__in;
            }
        }
    }
    // **** Start non-nested deferred initialize for p.p
    // **** End of non-nested deferred initialize for p.p
    // **** End of non-nested deferred initialize for p
    // Connect inputs and outputs for reactor p.
    // Connect inputs and outputs for reactor p.p.
    // Connect p.p.in(0,1)->[p.p.in(0,1)] to port p.p.in(0,1)
    // Iterate over ranges p.p.in(0,1)->[p.p.in(0,1)] and p.p.in(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range p.p.in(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            p_p_self[dst_runtime]->_lf_in = (print_in_t*)&p_main_self[src_runtime]->_lf_p.in;
        }
    }
    {
    }
    // Add port p.p.in to array of is_present fields.
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            {
                _lf_is_present_fields[0 + count] = &p_main_self[0]->_lf_p.in.is_present;
                #ifdef FEDERATED_DECENTRALIZED
                _lf_intended_tag_fields[0 + count] = &p_main_self[0]->_lf_p.in.intended_tag;
                #endif // FEDERATED_DECENTRALIZED
                count++;
            }
        }
    }
    {
        // Add action p.inputControlReactionTrigger to array of is_present fields.
        _lf_is_present_fields[1] 
                = &p_main_self[0]->_lf_inputControlReactionTrigger.is_present;
        #ifdef FEDERATED_DECENTRALIZED
        // Add action p.inputControlReactionTrigger to array of intended_tag fields.
        _lf_intended_tag_fields[1] 
                = &p_main_self[0]->_lf_inputControlReactionTrigger.intended_tag;
        #endif // FEDERATED_DECENTRALIZED
    }
    {
        // Add action p.networkMessage to array of is_present fields.
        _lf_is_present_fields[2] 
                = &p_main_self[0]->_lf_networkMessage.is_present;
        #ifdef FEDERATED_DECENTRALIZED
        // Add action p.networkMessage to array of intended_tag fields.
        _lf_intended_tag_fields[2] 
                = &p_main_self[0]->_lf_networkMessage.intended_tag;
        #endif // FEDERATED_DECENTRALIZED
    }
    // Set reaction priorities for ReactorInstance p
    {
        p_main_self[0]->_lf__reaction_0.chain_id = 1;
        // index is the OR of level 0 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        p_main_self[0]->_lf__reaction_0.index = 0xffffffffffff0000LL;
        p_main_self[0]->_lf__reaction_1.chain_id = 1;
        // index is the OR of level 0 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        p_main_self[0]->_lf__reaction_1.index = 0xffffffffffff0000LL;
        // Set reaction priorities for ReactorInstance p.p
        {
            p_p_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 1 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            p_p_self[0]->_lf__reaction_0.index = 0xffffffffffff0001LL;
        }
    }
    // Initialize the scheduler
    size_t num_reactions_per_level[2] = 
        {2, 1};
    sched_params_t sched_params = (sched_params_t) {
                            .num_reactions_per_level = &num_reactions_per_level[0],
                            .num_reactions_per_level_size = (size_t) 2};
    lf_sched_init(
        (size_t)_lf_number_of_workers,
        &sched_params
    );
    #ifdef EXECUTABLE_PREAMBLE
    _lf_executable_preamble();
    #endif
    #ifdef FEDERATED
    initialize_triggers_for_federate();
    #endif // FEDERATED
}
void _lf_trigger_startup_reactions() {}
void _lf_initialize_timers() {

}
void logical_tag_complete(tag_t tag_to_send) {
#ifdef FEDERATED_CENTRALIZED
        _lf_logical_tag_complete(tag_to_send);
#endif // FEDERATED_CENTRALIZED

}
bool _lf_trigger_shutdown_reactions() {
    return false;
}
#ifndef FEDERATED
void terminate_execution() {}
#endif
