// Code generated by the Lingua Franca compiler from:
// file://home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf
#define LOG_LEVEL 2
#define TARGET_FILES_DIRECTORY "/home/plutonh/project/fed-gen/Federated_Airplane/src-gen/D"
#include "include/api/api.h"
#include "core/reactor.h"
#include "core/reactor_common.h"
#include "core/threaded/scheduler.h"
#include "core/mixed_radix.h"
#include "core/port.h"
int lf_reactor_c_main(int argc, const char* argv[]);
#include "core/federated/federate.h"
#include "core/federated/net_common.h"
#include "include/_D_preamble.h"
#include <stdio.h>
struct {
    void* open;
    void* close;
    void* ready;
    void* not;
} buttons;

void* read_input_1(void* arg) { // keyboard input funciton for Cockpit reactor
    printf("***************************************************************\n");
    printf("Press 'o' and hit return or enter to open the door\n");
    printf("Press 'c' and hit return or enter to close the door\n");
    printf("Press 'Control-d' to exit\n");
    while(1) {
        int c = getchar();
        if (c == 'o') {
            lf_schedule(buttons.open, 0);
        }
        if (c == 'c') {
            lf_schedule(buttons.close, 0);
        }
        if (c == EOF) {
            break;
        }
    }
    lf_request_stop();
    return NULL;
}

void* read_input_2(void* arg) { // keyboard input funciton for VisionMonitor reactor
    printf("***************************************************************\n");
    printf("Press 'r' and hit return or enter to open the ramp\n");
    printf("Press 'n' and hit return or enter to close the ramp\n");
    printf("Press 'Control-d' to exit\n");
    while(1) {
        int c = getchar();
        if (c == 'r') {
            lf_schedule(buttons.ready, 0);
        }
        if (c == 'n') {
            lf_schedule(buttons.not, 0);
        }
        if (c == EOF) {
            break;
        }
    }
    lf_request_stop();
    return NULL;
}
int main(int argc, const char* argv[]) {
    return lf_reactor_c_main(argc, argv);
}
const char* _lf_default_argv[] = { "dummy", "-k", "true" };
void _lf_set_default_command_line_options() {
        default_argc = 3;
        default_argv = _lf_default_argv;
}
// =============== START reactor class Door
typedef struct {
    token_type_t type;
    lf_token_t* token;
    size_t length;
    bool is_present;
    lf_sparse_io_record_t* sparse_record;
    int destination_channel;
    int num_destinations;
    bool value;
    #ifdef FEDERATED
    #ifdef FEDERATED_DECENTRALIZED
    tag_t intended_tag;
    #endif
    interval_t physical_time_of_arrival;
    #endif
} door_open_t;
typedef struct {
    token_type_t type;
    lf_token_t* token;
    size_t length;
    bool is_present;
    lf_sparse_io_record_t* sparse_record;
    int destination_channel;
    int num_destinations;
    bool value;
    #ifdef FEDERATED
    #ifdef FEDERATED_DECENTRALIZED
    tag_t intended_tag;
    #endif
    interval_t physical_time_of_arrival;
    #endif
} door_disarm_t;
typedef struct {
    struct self_base_t base;
    #line 72 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    bool door_opened;
    #line 74 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    bool door_closed;
    #line 76 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    bool ramp_opened;
    #line 78 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    bool ramp_closed;
    #line 81 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    interval_t timestamp;
    #line 68 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    door_open_t* _lf_open;
    #line 68 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    // width of -2 indicates that it is not a multiport.
    #line 68 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    int _lf_open_width;
    #line 68 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    // Default input (in case it does not get connected)
    #line 68 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    door_open_t _lf_default__open;
    #line 69 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    door_disarm_t* _lf_disarm;
    #line 69 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    // width of -2 indicates that it is not a multiport.
    #line 69 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    int _lf_disarm_width;
    #line 69 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    // Default input (in case it does not get connected)
    #line 69 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    door_disarm_t _lf_default__disarm;
    #line 83 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    reaction_t _lf__reaction_0;
    #line 129 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    reaction_t _lf__reaction_1;
    #line 68 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    trigger_t _lf__open;
    #line 68 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    reaction_t* _lf__open_reactions[1];
    #ifdef FEDERATED
    
    #endif // FEDERATED
    #line 69 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    trigger_t _lf__disarm;
    #line 69 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    reaction_t* _lf__disarm_reactions[1];
    #ifdef FEDERATED
    
    #endif // FEDERATED
} door_self_t;
// ***** Start of method declarations.
// ***** End of method declarations.
#include "include/api/set.h"
void doorreaction_function_0(void* instance_args) {
    door_self_t* self = (door_self_t*)instance_args; SUPPRESS_UNUSED_WARNING(self);
    door_open_t* open = self->_lf_open;
    int open_width = self->_lf_open_width; SUPPRESS_UNUSED_WARNING(open_width);
    #line 86 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    // If the time at which the currently entered open action occurred
    // is less than 2 seconds after subtracting the stored variable from
    // the time at which the previously entered open action occurred,
    // an emergency situation is executed.
    if(open->value && (lf_time_logical_elapsed() - self->timestamp) < SECS(2)) {
        printf("%ld nsec: Emergency Open!!\n", lf_time_logical_elapsed());
        self->door_opened = true;
        self->door_closed = false;
    }
    
    // Conditions to determine if a door is already open
    else if(open->value && self->door_opened) {
        printf("%ld nsec: Door already open\n", lf_time_logical_elapsed());
    }
    
    // Conditions for checking the situation to open the door
    else if(open->value && self->door_opened == false && self->ramp_opened) {
        printf("%ld nsec: Opening Door\n", lf_time_logical_elapsed());
        self->door_opened = true;
        self->door_closed = false;
    }
    
    // Conditions to determine if the ramp is detected before opening the door
    else if(open->value && self->door_opened == false && self->ramp_closed) {
        printf("%ld nsec: No ramp detected\n", lf_time_logical_elapsed());
    }
    
    // Conditions to determine if the door is already closed
    else if(open->value == false && self->door_closed) {
        printf("%ld nsec: Door already close\n", lf_time_logical_elapsed());
    }
    
    // Conditions to check the situation to close the door
    else {
        printf("%ld nsec: Closing Door\n", lf_time_logical_elapsed());
        self->door_closed = true;
        self->door_opened = false;
    }
    
    // Save the time when an action occurred through the first 'o'
    self->timestamp = lf_time_logical_elapsed();
}
#include "include/api/set_undef.h"
#include "include/api/set.h"
void doorreaction_function_1(void* instance_args) {
    door_self_t* self = (door_self_t*)instance_args; SUPPRESS_UNUSED_WARNING(self);
    door_disarm_t* disarm = self->_lf_disarm;
    int disarm_width = self->_lf_disarm_width; SUPPRESS_UNUSED_WARNING(disarm_width);
    #line 132 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    if(disarm->value) {
        printf("%ld nsec: Ramp ready: true\n", lf_time_logical_elapsed());
        self->ramp_opened = true;
        self->ramp_closed = false;
    }
    else {
        printf("%ld nsec: Ramp ready: false\n", lf_time_logical_elapsed());
        self->ramp_closed = true;
        self->ramp_opened = false;
    }
}
#include "include/api/set_undef.h"
door_self_t* new_Door() {
    door_self_t* self = (door_self_t*)_lf_new_reactor(sizeof(door_self_t));
    #line 68 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    // Set input by default to an always absent default input.
    #line 68 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    self->_lf_open = &self->_lf_default__open;
    #line 69 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    // Set input by default to an always absent default input.
    #line 69 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    self->_lf_disarm = &self->_lf_default__disarm;
    #line 83 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    self->_lf__reaction_0.number = 0;
    #line 83 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    self->_lf__reaction_0.function = doorreaction_function_0;
    #line 83 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    self->_lf__reaction_0.self = self;
    #line 83 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    self->_lf__reaction_0.deadline_violation_handler = NULL;
    #line 83 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    self->_lf__reaction_0.STP_handler = NULL;
    #line 83 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    self->_lf__reaction_0.name = "?";
    #line 83 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    self->_lf__reaction_0.mode = NULL;
    #line 129 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    self->_lf__reaction_1.number = 1;
    #line 129 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    self->_lf__reaction_1.function = doorreaction_function_1;
    #line 129 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    self->_lf__reaction_1.self = self;
    #line 129 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    self->_lf__reaction_1.deadline_violation_handler = NULL;
    #line 129 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    self->_lf__reaction_1.STP_handler = NULL;
    #line 129 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    self->_lf__reaction_1.name = "?";
    #line 129 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    self->_lf__reaction_1.mode = NULL;
    #line 68 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    self->_lf__open.last = NULL;
    #line 68 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    #ifdef FEDERATED_DECENTRALIZED
    #line 68 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    self->_lf__open.intended_tag = (tag_t) { .time = NEVER, .microstep = 0u};
    #line 68 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    #endif // FEDERATED_DECENTRALIZED
    #line 68 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    #line 68 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    self->_lf__open_reactions[0] = &self->_lf__reaction_0;
    #line 68 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    self->_lf__open.reactions = &self->_lf__open_reactions[0];
    #line 68 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    self->_lf__open.number_of_reactions = 1;
    #line 68 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    #ifdef FEDERATED
    #line 68 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    self->_lf__open.physical_time_of_arrival = NEVER;
    #line 68 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    #endif // FEDERATED
    self->_lf__open.tmplt.type.element_size = sizeof(bool);
    #line 69 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    self->_lf__disarm.last = NULL;
    #line 69 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    #ifdef FEDERATED_DECENTRALIZED
    #line 69 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    self->_lf__disarm.intended_tag = (tag_t) { .time = NEVER, .microstep = 0u};
    #line 69 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    #endif // FEDERATED_DECENTRALIZED
    #line 69 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    #line 69 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    self->_lf__disarm_reactions[0] = &self->_lf__reaction_1;
    #line 69 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    self->_lf__disarm.reactions = &self->_lf__disarm_reactions[0];
    #line 69 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    self->_lf__disarm.number_of_reactions = 1;
    #line 69 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    #ifdef FEDERATED
    #line 69 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    self->_lf__disarm.physical_time_of_arrival = NEVER;
    #line 69 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    #endif // FEDERATED
    self->_lf__disarm.tmplt.type.element_size = sizeof(bool);
    return self;
}
// =============== END reactor class Door
// =============== START reactor class D
typedef struct {
    token_type_t type;
    lf_token_t* token;
    size_t length;
    bool is_present;
    bool has_value;
    trigger_t* trigger;
    bool value;
    #ifdef FEDERATED
    #ifdef FEDERATED_DECENTRALIZED
    tag_t intended_tag;
    #endif
    interval_t physical_time_of_arrival;
    #endif
} d_networkMessage_t;
typedef struct {
    token_type_t type;
    lf_token_t* token;
    size_t length;
    bool is_present;
    bool has_value;
    trigger_t* trigger;
    bool value;
    #ifdef FEDERATED
    #ifdef FEDERATED_DECENTRALIZED
    tag_t intended_tag;
    #endif
    interval_t physical_time_of_arrival;
    #endif
} d_networkMessage_0_t;
typedef struct {
    struct self_base_t base;
    #line 149 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    d_networkMessage_t _lf_networkMessage;
    #line 150 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    d_networkMessage_0_t _lf_networkMessage_0;
    struct {
        #line 68 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
        door_open_t open;
        #line 69 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
        door_disarm_t disarm;
    } _lf_D;
    int _lf_D_width;
    #line 153 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    reaction_t _lf__reaction_0;
    #line 159 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    reaction_t _lf__reaction_1;
    #line 149 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    trigger_t _lf__networkMessage;
    #line 149 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    reaction_t* _lf__networkMessage_reactions[1];
    #line 150 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    trigger_t _lf__networkMessage_0;
    #line 150 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    reaction_t* _lf__networkMessage_0_reactions[1];
} d_main_self_t;
// ***** Start of method declarations.
// ***** End of method declarations.
#include "include/api/set.h"
void d_mainreaction_function_0(void* instance_args) {
    d_main_self_t* self = (d_main_self_t*)instance_args; SUPPRESS_UNUSED_WARNING(self);
    struct D {
        door_open_t* open;
    
    } D;
    // Expose the action struct as a local variable whose name matches the action name.
    d_networkMessage_t* networkMessage = &self->_lf_networkMessage;
    // Set the fields of the action struct to match the current trigger.
    networkMessage->is_present = (bool)self->_lf__networkMessage.status;
    networkMessage->has_value = ((self->_lf__networkMessage.tmplt.token) != NULL && (self->_lf__networkMessage.tmplt.token)->value != NULL);
    _lf_replace_template_token((token_template_t*)networkMessage, (self->_lf__networkMessage.tmplt.token));
    if (networkMessage->has_value) {
        networkMessage->value = *(bool*)(self->_lf__networkMessage.tmplt.token)->value;
    }
    D.open = &(self->_lf_D.open);
    #line 155 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    // **** This reaction is unordered.
    D.open->physical_time_of_arrival = self->_lf__networkMessage.physical_time_of_arrival;
    lf_set(D.open, networkMessage->value);
}
#include "include/api/set_undef.h"
#include "include/api/set.h"
void d_mainreaction_function_1(void* instance_args) {
    d_main_self_t* self = (d_main_self_t*)instance_args; SUPPRESS_UNUSED_WARNING(self);
    struct D {
        door_disarm_t* disarm;
    
    } D;
    // Expose the action struct as a local variable whose name matches the action name.
    d_networkMessage_0_t* networkMessage_0 = &self->_lf_networkMessage_0;
    // Set the fields of the action struct to match the current trigger.
    networkMessage_0->is_present = (bool)self->_lf__networkMessage_0.status;
    networkMessage_0->has_value = ((self->_lf__networkMessage_0.tmplt.token) != NULL && (self->_lf__networkMessage_0.tmplt.token)->value != NULL);
    _lf_replace_template_token((token_template_t*)networkMessage_0, (self->_lf__networkMessage_0.tmplt.token));
    if (networkMessage_0->has_value) {
        networkMessage_0->value = *(bool*)(self->_lf__networkMessage_0.tmplt.token)->value;
    }
    D.disarm = &(self->_lf_D.disarm);
    #line 161 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    // **** This reaction is unordered.
    D.disarm->physical_time_of_arrival = self->_lf__networkMessage_0.physical_time_of_arrival;
    lf_set(D.disarm, networkMessage_0->value);
}
#include "include/api/set_undef.h"
d_main_self_t* new_D() {
    d_main_self_t* self = (d_main_self_t*)_lf_new_reactor(sizeof(d_main_self_t));
    #line 149 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    self->_lf_networkMessage.trigger = &self->_lf__networkMessage;
    #line 150 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    self->_lf_networkMessage_0.trigger = &self->_lf__networkMessage_0;
    // Set the _width variable for all cases. This will be -2
    // if the reactor is not a bank of reactors.
    self->_lf_D_width = -2;
    #line 153 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    self->_lf__reaction_0.number = 0;
    #line 153 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    self->_lf__reaction_0.function = d_mainreaction_function_0;
    #line 153 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    self->_lf__reaction_0.self = self;
    #line 153 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    self->_lf__reaction_0.deadline_violation_handler = NULL;
    #line 153 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    self->_lf__reaction_0.STP_handler = NULL;
    #line 153 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    self->_lf__reaction_0.name = "?";
    #line 153 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    self->_lf__reaction_0.mode = NULL;
    #line 159 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    self->_lf__reaction_1.number = 1;
    #line 159 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    self->_lf__reaction_1.function = d_mainreaction_function_1;
    #line 159 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    self->_lf__reaction_1.self = self;
    #line 159 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    self->_lf__reaction_1.deadline_violation_handler = NULL;
    #line 159 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    self->_lf__reaction_1.STP_handler = NULL;
    #line 159 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    self->_lf__reaction_1.name = "?";
    #line 159 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    self->_lf__reaction_1.mode = NULL;
    #line 149 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    self->_lf__networkMessage.last = NULL;
    #line 149 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    #ifdef FEDERATED_DECENTRALIZED
    #line 149 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    self->_lf__networkMessage.intended_tag = (tag_t) { .time = NEVER, .microstep = 0u};
    #line 149 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    #endif // FEDERATED_DECENTRALIZED
    #line 149 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    #line 149 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    self->_lf__networkMessage_reactions[0] = &self->_lf__reaction_0;
    #line 149 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    self->_lf__networkMessage.reactions = &self->_lf__networkMessage_reactions[0];
    #line 149 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    self->_lf__networkMessage.number_of_reactions = 1;
    #line 149 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    #ifdef FEDERATED
    #line 149 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    self->_lf__networkMessage.physical_time_of_arrival = NEVER;
    #line 149 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    #endif // FEDERATED
    self->_lf__networkMessage.is_physical = true;
    
    self->_lf__networkMessage.tmplt.type.element_size = sizeof(bool);
    self->_lf_networkMessage.type.element_size = sizeof(bool);
    #line 150 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    self->_lf__networkMessage_0.last = NULL;
    #line 150 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    #ifdef FEDERATED_DECENTRALIZED
    #line 150 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    self->_lf__networkMessage_0.intended_tag = (tag_t) { .time = NEVER, .microstep = 0u};
    #line 150 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    #endif // FEDERATED_DECENTRALIZED
    #line 150 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    #line 150 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    self->_lf__networkMessage_0_reactions[0] = &self->_lf__reaction_1;
    #line 150 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    self->_lf__networkMessage_0.reactions = &self->_lf__networkMessage_0_reactions[0];
    #line 150 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    self->_lf__networkMessage_0.number_of_reactions = 1;
    #line 150 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    #ifdef FEDERATED
    #line 150 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    self->_lf__networkMessage_0.physical_time_of_arrival = NEVER;
    #line 150 "/home/plutonh/project/fed-gen/Federated_Airplane/src/D.lf"
    #endif // FEDERATED
    self->_lf__networkMessage_0.is_physical = true;
    
    self->_lf__networkMessage_0.tmplt.type.element_size = sizeof(bool);
    self->_lf_networkMessage_0.type.element_size = sizeof(bool);
    return self;
}
// =============== END reactor class D
// Array of pointers to timer triggers to be scheduled in _lf_initialize_timers().
trigger_t** _lf_timer_triggers = NULL;
int _lf_timer_triggers_size = 0;
// Array of pointers to startup triggers.
reaction_t** _lf_startup_reactions = NULL;
int _lf_startup_reactions_size = 0;
// Array of pointers to shutdown triggers.
reaction_t** _lf_shutdown_reactions = NULL;
int _lf_shutdown_reactions_size = 0;
// Array of pointers to reset triggers.
reaction_t** _lf_reset_reactions = NULL;
int _lf_reset_reactions_size = 0;
void _lf_initialize_trigger_objects() {
    // Initialize the _lf_clock
    lf_initialize_clock();
    // Create the array that will contain pointers to is_present fields to reset on each step.
    _lf_is_present_fields_size = 4;
    _lf_is_present_fields = (bool**)calloc(4, sizeof(bool*));
    if (_lf_is_present_fields == NULL) lf_print_error_and_exit("Out of memory!");
    _lf_is_present_fields_abbreviated = (bool**)calloc(4, sizeof(bool*));
    if (_lf_is_present_fields_abbreviated == NULL) lf_print_error_and_exit("Out of memory!");
    _lf_is_present_fields_abbreviated_size = 0;
    #ifdef FEDERATED_DECENTRALIZED
    // Create the array that will contain pointers to intended_tag fields to reset on each step.
    _lf_intended_tag_fields_size = 4;
    _lf_intended_tag_fields = (tag_t**)malloc(_lf_intended_tag_fields_size * sizeof(tag_t*));
    
    #endif // FEDERATED_DECENTRALIZED
    int _lf_startup_reactions_count = 0;
    SUPPRESS_UNUSED_WARNING(_lf_startup_reactions_count);
    int _lf_shutdown_reactions_count = 0;
    SUPPRESS_UNUSED_WARNING(_lf_shutdown_reactions_count);
    int _lf_reset_reactions_count = 0;
    SUPPRESS_UNUSED_WARNING(_lf_reset_reactions_count);
    int _lf_timer_triggers_count = 0;
    SUPPRESS_UNUSED_WARNING(_lf_timer_triggers_count);
    int bank_index;
    SUPPRESS_UNUSED_WARNING(bank_index);
    d_main_self_t* d_main_self[1];
    SUPPRESS_UNUSED_WARNING(d_main_self);
    door_self_t* d_d_self[1];
    SUPPRESS_UNUSED_WARNING(d_d_self);
    // ***** Start initializing D of class D
    d_main_self[0] = new_D();
    bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
    // Initializing action D.networkMessage
    d_main_self[0]->_lf__networkMessage.offset = 0;
    d_main_self[0]->_lf__networkMessage.period = -1;
    d_main_self[0]->_lf__networkMessage.mode = NULL;
    // Initializing action D.networkMessage_0
    d_main_self[0]->_lf__networkMessage_0.offset = 0;
    d_main_self[0]->_lf__networkMessage_0.period = -1;
    d_main_self[0]->_lf__networkMessage_0.mode = NULL;
    _lf_initialize_template((token_template_t*)
            &(d_main_self[0]->_lf__networkMessage),
    sizeof(bool));
    d_main_self[0]->_lf__networkMessage.status = absent;
    _lf_initialize_template((token_template_t*)
            &(d_main_self[0]->_lf__networkMessage_0),
    sizeof(bool));
    d_main_self[0]->_lf__networkMessage_0.status = absent;
    d_main_self[0]->_lf__reaction_0.deadline = NEVER;
    d_main_self[0]->_lf__reaction_1.deadline = NEVER;
    {
        // ***** Start initializing D.D of class Door
        d_d_self[0] = new_Door();
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        // width of -2 indicates that it is not a multiport.
        d_d_self[0]->_lf_open_width = -2;
        // width of -2 indicates that it is not a multiport.
        d_d_self[0]->_lf_disarm_width = -2;
        { // For scoping
            static bool _initial = false;
            d_d_self[0]->door_opened = _initial;
        } // End scoping.
        { // For scoping
            static bool _initial = true;
            d_d_self[0]->door_closed = _initial;
        } // End scoping.
        { // For scoping
            static bool _initial = false;
            d_d_self[0]->ramp_opened = _initial;
        } // End scoping.
        { // For scoping
            static bool _initial = true;
            d_d_self[0]->ramp_closed = _initial;
        } // End scoping.
        d_d_self[0]->timestamp = 0;
        d_d_self[0]->_lf__reaction_0.deadline = NEVER;
        d_d_self[0]->_lf__reaction_1.deadline = NEVER;
        //***** End initializing D.D
    }
    //***** End initializing D
    // **** Start deferred initialize for D
    {
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_0 of D.
        d_main_self[0]->_lf__reaction_0.num_outputs = 1;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        d_main_self[0]->_lf__reaction_0.triggers = (trigger_t***)_lf_allocate(
                1, sizeof(trigger_t**),
                &d_main_self[0]->base.allocations);
        d_main_self[0]->_lf__reaction_0.triggered_sizes = (int*)_lf_allocate(
                1, sizeof(int),
                &d_main_self[0]->base.allocations);
        d_main_self[0]->_lf__reaction_0.output_produced = (bool**)_lf_allocate(
                1, sizeof(bool*),
                &d_main_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                d_main_self[0]->_lf__reaction_0.output_produced[count++] = &d_main_self[0]->_lf_D.open.is_present;
            }
        }
        
        // ** End initialization for reaction 0 of D
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_1 of D.
        d_main_self[0]->_lf__reaction_1.num_outputs = 1;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        d_main_self[0]->_lf__reaction_1.triggers = (trigger_t***)_lf_allocate(
                1, sizeof(trigger_t**),
                &d_main_self[0]->base.allocations);
        d_main_self[0]->_lf__reaction_1.triggered_sizes = (int*)_lf_allocate(
                1, sizeof(int),
                &d_main_self[0]->base.allocations);
        d_main_self[0]->_lf__reaction_1.output_produced = (bool**)_lf_allocate(
                1, sizeof(bool*),
                &d_main_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                d_main_self[0]->_lf__reaction_1.output_produced[count++] = &d_main_self[0]->_lf_D.disarm.is_present;
            }
        }
        
        // ** End initialization for reaction 1 of D
        // **** Start deferred initialize for D.D
        {
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_0 of D.D.
            d_d_self[0]->_lf__reaction_0.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 0 of D.D
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of D.D.
            d_d_self[0]->_lf__reaction_1.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 1 of D.D
        }
        // **** End of deferred initialize for D.D
    }
    // **** End of deferred initialize for D
    // **** Start non-nested deferred initialize for D
    // Set number of destination reactors for port D.open.
    // Iterate over range D.D.open(0,1)->[D.D.open(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        d_main_self[src_runtime]->_lf_D.open.num_destinations = 1;
    }
    // Set number of destination reactors for port D.disarm.
    // Iterate over range D.D.disarm(0,1)->[D.D.disarm(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        d_main_self[src_runtime]->_lf_D.disarm.num_destinations = 1;
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range D.D.open(0,1)->[D.D.open(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 0 of D triggers 1 downstream reactions
            // through port D.D.open.
            d_main_self[src_runtime]->_lf__reaction_0.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 0 of D, allocate an
            // array of trigger pointers for downstream reactions through port D.D.open
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &d_main_self[src_runtime]->base.allocations); 
            d_main_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges D.D.open(0,1)->[D.D.open(0,1)] and D.D.open(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range D.D.open(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port D.D.open's trigger struct.
                d_main_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime] + src_channel][0] = &d_d_self[dst_runtime]->_lf__open;
            }
        }
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range D.D.disarm(0,1)->[D.D.disarm(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 1 of D triggers 1 downstream reactions
            // through port D.D.disarm.
            d_main_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 1 of D, allocate an
            // array of trigger pointers for downstream reactions through port D.D.disarm
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &d_main_self[src_runtime]->base.allocations); 
            d_main_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges D.D.disarm(0,1)->[D.D.disarm(0,1)] and D.D.disarm(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range D.D.disarm(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port D.D.disarm's trigger struct.
                d_main_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &d_d_self[dst_runtime]->_lf__disarm;
            }
        }
    }
    // **** Start non-nested deferred initialize for D.D
    // **** End of non-nested deferred initialize for D.D
    // **** End of non-nested deferred initialize for D
    // Connect inputs and outputs for reactor D.
    // Connect inputs and outputs for reactor D.D.
    // Connect D.D.open(0,1)->[D.D.open(0,1)] to port D.D.open(0,1)
    // Iterate over ranges D.D.open(0,1)->[D.D.open(0,1)] and D.D.open(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range D.D.open(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            d_d_self[dst_runtime]->_lf_open = (door_open_t*)&d_main_self[src_runtime]->_lf_D.open;
        }
    }
    // Connect D.D.disarm(0,1)->[D.D.disarm(0,1)] to port D.D.disarm(0,1)
    // Iterate over ranges D.D.disarm(0,1)->[D.D.disarm(0,1)] and D.D.disarm(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range D.D.disarm(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            d_d_self[dst_runtime]->_lf_disarm = (door_disarm_t*)&d_main_self[src_runtime]->_lf_D.disarm;
        }
    }
    {
    }
    // Add port D.D.open to array of is_present fields.
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            {
                _lf_is_present_fields[0 + count] = &d_main_self[0]->_lf_D.open.is_present;
                #ifdef FEDERATED_DECENTRALIZED
                _lf_intended_tag_fields[0 + count] = &d_main_self[0]->_lf_D.open.intended_tag;
                #endif // FEDERATED_DECENTRALIZED
                count++;
            }
        }
    }
    // Add port D.D.disarm to array of is_present fields.
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            {
                _lf_is_present_fields[1 + count] = &d_main_self[0]->_lf_D.disarm.is_present;
                #ifdef FEDERATED_DECENTRALIZED
                _lf_intended_tag_fields[1 + count] = &d_main_self[0]->_lf_D.disarm.intended_tag;
                #endif // FEDERATED_DECENTRALIZED
                count++;
            }
        }
    }
    {
        // Add action D.networkMessage to array of is_present fields.
        _lf_is_present_fields[2] 
                = &d_main_self[0]->_lf_networkMessage.is_present;
        #ifdef FEDERATED_DECENTRALIZED
        // Add action D.networkMessage to array of intended_tag fields.
        _lf_intended_tag_fields[2] 
                = &d_main_self[0]->_lf_networkMessage.intended_tag;
        #endif // FEDERATED_DECENTRALIZED
    }
    {
        // Add action D.networkMessage_0 to array of is_present fields.
        _lf_is_present_fields[3] 
                = &d_main_self[0]->_lf_networkMessage_0.is_present;
        #ifdef FEDERATED_DECENTRALIZED
        // Add action D.networkMessage_0 to array of intended_tag fields.
        _lf_intended_tag_fields[3] 
                = &d_main_self[0]->_lf_networkMessage_0.intended_tag;
        #endif // FEDERATED_DECENTRALIZED
    }
    // Set reaction priorities for ReactorInstance D
    {
        d_main_self[0]->_lf__reaction_0.chain_id = 1;
        // index is the OR of level 0 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        d_main_self[0]->_lf__reaction_0.index = 0xffffffffffff0000LL;
        d_main_self[0]->_lf__reaction_1.chain_id = 1;
        // index is the OR of level 0 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        d_main_self[0]->_lf__reaction_1.index = 0xffffffffffff0000LL;
        // Set reaction priorities for ReactorInstance D.D
        {
            d_d_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 1 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            d_d_self[0]->_lf__reaction_0.index = 0xffffffffffff0001LL;
            d_d_self[0]->_lf__reaction_1.chain_id = 1;
            // index is the OR of level 2 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            d_d_self[0]->_lf__reaction_1.index = 0xffffffffffff0002LL;
        }
    }
    // Initialize the scheduler
    size_t num_reactions_per_level[3] = 
        {2, 1, 1};
    sched_params_t sched_params = (sched_params_t) {
                            .num_reactions_per_level = &num_reactions_per_level[0],
                            .num_reactions_per_level_size = (size_t) 3};
    lf_sched_init(
        (size_t)_lf_number_of_workers,
        &sched_params
    );
    #ifdef EXECUTABLE_PREAMBLE
    _lf_executable_preamble();
    #endif
    #ifdef FEDERATED
    initialize_triggers_for_federate();
    #endif // FEDERATED
}
void _lf_trigger_startup_reactions() {}
void _lf_initialize_timers() {

}
void logical_tag_complete(tag_t tag_to_send) {
#ifdef FEDERATED_CENTRALIZED
        _lf_logical_tag_complete(tag_to_send);
#endif // FEDERATED_CENTRALIZED

}
bool _lf_trigger_shutdown_reactions() {
    return false;
}
#ifndef FEDERATED
void terminate_execution() {}
#endif
