// Code generated by the Lingua Franca compiler from:
// file://home/plutonh/project/src/HelloWorldPy.lf
#define LOG_LEVEL 2
#define TARGET_FILES_DIRECTORY "/home/plutonh/project/src-gen/HelloWorldPy"
#define _LF_GARBAGE_COLLECTED
#include "include/ctarget/ctarget.h"
#include "core/reactor.c"
#include "core/mixed_radix.h"
#include "pythontarget.c"
int main(int argc, char* argv[]) {
    return lf_reactor_c_main(argc, argv);
}
void _lf_set_default_command_line_options() {}
// =============== START reactor class HelloWorld2
typedef struct {
    struct self_base_t base;
    char *_lf_name;
    PyObject* _lf_py_reaction_function_0;
    PyObject* _lf_py_reaction_function_1;
    #line 5 "file:/home/plutonh/project/src/HelloWorldPy.lf"
    reaction_t _lf__reaction_0;
    #line 9 "file:/home/plutonh/project/src/HelloWorldPy.lf"
    reaction_t _lf__reaction_1;
    trigger_t _lf__startup;
    reaction_t* _lf__startup_reactions[1];
    trigger_t _lf__shutdown;
    reaction_t* _lf__shutdown_reactions[1];
} helloworld2_self_t;
#include "include/ctarget/set.h"
void helloworld2reaction_function_0(void* instance_args){
    #pragma GCC diagnostic push
    #pragma GCC diagnostic ignored "-Wunused-variable"
    helloworld2_self_t* self = (helloworld2_self_t*)instance_args;
    #pragma GCC diagnostic pop
    #line 6 "file:/home/plutonh/project/src/HelloWorldPy.lf"
    // Acquire the GIL (Global Interpreter Lock) to be able to call Python APIs.
    PyGILState_STATE gstate;
    gstate = PyGILState_Ensure();
    LF_PRINT_DEBUG("Calling reaction function HelloWorld2.reaction_function_0");
    PyObject *rValue = PyObject_CallObject(
        self->_lf_py_reaction_function_0, 
        Py_BuildValue("()")
    );
    if (rValue == NULL) {
        lf_print_error("FATAL: Calling reaction HelloWorld2.reaction_function_0 failed.");
        if (PyErr_Occurred()) {
            PyErr_PrintEx(0);
            PyErr_Clear(); // this will reset the error indicator so we can run Python code again
        }
        /* Release the thread. No Python API allowed beyond this point. */
    PyGILState_Release(gstate);
        Py_FinalizeEx();
        exit(1);
    }
    
    /* Release the thread. No Python API allowed beyond this point. */
    /* Release the thread. No Python API allowed beyond this point. */
    PyGILState_Release(gstate);
}
#include "include/ctarget/set_undef.h"
#include "include/ctarget/set.h"
void helloworld2reaction_function_1(void* instance_args){
    #pragma GCC diagnostic push
    #pragma GCC diagnostic ignored "-Wunused-variable"
    helloworld2_self_t* self = (helloworld2_self_t*)instance_args;
    #pragma GCC diagnostic pop
    #line 10 "file:/home/plutonh/project/src/HelloWorldPy.lf"
    // Acquire the GIL (Global Interpreter Lock) to be able to call Python APIs.
    PyGILState_STATE gstate;
    gstate = PyGILState_Ensure();
    LF_PRINT_DEBUG("Calling reaction function HelloWorld2.reaction_function_1");
    PyObject *rValue = PyObject_CallObject(
        self->_lf_py_reaction_function_1, 
        Py_BuildValue("()")
    );
    if (rValue == NULL) {
        lf_print_error("FATAL: Calling reaction HelloWorld2.reaction_function_1 failed.");
        if (PyErr_Occurred()) {
            PyErr_PrintEx(0);
            PyErr_Clear(); // this will reset the error indicator so we can run Python code again
        }
        /* Release the thread. No Python API allowed beyond this point. */
    PyGILState_Release(gstate);
        Py_FinalizeEx();
        exit(1);
    }
    
    /* Release the thread. No Python API allowed beyond this point. */
    /* Release the thread. No Python API allowed beyond this point. */
    PyGILState_Release(gstate);
}
#include "include/ctarget/set_undef.h"
helloworld2_self_t* new_HelloWorld2() {
    helloworld2_self_t* self = (helloworld2_self_t*)_lf_new_reactor(sizeof(helloworld2_self_t));
    #line 5 "file:/home/plutonh/project/src/HelloWorldPy.lf"
    self->_lf__reaction_0.number = 0;
    #line 5 "file:/home/plutonh/project/src/HelloWorldPy.lf"
    self->_lf__reaction_0.function = helloworld2reaction_function_0;
    #line 5 "file:/home/plutonh/project/src/HelloWorldPy.lf"
    self->_lf__reaction_0.self = self;
    #line 5 "file:/home/plutonh/project/src/HelloWorldPy.lf"
    self->_lf__reaction_0.deadline_violation_handler = NULL;
    #line 5 "file:/home/plutonh/project/src/HelloWorldPy.lf"
    self->_lf__reaction_0.STP_handler = NULL;
    #line 5 "file:/home/plutonh/project/src/HelloWorldPy.lf"
    self->_lf__reaction_0.name = "?";
    #line 5 "file:/home/plutonh/project/src/HelloWorldPy.lf"
    self->_lf__reaction_0.mode = NULL;
    #line 9 "file:/home/plutonh/project/src/HelloWorldPy.lf"
    self->_lf__reaction_1.number = 1;
    #line 9 "file:/home/plutonh/project/src/HelloWorldPy.lf"
    self->_lf__reaction_1.function = helloworld2reaction_function_1;
    #line 9 "file:/home/plutonh/project/src/HelloWorldPy.lf"
    self->_lf__reaction_1.self = self;
    #line 9 "file:/home/plutonh/project/src/HelloWorldPy.lf"
    self->_lf__reaction_1.deadline_violation_handler = NULL;
    #line 9 "file:/home/plutonh/project/src/HelloWorldPy.lf"
    self->_lf__reaction_1.STP_handler = NULL;
    #line 9 "file:/home/plutonh/project/src/HelloWorldPy.lf"
    self->_lf__reaction_1.name = "?";
    #line 9 "file:/home/plutonh/project/src/HelloWorldPy.lf"
    self->_lf__reaction_1.mode = NULL;
    self->_lf__startup_reactions[0] = &self->_lf__reaction_0;
    self->_lf__startup.last = NULL;
    self->_lf__startup.reactions = &self->_lf__startup_reactions[0];
    self->_lf__startup.number_of_reactions = 1;
    self->_lf__startup.is_timer = false;
    self->_lf__shutdown_reactions[0] = &self->_lf__reaction_1;
    self->_lf__shutdown.last = NULL;
    self->_lf__shutdown.reactions = &self->_lf__shutdown_reactions[0];
    self->_lf__shutdown.number_of_reactions = 1;
    self->_lf__shutdown.is_timer = false;
    return self;
}
// =============== END reactor class HelloWorld2
// =============== START reactor class HelloWorldPy
typedef struct {
    struct self_base_t base;
    char *_lf_name;
} helloworldpy_self_t;
helloworldpy_self_t* new_HelloWorldPy() {
    helloworldpy_self_t* self = (helloworldpy_self_t*)_lf_new_reactor(sizeof(helloworldpy_self_t));
    return self;
}
// =============== END reactor class HelloWorldPy
// Array of pointers to timer triggers to be scheduled in _lf_initialize_timers().
trigger_t** _lf_timer_triggers = NULL;
int _lf_timer_triggers_size = 0;
// Array of pointers to startup triggers.
reaction_t* _lf_startup_reactions[1];
int _lf_startup_reactions_size = 1;
// Array of pointers to shutdown triggers.
reaction_t* _lf_shutdown_reactions[1];
int _lf_shutdown_reactions_size = 1;
// Array of pointers to reset triggers.
reaction_t** _lf_reset_reactions = NULL;
int _lf_reset_reactions_size = 0;
trigger_t* _lf_action_for_port(int port_id) {
        return NULL;
}
void _lf_initialize_trigger_objects() {
    // Initialize the _lf_clock
    lf_initialize_clock();
    int _lf_startup_reactions_count = 0;
    int _lf_shutdown_reactions_count = 0;
    int _lf_reset_reactions_count = 0;
    int _lf_timer_triggers_count = 0;
    int _lf_tokens_with_ref_count_count = 0;
    helloworldpy_self_t* helloworldpy_self[1];
    helloworld2_self_t* helloworldpy_a_self[1];
    // ***** Start initializing HelloWorldPy of class HelloWorldPy
    helloworldpy_self[0] = new_HelloWorldPy();
    helloworldpy_self[0]->_lf_name = "helloworldpy_lf";
    {
        // ***** Start initializing HelloWorldPy.a of class HelloWorld2
        helloworldpy_a_self[0] = new_HelloWorld2();
        helloworldpy_a_self[0]->_lf_name = "helloworldpy_a_lf";
        helloworldpy_a_self[0]->_lf_py_reaction_function_0 = 
        get_python_function("__main__", 
            helloworldpy_a_self[0]->_lf_name,
            0,
            "reaction_function_0");
        if(helloworldpy_a_self[0]->_lf_py_reaction_function_0 == NULL) {
            lf_print_error_and_exit("Could not load function reaction_function_0");
        }
        helloworldpy_a_self[0]->_lf_py_reaction_function_1 = 
        get_python_function("__main__", 
            helloworldpy_a_self[0]->_lf_name,
            0,
            "reaction_function_1");
        if(helloworldpy_a_self[0]->_lf_py_reaction_function_1 == NULL) {
            lf_print_error_and_exit("Could not load function reaction_function_1");
        }
        _lf_startup_reactions[_lf_startup_reactions_count++] = &helloworldpy_a_self[0]->_lf__reaction_0;
        _lf_shutdown_reactions[_lf_shutdown_reactions_count++] = &helloworldpy_a_self[0]->_lf__reaction_1;
        helloworldpy_a_self[0]->_lf__reaction_0.deadline = NEVER;
        helloworldpy_a_self[0]->_lf__reaction_1.deadline = NEVER;
        //***** End initializing HelloWorldPy.a
    }
    //***** End initializing HelloWorldPy
    // **** Start deferred initialize for HelloWorldPy
    {
        // **** Start deferred initialize for HelloWorldPy.a
        {
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_0 of HelloWorldPy.a.
            helloworldpy_a_self[0]->_lf__reaction_0.num_outputs = 0;
            {
                int count = 0;
            }
            
            // ** End initialization for reaction 0 of HelloWorldPy.a
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of HelloWorldPy.a.
            helloworldpy_a_self[0]->_lf__reaction_1.num_outputs = 0;
            {
                int count = 0;
            }
            
            // ** End initialization for reaction 1 of HelloWorldPy.a
        }
        // **** End of deferred initialize for HelloWorldPy.a
    }
    // **** End of deferred initialize for HelloWorldPy
    // **** Start non-nested deferred initialize for HelloWorldPy
    // **** Start non-nested deferred initialize for HelloWorldPy.a
    // **** End of non-nested deferred initialize for HelloWorldPy.a
    // **** End of non-nested deferred initialize for HelloWorldPy
    // Connect inputs and outputs for reactor HelloWorldPy.
    // Connect inputs and outputs for reactor HelloWorldPy.a.
    {
    }
    // Set reaction priorities for ReactorInstance HelloWorldPy
    {
        // Set reaction priorities for ReactorInstance HelloWorldPy.a
        {
            helloworldpy_a_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 0 and 
            // deadline 140737488355327 shifted left 16 bits.
            helloworldpy_a_self[0]->_lf__reaction_0.index = 0x7fffffffffff0000LL;
            helloworldpy_a_self[0]->_lf__reaction_1.chain_id = 1;
            // index is the OR of level 1 and 
            // deadline 140737488355327 shifted left 16 bits.
            helloworldpy_a_self[0]->_lf__reaction_1.index = 0x7fffffffffff0001LL;
        }
    }
}
void _lf_trigger_startup_reactions() {
    for (int i = 0; i < _lf_startup_reactions_size; i++) {
        if (_lf_startup_reactions[i] != NULL) {
            _lf_trigger_reaction(_lf_startup_reactions[i], -1);
        }
    }
}
void _lf_initialize_timers() {

}
void logical_tag_complete(tag_t tag_to_send) {

}
bool _lf_trigger_shutdown_reactions() {
    for (int i = 0; i < _lf_shutdown_reactions_size; i++) {
        if (_lf_shutdown_reactions[i] != NULL) {
            _lf_trigger_reaction(_lf_shutdown_reactions[i], -1);
        }
    }
    return true;
}
void terminate_execution() {}
