// Code generated by the Lingua Franca compiler from:
// file://home/plutonh/project/fed-gen/Waiting_Line/src/A.lf
#define LOG_LEVEL 2
#define TARGET_FILES_DIRECTORY "/home/plutonh/project/fed-gen/Waiting_Line/src-gen/A"
#include "include/api/api.h"
#include "core/reactor.h"
#include "core/reactor_common.h"
#include "core/threaded/scheduler.h"
#include "core/mixed_radix.h"
#include "core/port.h"
int lf_reactor_c_main(int argc, const char* argv[]);
#include "core/federated/federate.h"
#include "core/federated/net_common.h"
#include "include/_A_preamble.h"
int main(int argc, const char* argv[]) {
    return lf_reactor_c_main(argc, argv);
}
const char* _lf_default_argv[] = { "dummy", "-k", "true" };
void _lf_set_default_command_line_options() {
        default_argc = 3;
        default_argv = _lf_default_argv;
}
// =============== START reactor class Arbiter
typedef struct {
    token_type_t type;
    lf_token_t* token;
    size_t length;
    bool is_present;
    lf_sparse_io_record_t* sparse_record;
    int destination_channel;
    int num_destinations;
    bool value;
    #ifdef FEDERATED
    #ifdef FEDERATED_DECENTRALIZED
    tag_t intended_tag;
    #endif
    interval_t physical_time_of_arrival;
    #endif
} arbiter_sensor_1_t;
typedef struct {
    token_type_t type;
    lf_token_t* token;
    size_t length;
    bool is_present;
    lf_sparse_io_record_t* sparse_record;
    int destination_channel;
    int num_destinations;
    bool value;
    #ifdef FEDERATED
    #ifdef FEDERATED_DECENTRALIZED
    tag_t intended_tag;
    #endif
    interval_t physical_time_of_arrival;
    #endif
} arbiter_sensor_2_t;
typedef struct {
    token_type_t type;
    lf_token_t* token;
    size_t length;
    bool is_present;
    lf_sparse_io_record_t* sparse_record;
    int destination_channel;
    int num_destinations;
    int value;
    #ifdef FEDERATED
    #ifdef FEDERATED_DECENTRALIZED
    tag_t intended_tag;
    #endif
    interval_t physical_time_of_arrival;
    #endif
} arbiter_control_t;
typedef struct {
    token_type_t type;
    lf_token_t* token;
    size_t length;
    bool is_present;
    lf_sparse_io_record_t* sparse_record;
    int destination_channel;
    int num_destinations;
    int value;
    #ifdef FEDERATED
    #ifdef FEDERATED_DECENTRALIZED
    tag_t intended_tag;
    #endif
    interval_t physical_time_of_arrival;
    #endif
} arbiter_result_t;
typedef struct {
    struct self_base_t base;
    #line 17 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    arbiter_sensor_1_t* _lf_sensor_1;
    #line 17 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    // width of -2 indicates that it is not a multiport.
    #line 17 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    int _lf_sensor_1_width;
    #line 17 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    // Default input (in case it does not get connected)
    #line 17 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    arbiter_sensor_1_t _lf_default__sensor_1;
    #line 18 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    arbiter_sensor_2_t* _lf_sensor_2;
    #line 18 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    // width of -2 indicates that it is not a multiport.
    #line 18 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    int _lf_sensor_2_width;
    #line 18 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    // Default input (in case it does not get connected)
    #line 18 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    arbiter_sensor_2_t _lf_default__sensor_2;
    #line 19 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    arbiter_control_t* _lf_control;
    #line 19 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    // width of -2 indicates that it is not a multiport.
    #line 19 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    int _lf_control_width;
    #line 19 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    // Default input (in case it does not get connected)
    #line 19 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    arbiter_control_t _lf_default__control;
    #line 20 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    arbiter_result_t _lf_result;
    #line 20 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    int _lf_result_width;
    #line 17 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    trigger_t _lf__sensor_1;
    #ifdef FEDERATED
    
    #endif // FEDERATED
    #line 18 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    trigger_t _lf__sensor_2;
    #ifdef FEDERATED
    
    #endif // FEDERATED
    #line 19 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    trigger_t _lf__control;
    #ifdef FEDERATED
    
    #endif // FEDERATED
} arbiter_self_t;
// ***** Start of method declarations.
// ***** End of method declarations.
arbiter_self_t* new_Arbiter() {
    arbiter_self_t* self = (arbiter_self_t*)_lf_new_reactor(sizeof(arbiter_self_t));
    #line 17 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    // Set input by default to an always absent default input.
    #line 17 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf_sensor_1 = &self->_lf_default__sensor_1;
    #line 18 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    // Set input by default to an always absent default input.
    #line 18 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf_sensor_2 = &self->_lf_default__sensor_2;
    #line 19 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    // Set input by default to an always absent default input.
    #line 19 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf_control = &self->_lf_default__control;
    #line 17 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__sensor_1.last = NULL;
    #line 17 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    #ifdef FEDERATED_DECENTRALIZED
    #line 17 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__sensor_1.intended_tag = (tag_t) { .time = NEVER, .microstep = 0u};
    #line 17 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    #endif // FEDERATED_DECENTRALIZED
    self->_lf__sensor_1.tmplt.type.element_size = sizeof(bool);
    #line 18 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__sensor_2.last = NULL;
    #line 18 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    #ifdef FEDERATED_DECENTRALIZED
    #line 18 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__sensor_2.intended_tag = (tag_t) { .time = NEVER, .microstep = 0u};
    #line 18 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    #endif // FEDERATED_DECENTRALIZED
    self->_lf__sensor_2.tmplt.type.element_size = sizeof(bool);
    #line 19 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__control.last = NULL;
    #line 19 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    #ifdef FEDERATED_DECENTRALIZED
    #line 19 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__control.intended_tag = (tag_t) { .time = NEVER, .microstep = 0u};
    #line 19 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    #endif // FEDERATED_DECENTRALIZED
    self->_lf__control.tmplt.type.element_size = sizeof(int);
    return self;
}
// =============== END reactor class Arbiter
// =============== START reactor class A
typedef struct {
    token_type_t type;
    lf_token_t* token;
    size_t length;
    bool is_present;
    bool has_value;
    trigger_t* trigger;
    #ifdef FEDERATED
    #ifdef FEDERATED_DECENTRALIZED
    tag_t intended_tag;
    #endif
    interval_t physical_time_of_arrival;
    #endif
} a_outputControlReactionTrigger_t;
typedef struct {
    token_type_t type;
    lf_token_t* token;
    size_t length;
    bool is_present;
    bool has_value;
    trigger_t* trigger;
    #ifdef FEDERATED
    #ifdef FEDERATED_DECENTRALIZED
    tag_t intended_tag;
    #endif
    interval_t physical_time_of_arrival;
    #endif
} a_inputControlReactionTrigger_1_t;
typedef struct {
    token_type_t type;
    lf_token_t* token;
    size_t length;
    bool is_present;
    bool has_value;
    trigger_t* trigger;
    bool value;
    #ifdef FEDERATED
    #ifdef FEDERATED_DECENTRALIZED
    tag_t intended_tag;
    #endif
    interval_t physical_time_of_arrival;
    #endif
} a_networkMessage_1_t;
typedef struct {
    token_type_t type;
    lf_token_t* token;
    size_t length;
    bool is_present;
    bool has_value;
    trigger_t* trigger;
    #ifdef FEDERATED
    #ifdef FEDERATED_DECENTRALIZED
    tag_t intended_tag;
    #endif
    interval_t physical_time_of_arrival;
    #endif
} a_inputControlReactionTrigger_2_t;
typedef struct {
    token_type_t type;
    lf_token_t* token;
    size_t length;
    bool is_present;
    bool has_value;
    trigger_t* trigger;
    bool value;
    #ifdef FEDERATED
    #ifdef FEDERATED_DECENTRALIZED
    tag_t intended_tag;
    #endif
    interval_t physical_time_of_arrival;
    #endif
} a_networkMessage_2_t;
typedef struct {
    token_type_t type;
    lf_token_t* token;
    size_t length;
    bool is_present;
    bool has_value;
    trigger_t* trigger;
    #ifdef FEDERATED
    #ifdef FEDERATED_DECENTRALIZED
    tag_t intended_tag;
    #endif
    interval_t physical_time_of_arrival;
    #endif
} a_inputControlReactionTrigger_3_t;
typedef struct {
    token_type_t type;
    lf_token_t* token;
    size_t length;
    bool is_present;
    bool has_value;
    trigger_t* trigger;
    int value;
    #ifdef FEDERATED
    #ifdef FEDERATED_DECENTRALIZED
    tag_t intended_tag;
    #endif
    interval_t physical_time_of_arrival;
    #endif
} a_networkMessage_3_t;
typedef struct {
    struct self_base_t base;
    #line 27 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    a_outputControlReactionTrigger_t _lf_outputControlReactionTrigger;
    #line 28 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    a_inputControlReactionTrigger_1_t _lf_inputControlReactionTrigger_1;
    #line 29 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    a_networkMessage_1_t _lf_networkMessage_1;
    #line 30 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    a_inputControlReactionTrigger_2_t _lf_inputControlReactionTrigger_2;
    #line 31 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    a_networkMessage_2_t _lf_networkMessage_2;
    #line 32 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    a_inputControlReactionTrigger_3_t _lf_inputControlReactionTrigger_3;
    #line 33 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    a_networkMessage_3_t _lf_networkMessage_3;
    struct {
        #line 20 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
        arbiter_result_t* result;
        #line 20 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
        trigger_t result_trigger;
        #line 20 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
        reaction_t* result_reactions[2];
        #line 17 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
        arbiter_sensor_1_t sensor_1;
        #line 18 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
        arbiter_sensor_2_t sensor_2;
        #line 19 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
        arbiter_control_t control;
    } _lf_A;
    int _lf_A_width;
    #line 36 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    reaction_t _lf__reaction_0;
    #line 44 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    reaction_t _lf__reaction_1;
    #line 57 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    reaction_t _lf__reaction_2;
    #line 65 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    reaction_t _lf__reaction_3;
    #line 78 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    reaction_t _lf__reaction_4;
    #line 85 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    reaction_t _lf__reaction_5;
    #line 91 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    reaction_t _lf__reaction_6;
    #line 98 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    reaction_t _lf__reaction_7;
    #line 104 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    reaction_t _lf__reaction_8;
    #line 111 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    reaction_t _lf__reaction_9;
    #line 27 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    trigger_t _lf__outputControlReactionTrigger;
    #line 27 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    reaction_t* _lf__outputControlReactionTrigger_reactions[2];
    #line 28 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    trigger_t _lf__inputControlReactionTrigger_1;
    #line 28 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    reaction_t* _lf__inputControlReactionTrigger_1_reactions[1];
    #line 29 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    trigger_t _lf__networkMessage_1;
    #line 29 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    reaction_t* _lf__networkMessage_1_reactions[1];
    #line 30 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    trigger_t _lf__inputControlReactionTrigger_2;
    #line 30 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    reaction_t* _lf__inputControlReactionTrigger_2_reactions[1];
    #line 31 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    trigger_t _lf__networkMessage_2;
    #line 31 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    reaction_t* _lf__networkMessage_2_reactions[1];
    #line 32 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    trigger_t _lf__inputControlReactionTrigger_3;
    #line 32 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    reaction_t* _lf__inputControlReactionTrigger_3_reactions[1];
    #line 33 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    trigger_t _lf__networkMessage_3;
    #line 33 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    reaction_t* _lf__networkMessage_3_reactions[1];
} a_main_self_t;
// ***** Start of method declarations.
// ***** End of method declarations.
#include "include/api/set.h"
void a_mainreaction_function_0(void* instance_args) {
    a_main_self_t* self = (a_main_self_t*)instance_args; SUPPRESS_UNUSED_WARNING(self);
    struct A {
        arbiter_result_t* result;
    
    } A;
    A.result = self->_lf_A.result;
    #line 38 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    // **** This reaction is unordered.
    // Sending from A.result in federate A to H.result in federate H
    if (!A.result->is_present) return;
    size_t message_length = sizeof(int);
    send_timed_message(NEVER, MSG_TYPE_TAGGED_MESSAGE, 0, 3, "federate 3 via the RTI", message_length, (unsigned char*)&A.result->value);
}
#include "include/api/set_undef.h"
#include "include/api/set.h"
void a_mainreaction_function_1(void* instance_args) {
    a_main_self_t* self = (a_main_self_t*)instance_args; SUPPRESS_UNUSED_WARNING(self);
    struct A {
        arbiter_result_t* result;
    
    } A;
    // Expose the action struct as a local variable whose name matches the action name.
    a_outputControlReactionTrigger_t* outputControlReactionTrigger = &self->_lf_outputControlReactionTrigger;
    // Set the fields of the action struct to match the current trigger.
    outputControlReactionTrigger->is_present = (bool)self->_lf__outputControlReactionTrigger.status;
    outputControlReactionTrigger->has_value = ((self->_lf__outputControlReactionTrigger.tmplt.token) != NULL && (self->_lf__outputControlReactionTrigger.tmplt.token)->value != NULL);
    _lf_replace_template_token((token_template_t*)outputControlReactionTrigger, (self->_lf__outputControlReactionTrigger.tmplt.token));
    A.result = self->_lf_A.result;
    #line 46 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    // **** This reaction is unordered.
    // If the output port has not been lf_set for the current logical time,
    // send an ABSENT message to the receiving federate
    LF_PRINT_LOG("Contemplating whether to send port "
              "absent for port %d to federate %d.",
              0, 3);
    if (A.result == NULL || !A.result->is_present) {
        // The output port is NULL or it is not present.
        send_port_absent_to_federate(NEVER, 0, 3);
    }
}
#include "include/api/set_undef.h"
#include "include/api/set.h"
void a_mainreaction_function_2(void* instance_args) {
    a_main_self_t* self = (a_main_self_t*)instance_args; SUPPRESS_UNUSED_WARNING(self);
    struct A {
        arbiter_result_t* result;
    
    } A;
    A.result = self->_lf_A.result;
    #line 59 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    // **** This reaction is unordered.
    // Sending from A.result in federate A to SM.result in federate SM
    if (!A.result->is_present) return;
    size_t message_length = sizeof(int);
    send_timed_message(NEVER, MSG_TYPE_TAGGED_MESSAGE, 0, 4, "federate 4 via the RTI", message_length, (unsigned char*)&A.result->value);
}
#include "include/api/set_undef.h"
#include "include/api/set.h"
void a_mainreaction_function_3(void* instance_args) {
    a_main_self_t* self = (a_main_self_t*)instance_args; SUPPRESS_UNUSED_WARNING(self);
    struct A {
        arbiter_result_t* result;
    
    } A;
    // Expose the action struct as a local variable whose name matches the action name.
    a_outputControlReactionTrigger_t* outputControlReactionTrigger = &self->_lf_outputControlReactionTrigger;
    // Set the fields of the action struct to match the current trigger.
    outputControlReactionTrigger->is_present = (bool)self->_lf__outputControlReactionTrigger.status;
    outputControlReactionTrigger->has_value = ((self->_lf__outputControlReactionTrigger.tmplt.token) != NULL && (self->_lf__outputControlReactionTrigger.tmplt.token)->value != NULL);
    _lf_replace_template_token((token_template_t*)outputControlReactionTrigger, (self->_lf__outputControlReactionTrigger.tmplt.token));
    A.result = self->_lf_A.result;
    #line 67 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    // **** This reaction is unordered.
    // If the output port has not been lf_set for the current logical time,
    // send an ABSENT message to the receiving federate
    LF_PRINT_LOG("Contemplating whether to send port "
              "absent for port %d to federate %d.",
              0, 4);
    if (A.result == NULL || !A.result->is_present) {
        // The output port is NULL or it is not present.
        send_port_absent_to_federate(NEVER, 0, 4);
    }
}
#include "include/api/set_undef.h"
#include "include/api/set.h"
void a_mainreaction_function_4(void* instance_args) {
    a_main_self_t* self = (a_main_self_t*)instance_args; SUPPRESS_UNUSED_WARNING(self);
    struct A {
        arbiter_sensor_1_t* sensor_1;
    
    } A;
    // Expose the action struct as a local variable whose name matches the action name.
    a_inputControlReactionTrigger_1_t* inputControlReactionTrigger_1 = &self->_lf_inputControlReactionTrigger_1;
    // Set the fields of the action struct to match the current trigger.
    inputControlReactionTrigger_1->is_present = (bool)self->_lf__inputControlReactionTrigger_1.status;
    inputControlReactionTrigger_1->has_value = ((self->_lf__inputControlReactionTrigger_1.tmplt.token) != NULL && (self->_lf__inputControlReactionTrigger_1.tmplt.token)->value != NULL);
    _lf_replace_template_token((token_template_t*)inputControlReactionTrigger_1, (self->_lf__inputControlReactionTrigger_1.tmplt.token));
    A.sensor_1 = &(self->_lf_A.sensor_1);
    #line 80 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    // **** This reaction is unordered.
    interval_t max_STP = 0LL;
    // Wait until the port status is known
    wait_until_port_status_known(0, max_STP);
}
#include "include/api/set_undef.h"
#include "include/api/set.h"
void a_mainreaction_function_5(void* instance_args) {
    a_main_self_t* self = (a_main_self_t*)instance_args; SUPPRESS_UNUSED_WARNING(self);
    struct A {
        arbiter_sensor_1_t* sensor_1;
    
    } A;
    // Expose the action struct as a local variable whose name matches the action name.
    a_networkMessage_1_t* networkMessage_1 = &self->_lf_networkMessage_1;
    // Set the fields of the action struct to match the current trigger.
    networkMessage_1->is_present = (bool)self->_lf__networkMessage_1.status;
    networkMessage_1->has_value = ((self->_lf__networkMessage_1.tmplt.token) != NULL && (self->_lf__networkMessage_1.tmplt.token)->value != NULL);
    _lf_replace_template_token((token_template_t*)networkMessage_1, (self->_lf__networkMessage_1.tmplt.token));
    if (networkMessage_1->has_value) {
        networkMessage_1->value = *(bool*)(self->_lf__networkMessage_1.tmplt.token)->value;
    }
    A.sensor_1 = &(self->_lf_A.sensor_1);
    #line 87 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    // **** This reaction is unordered.
    A.sensor_1->physical_time_of_arrival = self->_lf__networkMessage_1.physical_time_of_arrival;
    lf_set(A.sensor_1, networkMessage_1->value);
}
#include "include/api/set_undef.h"
#include "include/api/set.h"
void a_mainreaction_function_6(void* instance_args) {
    a_main_self_t* self = (a_main_self_t*)instance_args; SUPPRESS_UNUSED_WARNING(self);
    struct A {
        arbiter_sensor_2_t* sensor_2;
    
    } A;
    // Expose the action struct as a local variable whose name matches the action name.
    a_inputControlReactionTrigger_2_t* inputControlReactionTrigger_2 = &self->_lf_inputControlReactionTrigger_2;
    // Set the fields of the action struct to match the current trigger.
    inputControlReactionTrigger_2->is_present = (bool)self->_lf__inputControlReactionTrigger_2.status;
    inputControlReactionTrigger_2->has_value = ((self->_lf__inputControlReactionTrigger_2.tmplt.token) != NULL && (self->_lf__inputControlReactionTrigger_2.tmplt.token)->value != NULL);
    _lf_replace_template_token((token_template_t*)inputControlReactionTrigger_2, (self->_lf__inputControlReactionTrigger_2.tmplt.token));
    A.sensor_2 = &(self->_lf_A.sensor_2);
    #line 93 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    // **** This reaction is unordered.
    interval_t max_STP = 0LL;
    // Wait until the port status is known
    wait_until_port_status_known(1, max_STP);
}
#include "include/api/set_undef.h"
#include "include/api/set.h"
void a_mainreaction_function_7(void* instance_args) {
    a_main_self_t* self = (a_main_self_t*)instance_args; SUPPRESS_UNUSED_WARNING(self);
    struct A {
        arbiter_sensor_2_t* sensor_2;
    
    } A;
    // Expose the action struct as a local variable whose name matches the action name.
    a_networkMessage_2_t* networkMessage_2 = &self->_lf_networkMessage_2;
    // Set the fields of the action struct to match the current trigger.
    networkMessage_2->is_present = (bool)self->_lf__networkMessage_2.status;
    networkMessage_2->has_value = ((self->_lf__networkMessage_2.tmplt.token) != NULL && (self->_lf__networkMessage_2.tmplt.token)->value != NULL);
    _lf_replace_template_token((token_template_t*)networkMessage_2, (self->_lf__networkMessage_2.tmplt.token));
    if (networkMessage_2->has_value) {
        networkMessage_2->value = *(bool*)(self->_lf__networkMessage_2.tmplt.token)->value;
    }
    A.sensor_2 = &(self->_lf_A.sensor_2);
    #line 100 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    // **** This reaction is unordered.
    A.sensor_2->physical_time_of_arrival = self->_lf__networkMessage_2.physical_time_of_arrival;
    lf_set(A.sensor_2, networkMessage_2->value);
}
#include "include/api/set_undef.h"
#include "include/api/set.h"
void a_mainreaction_function_8(void* instance_args) {
    a_main_self_t* self = (a_main_self_t*)instance_args; SUPPRESS_UNUSED_WARNING(self);
    struct A {
        arbiter_control_t* control;
    
    } A;
    // Expose the action struct as a local variable whose name matches the action name.
    a_inputControlReactionTrigger_3_t* inputControlReactionTrigger_3 = &self->_lf_inputControlReactionTrigger_3;
    // Set the fields of the action struct to match the current trigger.
    inputControlReactionTrigger_3->is_present = (bool)self->_lf__inputControlReactionTrigger_3.status;
    inputControlReactionTrigger_3->has_value = ((self->_lf__inputControlReactionTrigger_3.tmplt.token) != NULL && (self->_lf__inputControlReactionTrigger_3.tmplt.token)->value != NULL);
    _lf_replace_template_token((token_template_t*)inputControlReactionTrigger_3, (self->_lf__inputControlReactionTrigger_3.tmplt.token));
    A.control = &(self->_lf_A.control);
    #line 106 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    // **** This reaction is unordered.
    interval_t max_STP = 0LL;
    // Wait until the port status is known
    wait_until_port_status_known(2, max_STP);
}
#include "include/api/set_undef.h"
#include "include/api/set.h"
void a_mainreaction_function_9(void* instance_args) {
    a_main_self_t* self = (a_main_self_t*)instance_args; SUPPRESS_UNUSED_WARNING(self);
    struct A {
        arbiter_control_t* control;
    
    } A;
    // Expose the action struct as a local variable whose name matches the action name.
    a_networkMessage_3_t* networkMessage_3 = &self->_lf_networkMessage_3;
    // Set the fields of the action struct to match the current trigger.
    networkMessage_3->is_present = (bool)self->_lf__networkMessage_3.status;
    networkMessage_3->has_value = ((self->_lf__networkMessage_3.tmplt.token) != NULL && (self->_lf__networkMessage_3.tmplt.token)->value != NULL);
    _lf_replace_template_token((token_template_t*)networkMessage_3, (self->_lf__networkMessage_3.tmplt.token));
    if (networkMessage_3->has_value) {
        networkMessage_3->value = *(int*)(self->_lf__networkMessage_3.tmplt.token)->value;
    }
    A.control = &(self->_lf_A.control);
    #line 113 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    // **** This reaction is unordered.
    A.control->physical_time_of_arrival = self->_lf__networkMessage_3.physical_time_of_arrival;
    lf_set(A.control, networkMessage_3->value);
}
#include "include/api/set_undef.h"
a_main_self_t* new_A() {
    a_main_self_t* self = (a_main_self_t*)_lf_new_reactor(sizeof(a_main_self_t));
    #line 27 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf_outputControlReactionTrigger.trigger = &self->_lf__outputControlReactionTrigger;
    #line 28 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf_inputControlReactionTrigger_1.trigger = &self->_lf__inputControlReactionTrigger_1;
    #line 29 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf_networkMessage_1.trigger = &self->_lf__networkMessage_1;
    #line 30 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf_inputControlReactionTrigger_2.trigger = &self->_lf__inputControlReactionTrigger_2;
    #line 31 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf_networkMessage_2.trigger = &self->_lf__networkMessage_2;
    #line 32 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf_inputControlReactionTrigger_3.trigger = &self->_lf__inputControlReactionTrigger_3;
    #line 33 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf_networkMessage_3.trigger = &self->_lf__networkMessage_3;
    // Set the _width variable for all cases. This will be -2
    // if the reactor is not a bank of reactors.
    self->_lf_A_width = -2;
    #line 20 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    #ifdef FEDERATED_DECENTRALIZED
    #line 20 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf_A.result_trigger.intended_tag = (tag_t) { .time = NEVER, .microstep = 0u};
    #line 20 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    #endif // FEDERATED_DECENTRALIZED
    #line 20 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf_A.result_reactions[0] = &self->_lf__reaction_0;
    #line 20 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf_A.result_reactions[1] = &self->_lf__reaction_2;
    #line 20 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf_A.result_trigger.reactions = self->_lf_A.result_reactions;
    #line 20 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf_A.result_trigger.last = NULL;
    #line 20 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf_A.result_trigger.number_of_reactions = 2;
    #line 20 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    #ifdef FEDERATED
    #line 20 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf_A.result_trigger.physical_time_of_arrival = NEVER;
    #line 20 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    #endif // FEDERATED
    #line 36 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_0.number = 0;
    #line 36 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_0.function = a_mainreaction_function_0;
    #line 36 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_0.self = self;
    #line 36 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_0.deadline_violation_handler = NULL;
    #line 36 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_0.STP_handler = NULL;
    #line 36 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_0.name = "?";
    #line 36 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_0.mode = NULL;
    #line 44 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_1.number = 1;
    #line 44 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_1.function = a_mainreaction_function_1;
    #line 44 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_1.self = self;
    #line 44 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_1.deadline_violation_handler = NULL;
    #line 44 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_1.STP_handler = NULL;
    #line 44 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_1.name = "?";
    #line 44 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_1.mode = NULL;
    #line 57 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_2.number = 2;
    #line 57 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_2.function = a_mainreaction_function_2;
    #line 57 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_2.self = self;
    #line 57 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_2.deadline_violation_handler = NULL;
    #line 57 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_2.STP_handler = NULL;
    #line 57 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_2.name = "?";
    #line 57 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_2.mode = NULL;
    #line 65 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_3.number = 3;
    #line 65 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_3.function = a_mainreaction_function_3;
    #line 65 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_3.self = self;
    #line 65 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_3.deadline_violation_handler = NULL;
    #line 65 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_3.STP_handler = NULL;
    #line 65 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_3.name = "?";
    #line 65 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_3.mode = NULL;
    #line 78 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_4.number = 4;
    #line 78 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_4.function = a_mainreaction_function_4;
    #line 78 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_4.self = self;
    #line 78 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_4.deadline_violation_handler = NULL;
    #line 78 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_4.STP_handler = NULL;
    #line 78 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_4.name = "?";
    #line 78 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_4.mode = NULL;
    #line 85 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_5.number = 5;
    #line 85 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_5.function = a_mainreaction_function_5;
    #line 85 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_5.self = self;
    #line 85 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_5.deadline_violation_handler = NULL;
    #line 85 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_5.STP_handler = NULL;
    #line 85 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_5.name = "?";
    #line 85 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_5.mode = NULL;
    #line 91 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_6.number = 6;
    #line 91 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_6.function = a_mainreaction_function_6;
    #line 91 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_6.self = self;
    #line 91 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_6.deadline_violation_handler = NULL;
    #line 91 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_6.STP_handler = NULL;
    #line 91 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_6.name = "?";
    #line 91 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_6.mode = NULL;
    #line 98 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_7.number = 7;
    #line 98 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_7.function = a_mainreaction_function_7;
    #line 98 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_7.self = self;
    #line 98 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_7.deadline_violation_handler = NULL;
    #line 98 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_7.STP_handler = NULL;
    #line 98 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_7.name = "?";
    #line 98 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_7.mode = NULL;
    #line 104 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_8.number = 8;
    #line 104 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_8.function = a_mainreaction_function_8;
    #line 104 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_8.self = self;
    #line 104 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_8.deadline_violation_handler = NULL;
    #line 104 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_8.STP_handler = NULL;
    #line 104 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_8.name = "?";
    #line 104 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_8.mode = NULL;
    #line 111 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_9.number = 9;
    #line 111 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_9.function = a_mainreaction_function_9;
    #line 111 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_9.self = self;
    #line 111 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_9.deadline_violation_handler = NULL;
    #line 111 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_9.STP_handler = NULL;
    #line 111 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_9.name = "?";
    #line 111 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__reaction_9.mode = NULL;
    #line 27 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__outputControlReactionTrigger.last = NULL;
    #line 27 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    #ifdef FEDERATED_DECENTRALIZED
    #line 27 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__outputControlReactionTrigger.intended_tag = (tag_t) { .time = NEVER, .microstep = 0u};
    #line 27 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    #endif // FEDERATED_DECENTRALIZED
    #line 27 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    #line 27 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__outputControlReactionTrigger_reactions[0] = &self->_lf__reaction_1;
    #line 27 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    #line 27 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__outputControlReactionTrigger_reactions[1] = &self->_lf__reaction_3;
    #line 27 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__outputControlReactionTrigger.reactions = &self->_lf__outputControlReactionTrigger_reactions[0];
    #line 27 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__outputControlReactionTrigger.number_of_reactions = 2;
    #line 27 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    #ifdef FEDERATED
    #line 27 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__outputControlReactionTrigger.physical_time_of_arrival = NEVER;
    #line 27 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    #endif // FEDERATED
    self->_lf__outputControlReactionTrigger.is_physical = false;
    
    self->_lf__outputControlReactionTrigger.tmplt.type.element_size = 0;
    self->_lf_outputControlReactionTrigger.type.element_size = 0;
    #line 28 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__inputControlReactionTrigger_1.last = NULL;
    #line 28 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    #ifdef FEDERATED_DECENTRALIZED
    #line 28 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__inputControlReactionTrigger_1.intended_tag = (tag_t) { .time = NEVER, .microstep = 0u};
    #line 28 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    #endif // FEDERATED_DECENTRALIZED
    #line 28 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    #line 28 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__inputControlReactionTrigger_1_reactions[0] = &self->_lf__reaction_4;
    #line 28 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__inputControlReactionTrigger_1.reactions = &self->_lf__inputControlReactionTrigger_1_reactions[0];
    #line 28 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__inputControlReactionTrigger_1.number_of_reactions = 1;
    #line 28 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    #ifdef FEDERATED
    #line 28 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__inputControlReactionTrigger_1.physical_time_of_arrival = NEVER;
    #line 28 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    #endif // FEDERATED
    self->_lf__inputControlReactionTrigger_1.is_physical = false;
    
    self->_lf__inputControlReactionTrigger_1.tmplt.type.element_size = 0;
    self->_lf_inputControlReactionTrigger_1.type.element_size = 0;
    #line 29 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__networkMessage_1.last = NULL;
    #line 29 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    #ifdef FEDERATED_DECENTRALIZED
    #line 29 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__networkMessage_1.intended_tag = (tag_t) { .time = NEVER, .microstep = 0u};
    #line 29 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    #endif // FEDERATED_DECENTRALIZED
    #line 29 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    #line 29 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__networkMessage_1_reactions[0] = &self->_lf__reaction_5;
    #line 29 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__networkMessage_1.reactions = &self->_lf__networkMessage_1_reactions[0];
    #line 29 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__networkMessage_1.number_of_reactions = 1;
    #line 29 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    #ifdef FEDERATED
    #line 29 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__networkMessage_1.physical_time_of_arrival = NEVER;
    #line 29 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    #endif // FEDERATED
    self->_lf__networkMessage_1.is_physical = false;
    
    self->_lf__networkMessage_1.tmplt.type.element_size = sizeof(bool);
    self->_lf_networkMessage_1.type.element_size = sizeof(bool);
    #line 30 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__inputControlReactionTrigger_2.last = NULL;
    #line 30 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    #ifdef FEDERATED_DECENTRALIZED
    #line 30 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__inputControlReactionTrigger_2.intended_tag = (tag_t) { .time = NEVER, .microstep = 0u};
    #line 30 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    #endif // FEDERATED_DECENTRALIZED
    #line 30 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    #line 30 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__inputControlReactionTrigger_2_reactions[0] = &self->_lf__reaction_6;
    #line 30 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__inputControlReactionTrigger_2.reactions = &self->_lf__inputControlReactionTrigger_2_reactions[0];
    #line 30 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__inputControlReactionTrigger_2.number_of_reactions = 1;
    #line 30 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    #ifdef FEDERATED
    #line 30 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__inputControlReactionTrigger_2.physical_time_of_arrival = NEVER;
    #line 30 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    #endif // FEDERATED
    self->_lf__inputControlReactionTrigger_2.is_physical = false;
    
    self->_lf__inputControlReactionTrigger_2.tmplt.type.element_size = 0;
    self->_lf_inputControlReactionTrigger_2.type.element_size = 0;
    #line 31 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__networkMessage_2.last = NULL;
    #line 31 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    #ifdef FEDERATED_DECENTRALIZED
    #line 31 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__networkMessage_2.intended_tag = (tag_t) { .time = NEVER, .microstep = 0u};
    #line 31 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    #endif // FEDERATED_DECENTRALIZED
    #line 31 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    #line 31 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__networkMessage_2_reactions[0] = &self->_lf__reaction_7;
    #line 31 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__networkMessage_2.reactions = &self->_lf__networkMessage_2_reactions[0];
    #line 31 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__networkMessage_2.number_of_reactions = 1;
    #line 31 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    #ifdef FEDERATED
    #line 31 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__networkMessage_2.physical_time_of_arrival = NEVER;
    #line 31 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    #endif // FEDERATED
    self->_lf__networkMessage_2.is_physical = false;
    
    self->_lf__networkMessage_2.tmplt.type.element_size = sizeof(bool);
    self->_lf_networkMessage_2.type.element_size = sizeof(bool);
    #line 32 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__inputControlReactionTrigger_3.last = NULL;
    #line 32 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    #ifdef FEDERATED_DECENTRALIZED
    #line 32 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__inputControlReactionTrigger_3.intended_tag = (tag_t) { .time = NEVER, .microstep = 0u};
    #line 32 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    #endif // FEDERATED_DECENTRALIZED
    #line 32 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    #line 32 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__inputControlReactionTrigger_3_reactions[0] = &self->_lf__reaction_8;
    #line 32 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__inputControlReactionTrigger_3.reactions = &self->_lf__inputControlReactionTrigger_3_reactions[0];
    #line 32 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__inputControlReactionTrigger_3.number_of_reactions = 1;
    #line 32 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    #ifdef FEDERATED
    #line 32 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__inputControlReactionTrigger_3.physical_time_of_arrival = NEVER;
    #line 32 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    #endif // FEDERATED
    self->_lf__inputControlReactionTrigger_3.is_physical = false;
    
    self->_lf__inputControlReactionTrigger_3.tmplt.type.element_size = 0;
    self->_lf_inputControlReactionTrigger_3.type.element_size = 0;
    #line 33 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__networkMessage_3.last = NULL;
    #line 33 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    #ifdef FEDERATED_DECENTRALIZED
    #line 33 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__networkMessage_3.intended_tag = (tag_t) { .time = NEVER, .microstep = 0u};
    #line 33 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    #endif // FEDERATED_DECENTRALIZED
    #line 33 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    #line 33 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__networkMessage_3_reactions[0] = &self->_lf__reaction_9;
    #line 33 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__networkMessage_3.reactions = &self->_lf__networkMessage_3_reactions[0];
    #line 33 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__networkMessage_3.number_of_reactions = 1;
    #line 33 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    #ifdef FEDERATED
    #line 33 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    self->_lf__networkMessage_3.physical_time_of_arrival = NEVER;
    #line 33 "/home/plutonh/project/fed-gen/Waiting_Line/src/A.lf"
    #endif // FEDERATED
    self->_lf__networkMessage_3.is_physical = false;
    
    self->_lf__networkMessage_3.tmplt.type.element_size = sizeof(int);
    self->_lf_networkMessage_3.type.element_size = sizeof(int);
    return self;
}
// =============== END reactor class A
// Array of pointers to timer triggers to be scheduled in _lf_initialize_timers().
trigger_t** _lf_timer_triggers = NULL;
int _lf_timer_triggers_size = 0;
// Array of pointers to startup triggers.
reaction_t** _lf_startup_reactions = NULL;
int _lf_startup_reactions_size = 0;
// Array of pointers to shutdown triggers.
reaction_t** _lf_shutdown_reactions = NULL;
int _lf_shutdown_reactions_size = 0;
// Array of pointers to reset triggers.
reaction_t** _lf_reset_reactions = NULL;
int _lf_reset_reactions_size = 0;
void _lf_initialize_trigger_objects() {
    // Initialize the _lf_clock
    lf_initialize_clock();
    // Create the array that will contain pointers to is_present fields to reset on each step.
    _lf_is_present_fields_size = 10;
    _lf_is_present_fields = (bool**)calloc(10, sizeof(bool*));
    if (_lf_is_present_fields == NULL) lf_print_error_and_exit("Out of memory!");
    _lf_is_present_fields_abbreviated = (bool**)calloc(10, sizeof(bool*));
    if (_lf_is_present_fields_abbreviated == NULL) lf_print_error_and_exit("Out of memory!");
    _lf_is_present_fields_abbreviated_size = 0;
    #ifdef FEDERATED_DECENTRALIZED
    // Create the array that will contain pointers to intended_tag fields to reset on each step.
    _lf_intended_tag_fields_size = 10;
    _lf_intended_tag_fields = (tag_t**)malloc(_lf_intended_tag_fields_size * sizeof(tag_t*));
    
    #endif // FEDERATED_DECENTRALIZED
    int _lf_startup_reactions_count = 0;
    SUPPRESS_UNUSED_WARNING(_lf_startup_reactions_count);
    int _lf_shutdown_reactions_count = 0;
    SUPPRESS_UNUSED_WARNING(_lf_shutdown_reactions_count);
    int _lf_reset_reactions_count = 0;
    SUPPRESS_UNUSED_WARNING(_lf_reset_reactions_count);
    int _lf_timer_triggers_count = 0;
    SUPPRESS_UNUSED_WARNING(_lf_timer_triggers_count);
    int bank_index;
    SUPPRESS_UNUSED_WARNING(bank_index);
    a_main_self_t* a_main_self[1];
    SUPPRESS_UNUSED_WARNING(a_main_self);
    arbiter_self_t* a_a_self[1];
    SUPPRESS_UNUSED_WARNING(a_a_self);
    // ***** Start initializing A of class A
    a_main_self[0] = new_A();
    bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
    // Initializing action A.outputControlReactionTrigger
    a_main_self[0]->_lf__outputControlReactionTrigger.offset = 0;
    a_main_self[0]->_lf__outputControlReactionTrigger.period = -1;
    a_main_self[0]->_lf__outputControlReactionTrigger.mode = NULL;
    // Initializing action A.inputControlReactionTrigger_1
    a_main_self[0]->_lf__inputControlReactionTrigger_1.offset = 0;
    a_main_self[0]->_lf__inputControlReactionTrigger_1.period = -1;
    a_main_self[0]->_lf__inputControlReactionTrigger_1.mode = NULL;
    // Initializing action A.networkMessage_1
    a_main_self[0]->_lf__networkMessage_1.offset = 0;
    a_main_self[0]->_lf__networkMessage_1.period = -1;
    a_main_self[0]->_lf__networkMessage_1.mode = NULL;
    // Initializing action A.inputControlReactionTrigger_2
    a_main_self[0]->_lf__inputControlReactionTrigger_2.offset = 0;
    a_main_self[0]->_lf__inputControlReactionTrigger_2.period = -1;
    a_main_self[0]->_lf__inputControlReactionTrigger_2.mode = NULL;
    // Initializing action A.networkMessage_2
    a_main_self[0]->_lf__networkMessage_2.offset = 0;
    a_main_self[0]->_lf__networkMessage_2.period = -1;
    a_main_self[0]->_lf__networkMessage_2.mode = NULL;
    // Initializing action A.inputControlReactionTrigger_3
    a_main_self[0]->_lf__inputControlReactionTrigger_3.offset = 0;
    a_main_self[0]->_lf__inputControlReactionTrigger_3.period = -1;
    a_main_self[0]->_lf__inputControlReactionTrigger_3.mode = NULL;
    // Initializing action A.networkMessage_3
    a_main_self[0]->_lf__networkMessage_3.offset = 0;
    a_main_self[0]->_lf__networkMessage_3.period = -1;
    a_main_self[0]->_lf__networkMessage_3.mode = NULL;
    _lf_initialize_template((token_template_t*)
            &(a_main_self[0]->_lf__outputControlReactionTrigger),
    0);
    a_main_self[0]->_lf__outputControlReactionTrigger.status = absent;
    _lf_initialize_template((token_template_t*)
            &(a_main_self[0]->_lf__inputControlReactionTrigger_1),
    0);
    a_main_self[0]->_lf__inputControlReactionTrigger_1.status = absent;
    _lf_initialize_template((token_template_t*)
            &(a_main_self[0]->_lf__networkMessage_1),
    sizeof(bool));
    a_main_self[0]->_lf__networkMessage_1.status = absent;
    _lf_initialize_template((token_template_t*)
            &(a_main_self[0]->_lf__inputControlReactionTrigger_2),
    0);
    a_main_self[0]->_lf__inputControlReactionTrigger_2.status = absent;
    _lf_initialize_template((token_template_t*)
            &(a_main_self[0]->_lf__networkMessage_2),
    sizeof(bool));
    a_main_self[0]->_lf__networkMessage_2.status = absent;
    _lf_initialize_template((token_template_t*)
            &(a_main_self[0]->_lf__inputControlReactionTrigger_3),
    0);
    a_main_self[0]->_lf__inputControlReactionTrigger_3.status = absent;
    _lf_initialize_template((token_template_t*)
            &(a_main_self[0]->_lf__networkMessage_3),
    sizeof(int));
    a_main_self[0]->_lf__networkMessage_3.status = absent;
    a_main_self[0]->_lf__reaction_0.deadline = NEVER;
    a_main_self[0]->_lf__reaction_1.deadline = NEVER;
    a_main_self[0]->_lf__reaction_2.deadline = NEVER;
    a_main_self[0]->_lf__reaction_3.deadline = NEVER;
    a_main_self[0]->_lf__reaction_4.deadline = NEVER;
    a_main_self[0]->_lf__reaction_5.deadline = NEVER;
    a_main_self[0]->_lf__reaction_6.deadline = NEVER;
    a_main_self[0]->_lf__reaction_7.deadline = NEVER;
    a_main_self[0]->_lf__reaction_8.deadline = NEVER;
    a_main_self[0]->_lf__reaction_9.deadline = NEVER;
    {
        // ***** Start initializing A.A of class Arbiter
        a_a_self[0] = new_Arbiter();
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        // width of -2 indicates that it is not a multiport.
        a_a_self[0]->_lf_result_width = -2;
        // width of -2 indicates that it is not a multiport.
        a_a_self[0]->_lf_sensor_1_width = -2;
        // width of -2 indicates that it is not a multiport.
        a_a_self[0]->_lf_sensor_2_width = -2;
        // width of -2 indicates that it is not a multiport.
        a_a_self[0]->_lf_control_width = -2;
        //***** End initializing A.A
    }
    //***** End initializing A
    // **** Start deferred initialize for A
    {
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_0 of A.
        a_main_self[0]->_lf__reaction_0.num_outputs = 0;
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
        }
        
        // ** End initialization for reaction 0 of A
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_1 of A.
        a_main_self[0]->_lf__reaction_1.num_outputs = 0;
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
        }
        
        // ** End initialization for reaction 1 of A
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_2 of A.
        a_main_self[0]->_lf__reaction_2.num_outputs = 0;
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
        }
        
        // ** End initialization for reaction 2 of A
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_3 of A.
        a_main_self[0]->_lf__reaction_3.num_outputs = 0;
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
        }
        
        // ** End initialization for reaction 3 of A
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_4 of A.
        a_main_self[0]->_lf__reaction_4.num_outputs = 1;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        a_main_self[0]->_lf__reaction_4.triggers = (trigger_t***)_lf_allocate(
                1, sizeof(trigger_t**),
                &a_main_self[0]->base.allocations);
        a_main_self[0]->_lf__reaction_4.triggered_sizes = (int*)_lf_allocate(
                1, sizeof(int),
                &a_main_self[0]->base.allocations);
        a_main_self[0]->_lf__reaction_4.output_produced = (bool**)_lf_allocate(
                1, sizeof(bool*),
                &a_main_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                a_main_self[0]->_lf__reaction_4.output_produced[count++] = &a_main_self[0]->_lf_A.sensor_1.is_present;
            }
        }
        
        // ** End initialization for reaction 4 of A
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_5 of A.
        a_main_self[0]->_lf__reaction_5.num_outputs = 1;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        a_main_self[0]->_lf__reaction_5.triggers = (trigger_t***)_lf_allocate(
                1, sizeof(trigger_t**),
                &a_main_self[0]->base.allocations);
        a_main_self[0]->_lf__reaction_5.triggered_sizes = (int*)_lf_allocate(
                1, sizeof(int),
                &a_main_self[0]->base.allocations);
        a_main_self[0]->_lf__reaction_5.output_produced = (bool**)_lf_allocate(
                1, sizeof(bool*),
                &a_main_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                a_main_self[0]->_lf__reaction_5.output_produced[count++] = &a_main_self[0]->_lf_A.sensor_1.is_present;
            }
        }
        
        // ** End initialization for reaction 5 of A
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_6 of A.
        a_main_self[0]->_lf__reaction_6.num_outputs = 1;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        a_main_self[0]->_lf__reaction_6.triggers = (trigger_t***)_lf_allocate(
                1, sizeof(trigger_t**),
                &a_main_self[0]->base.allocations);
        a_main_self[0]->_lf__reaction_6.triggered_sizes = (int*)_lf_allocate(
                1, sizeof(int),
                &a_main_self[0]->base.allocations);
        a_main_self[0]->_lf__reaction_6.output_produced = (bool**)_lf_allocate(
                1, sizeof(bool*),
                &a_main_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                a_main_self[0]->_lf__reaction_6.output_produced[count++] = &a_main_self[0]->_lf_A.sensor_2.is_present;
            }
        }
        
        // ** End initialization for reaction 6 of A
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_7 of A.
        a_main_self[0]->_lf__reaction_7.num_outputs = 1;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        a_main_self[0]->_lf__reaction_7.triggers = (trigger_t***)_lf_allocate(
                1, sizeof(trigger_t**),
                &a_main_self[0]->base.allocations);
        a_main_self[0]->_lf__reaction_7.triggered_sizes = (int*)_lf_allocate(
                1, sizeof(int),
                &a_main_self[0]->base.allocations);
        a_main_self[0]->_lf__reaction_7.output_produced = (bool**)_lf_allocate(
                1, sizeof(bool*),
                &a_main_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                a_main_self[0]->_lf__reaction_7.output_produced[count++] = &a_main_self[0]->_lf_A.sensor_2.is_present;
            }
        }
        
        // ** End initialization for reaction 7 of A
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_8 of A.
        a_main_self[0]->_lf__reaction_8.num_outputs = 1;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        a_main_self[0]->_lf__reaction_8.triggers = (trigger_t***)_lf_allocate(
                1, sizeof(trigger_t**),
                &a_main_self[0]->base.allocations);
        a_main_self[0]->_lf__reaction_8.triggered_sizes = (int*)_lf_allocate(
                1, sizeof(int),
                &a_main_self[0]->base.allocations);
        a_main_self[0]->_lf__reaction_8.output_produced = (bool**)_lf_allocate(
                1, sizeof(bool*),
                &a_main_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                a_main_self[0]->_lf__reaction_8.output_produced[count++] = &a_main_self[0]->_lf_A.control.is_present;
            }
        }
        
        // ** End initialization for reaction 8 of A
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_9 of A.
        a_main_self[0]->_lf__reaction_9.num_outputs = 1;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        a_main_self[0]->_lf__reaction_9.triggers = (trigger_t***)_lf_allocate(
                1, sizeof(trigger_t**),
                &a_main_self[0]->base.allocations);
        a_main_self[0]->_lf__reaction_9.triggered_sizes = (int*)_lf_allocate(
                1, sizeof(int),
                &a_main_self[0]->base.allocations);
        a_main_self[0]->_lf__reaction_9.output_produced = (bool**)_lf_allocate(
                1, sizeof(bool*),
                &a_main_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                a_main_self[0]->_lf__reaction_9.output_produced[count++] = &a_main_self[0]->_lf_A.control.is_present;
            }
        }
        
        // ** End initialization for reaction 9 of A
        // **** Start deferred initialize for A.A
        {
        }
        // **** End of deferred initialize for A.A
    }
    // **** End of deferred initialize for A
    // **** Start non-nested deferred initialize for A
    // Set number of destination reactors for port A.sensor_1.
    // Set number of destination reactors for port A.sensor_2.
    // Set number of destination reactors for port A.control.
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
    }
    // **** Start non-nested deferred initialize for A.A
    // For reference counting, set num_destinations for port A.A.result.
    // Iterate over range A.A.result(0,1)->[A.A.result(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        a_a_self[src_runtime]->_lf_result.num_destinations = 1;
    }
    // **** End of non-nested deferred initialize for A.A
    // **** End of non-nested deferred initialize for A
    // Connect inputs and outputs for reactor A.
    // Connect inputs and outputs for reactor A.A.
    {
    }
    // Add port A.A.sensor_1 to array of is_present fields.
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            {
                _lf_is_present_fields[0 + count] = &a_main_self[0]->_lf_A.sensor_1.is_present;
                #ifdef FEDERATED_DECENTRALIZED
                _lf_intended_tag_fields[0 + count] = &a_main_self[0]->_lf_A.sensor_1.intended_tag;
                #endif // FEDERATED_DECENTRALIZED
                count++;
            }
        }
    }
    // Add port A.A.sensor_2 to array of is_present fields.
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            {
                _lf_is_present_fields[1 + count] = &a_main_self[0]->_lf_A.sensor_2.is_present;
                #ifdef FEDERATED_DECENTRALIZED
                _lf_intended_tag_fields[1 + count] = &a_main_self[0]->_lf_A.sensor_2.intended_tag;
                #endif // FEDERATED_DECENTRALIZED
                count++;
            }
        }
    }
    // Add port A.A.control to array of is_present fields.
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            {
                _lf_is_present_fields[2 + count] = &a_main_self[0]->_lf_A.control.is_present;
                #ifdef FEDERATED_DECENTRALIZED
                _lf_intended_tag_fields[2 + count] = &a_main_self[0]->_lf_A.control.intended_tag;
                #endif // FEDERATED_DECENTRALIZED
                count++;
            }
        }
    }
    {
        // Add action A.outputControlReactionTrigger to array of is_present fields.
        _lf_is_present_fields[3] 
                = &a_main_self[0]->_lf_outputControlReactionTrigger.is_present;
        #ifdef FEDERATED_DECENTRALIZED
        // Add action A.outputControlReactionTrigger to array of intended_tag fields.
        _lf_intended_tag_fields[3] 
                = &a_main_self[0]->_lf_outputControlReactionTrigger.intended_tag;
        #endif // FEDERATED_DECENTRALIZED
    }
    {
        // Add action A.inputControlReactionTrigger_1 to array of is_present fields.
        _lf_is_present_fields[4] 
                = &a_main_self[0]->_lf_inputControlReactionTrigger_1.is_present;
        #ifdef FEDERATED_DECENTRALIZED
        // Add action A.inputControlReactionTrigger_1 to array of intended_tag fields.
        _lf_intended_tag_fields[4] 
                = &a_main_self[0]->_lf_inputControlReactionTrigger_1.intended_tag;
        #endif // FEDERATED_DECENTRALIZED
    }
    {
        // Add action A.networkMessage_1 to array of is_present fields.
        _lf_is_present_fields[5] 
                = &a_main_self[0]->_lf_networkMessage_1.is_present;
        #ifdef FEDERATED_DECENTRALIZED
        // Add action A.networkMessage_1 to array of intended_tag fields.
        _lf_intended_tag_fields[5] 
                = &a_main_self[0]->_lf_networkMessage_1.intended_tag;
        #endif // FEDERATED_DECENTRALIZED
    }
    {
        // Add action A.inputControlReactionTrigger_2 to array of is_present fields.
        _lf_is_present_fields[6] 
                = &a_main_self[0]->_lf_inputControlReactionTrigger_2.is_present;
        #ifdef FEDERATED_DECENTRALIZED
        // Add action A.inputControlReactionTrigger_2 to array of intended_tag fields.
        _lf_intended_tag_fields[6] 
                = &a_main_self[0]->_lf_inputControlReactionTrigger_2.intended_tag;
        #endif // FEDERATED_DECENTRALIZED
    }
    {
        // Add action A.networkMessage_2 to array of is_present fields.
        _lf_is_present_fields[7] 
                = &a_main_self[0]->_lf_networkMessage_2.is_present;
        #ifdef FEDERATED_DECENTRALIZED
        // Add action A.networkMessage_2 to array of intended_tag fields.
        _lf_intended_tag_fields[7] 
                = &a_main_self[0]->_lf_networkMessage_2.intended_tag;
        #endif // FEDERATED_DECENTRALIZED
    }
    {
        // Add action A.inputControlReactionTrigger_3 to array of is_present fields.
        _lf_is_present_fields[8] 
                = &a_main_self[0]->_lf_inputControlReactionTrigger_3.is_present;
        #ifdef FEDERATED_DECENTRALIZED
        // Add action A.inputControlReactionTrigger_3 to array of intended_tag fields.
        _lf_intended_tag_fields[8] 
                = &a_main_self[0]->_lf_inputControlReactionTrigger_3.intended_tag;
        #endif // FEDERATED_DECENTRALIZED
    }
    {
        // Add action A.networkMessage_3 to array of is_present fields.
        _lf_is_present_fields[9] 
                = &a_main_self[0]->_lf_networkMessage_3.is_present;
        #ifdef FEDERATED_DECENTRALIZED
        // Add action A.networkMessage_3 to array of intended_tag fields.
        _lf_intended_tag_fields[9] 
                = &a_main_self[0]->_lf_networkMessage_3.intended_tag;
        #endif // FEDERATED_DECENTRALIZED
    }
    // Set reaction priorities for ReactorInstance A
    {
        a_main_self[0]->_lf__reaction_0.chain_id = 1;
        // index is the OR of level 0 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        a_main_self[0]->_lf__reaction_0.index = 0xffffffffffff0000LL;
        a_main_self[0]->_lf__reaction_1.chain_id = 1;
        // index is the OR of level 0 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        a_main_self[0]->_lf__reaction_1.index = 0xffffffffffff0000LL;
        a_main_self[0]->_lf__reaction_2.chain_id = 1;
        // index is the OR of level 0 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        a_main_self[0]->_lf__reaction_2.index = 0xffffffffffff0000LL;
        a_main_self[0]->_lf__reaction_3.chain_id = 1;
        // index is the OR of level 0 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        a_main_self[0]->_lf__reaction_3.index = 0xffffffffffff0000LL;
        a_main_self[0]->_lf__reaction_4.chain_id = 1;
        // index is the OR of level 0 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        a_main_self[0]->_lf__reaction_4.index = 0xffffffffffff0000LL;
        a_main_self[0]->_lf__reaction_5.chain_id = 1;
        // index is the OR of level 0 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        a_main_self[0]->_lf__reaction_5.index = 0xffffffffffff0000LL;
        a_main_self[0]->_lf__reaction_6.chain_id = 1;
        // index is the OR of level 0 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        a_main_self[0]->_lf__reaction_6.index = 0xffffffffffff0000LL;
        a_main_self[0]->_lf__reaction_7.chain_id = 1;
        // index is the OR of level 0 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        a_main_self[0]->_lf__reaction_7.index = 0xffffffffffff0000LL;
        a_main_self[0]->_lf__reaction_8.chain_id = 1;
        // index is the OR of level 0 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        a_main_self[0]->_lf__reaction_8.index = 0xffffffffffff0000LL;
        a_main_self[0]->_lf__reaction_9.chain_id = 1;
        // index is the OR of level 0 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        a_main_self[0]->_lf__reaction_9.index = 0xffffffffffff0000LL;
    }
    // Initialize the scheduler
    size_t num_reactions_per_level[1] = 
        {10};
    sched_params_t sched_params = (sched_params_t) {
                            .num_reactions_per_level = &num_reactions_per_level[0],
                            .num_reactions_per_level_size = (size_t) 1};
    lf_sched_init(
        (size_t)_lf_number_of_workers,
        &sched_params
    );
    #ifdef EXECUTABLE_PREAMBLE
    _lf_executable_preamble();
    #endif
    #ifdef FEDERATED
    initialize_triggers_for_federate();
    #endif // FEDERATED
}
void _lf_trigger_startup_reactions() {}
void _lf_initialize_timers() {

}
void logical_tag_complete(tag_t tag_to_send) {
#ifdef FEDERATED_CENTRALIZED
        _lf_logical_tag_complete(tag_to_send);
#endif // FEDERATED_CENTRALIZED

}
bool _lf_trigger_shutdown_reactions() {
    return false;
}
#ifndef FEDERATED
void terminate_execution() {}
#endif
