// Code generated by the Lingua Franca compiler from:
// file://home/plutonh/project/fed-gen/Waiting_Line/src/S2.lf
#define LOG_LEVEL 2
#define TARGET_FILES_DIRECTORY "/home/plutonh/project/fed-gen/Waiting_Line/src-gen/S2"
#include "include/api/api.h"
#include "core/reactor.h"
#include "core/reactor_common.h"
#include "core/threaded/scheduler.h"
#include "core/mixed_radix.h"
#include "core/port.h"
int lf_reactor_c_main(int argc, const char* argv[]);
#include "core/federated/federate.h"
#include "core/federated/net_common.h"
#include "include/_S2_preamble.h"
int main(int argc, const char* argv[]) {
    return lf_reactor_c_main(argc, argv);
}
const char* _lf_default_argv[] = { "dummy", "-k", "true" };
void _lf_set_default_command_line_options() {
        default_argc = 3;
        default_argv = _lf_default_argv;
}
// =============== START reactor class Sensor_2
typedef struct {
    token_type_t type;
    lf_token_t* token;
    size_t length;
    bool is_present;
    lf_sparse_io_record_t* sparse_record;
    int destination_channel;
    int num_destinations;
    bool value;
    #ifdef FEDERATED
    #ifdef FEDERATED_DECENTRALIZED
    tag_t intended_tag;
    #endif
    interval_t physical_time_of_arrival;
    #endif
} sensor_2_blocked_t;
typedef struct {
    struct self_base_t base;
    #line 17 "/home/plutonh/project/fed-gen/Waiting_Line/src/S2.lf"
    sensor_2_blocked_t _lf_blocked;
    #line 17 "/home/plutonh/project/fed-gen/Waiting_Line/src/S2.lf"
    int _lf_blocked_width;
} sensor_2_self_t;
// ***** Start of method declarations.
// ***** End of method declarations.
sensor_2_self_t* new_Sensor_2() {
    sensor_2_self_t* self = (sensor_2_self_t*)_lf_new_reactor(sizeof(sensor_2_self_t));
    return self;
}
// =============== END reactor class Sensor_2
// =============== START reactor class S2
typedef struct {
    token_type_t type;
    lf_token_t* token;
    size_t length;
    bool is_present;
    bool has_value;
    trigger_t* trigger;
    #ifdef FEDERATED
    #ifdef FEDERATED_DECENTRALIZED
    tag_t intended_tag;
    #endif
    interval_t physical_time_of_arrival;
    #endif
} s2_outputControlReactionTrigger_t;
typedef struct {
    struct self_base_t base;
    #line 24 "/home/plutonh/project/fed-gen/Waiting_Line/src/S2.lf"
    s2_outputControlReactionTrigger_t _lf_outputControlReactionTrigger;
    struct {
        #line 17 "/home/plutonh/project/fed-gen/Waiting_Line/src/S2.lf"
        sensor_2_blocked_t* blocked;
        #line 17 "/home/plutonh/project/fed-gen/Waiting_Line/src/S2.lf"
        trigger_t blocked_trigger;
        #line 17 "/home/plutonh/project/fed-gen/Waiting_Line/src/S2.lf"
        reaction_t* blocked_reactions[1];
    } _lf_S2;
    int _lf_S2_width;
    #line 27 "/home/plutonh/project/fed-gen/Waiting_Line/src/S2.lf"
    reaction_t _lf__reaction_0;
    #line 35 "/home/plutonh/project/fed-gen/Waiting_Line/src/S2.lf"
    reaction_t _lf__reaction_1;
    #line 24 "/home/plutonh/project/fed-gen/Waiting_Line/src/S2.lf"
    trigger_t _lf__outputControlReactionTrigger;
    #line 24 "/home/plutonh/project/fed-gen/Waiting_Line/src/S2.lf"
    reaction_t* _lf__outputControlReactionTrigger_reactions[1];
} s2_main_self_t;
// ***** Start of method declarations.
// ***** End of method declarations.
#include "include/api/set.h"
void s2_mainreaction_function_0(void* instance_args) {
    s2_main_self_t* self = (s2_main_self_t*)instance_args; SUPPRESS_UNUSED_WARNING(self);
    struct S2 {
        sensor_2_blocked_t* blocked;
    
    } S2;
    S2.blocked = self->_lf_S2.blocked;
    #line 29 "/home/plutonh/project/fed-gen/Waiting_Line/src/S2.lf"
    // **** This reaction is unordered.
    // Sending from S2.blocked in federate S2 to A.sensor_2 in federate A
    if (!S2.blocked->is_present) return;
    size_t message_length = sizeof(bool);
    send_timed_message(NEVER, MSG_TYPE_TAGGED_MESSAGE, 1, 0, "federate 0 via the RTI", message_length, (unsigned char*)&S2.blocked->value);
}
#include "include/api/set_undef.h"
#include "include/api/set.h"
void s2_mainreaction_function_1(void* instance_args) {
    s2_main_self_t* self = (s2_main_self_t*)instance_args; SUPPRESS_UNUSED_WARNING(self);
    struct S2 {
        sensor_2_blocked_t* blocked;
    
    } S2;
    // Expose the action struct as a local variable whose name matches the action name.
    s2_outputControlReactionTrigger_t* outputControlReactionTrigger = &self->_lf_outputControlReactionTrigger;
    // Set the fields of the action struct to match the current trigger.
    outputControlReactionTrigger->is_present = (bool)self->_lf__outputControlReactionTrigger.status;
    outputControlReactionTrigger->has_value = ((self->_lf__outputControlReactionTrigger.tmplt.token) != NULL && (self->_lf__outputControlReactionTrigger.tmplt.token)->value != NULL);
    _lf_replace_template_token((token_template_t*)outputControlReactionTrigger, (self->_lf__outputControlReactionTrigger.tmplt.token));
    S2.blocked = self->_lf_S2.blocked;
    #line 37 "/home/plutonh/project/fed-gen/Waiting_Line/src/S2.lf"
    // **** This reaction is unordered.
    // If the output port has not been lf_set for the current logical time,
    // send an ABSENT message to the receiving federate
    LF_PRINT_LOG("Contemplating whether to send port "
              "absent for port %d to federate %d.",
              1, 0);
    if (S2.blocked == NULL || !S2.blocked->is_present) {
        // The output port is NULL or it is not present.
        send_port_absent_to_federate(NEVER, 1, 0);
    }
}
#include "include/api/set_undef.h"
s2_main_self_t* new_S2() {
    s2_main_self_t* self = (s2_main_self_t*)_lf_new_reactor(sizeof(s2_main_self_t));
    #line 24 "/home/plutonh/project/fed-gen/Waiting_Line/src/S2.lf"
    self->_lf_outputControlReactionTrigger.trigger = &self->_lf__outputControlReactionTrigger;
    // Set the _width variable for all cases. This will be -2
    // if the reactor is not a bank of reactors.
    self->_lf_S2_width = -2;
    #line 17 "/home/plutonh/project/fed-gen/Waiting_Line/src/S2.lf"
    #ifdef FEDERATED_DECENTRALIZED
    #line 17 "/home/plutonh/project/fed-gen/Waiting_Line/src/S2.lf"
    self->_lf_S2.blocked_trigger.intended_tag = (tag_t) { .time = NEVER, .microstep = 0u};
    #line 17 "/home/plutonh/project/fed-gen/Waiting_Line/src/S2.lf"
    #endif // FEDERATED_DECENTRALIZED
    #line 17 "/home/plutonh/project/fed-gen/Waiting_Line/src/S2.lf"
    self->_lf_S2.blocked_reactions[0] = &self->_lf__reaction_0;
    #line 17 "/home/plutonh/project/fed-gen/Waiting_Line/src/S2.lf"
    self->_lf_S2.blocked_trigger.reactions = self->_lf_S2.blocked_reactions;
    #line 17 "/home/plutonh/project/fed-gen/Waiting_Line/src/S2.lf"
    self->_lf_S2.blocked_trigger.last = NULL;
    #line 17 "/home/plutonh/project/fed-gen/Waiting_Line/src/S2.lf"
    self->_lf_S2.blocked_trigger.number_of_reactions = 1;
    #line 17 "/home/plutonh/project/fed-gen/Waiting_Line/src/S2.lf"
    #ifdef FEDERATED
    #line 17 "/home/plutonh/project/fed-gen/Waiting_Line/src/S2.lf"
    self->_lf_S2.blocked_trigger.physical_time_of_arrival = NEVER;
    #line 17 "/home/plutonh/project/fed-gen/Waiting_Line/src/S2.lf"
    #endif // FEDERATED
    #line 27 "/home/plutonh/project/fed-gen/Waiting_Line/src/S2.lf"
    self->_lf__reaction_0.number = 0;
    #line 27 "/home/plutonh/project/fed-gen/Waiting_Line/src/S2.lf"
    self->_lf__reaction_0.function = s2_mainreaction_function_0;
    #line 27 "/home/plutonh/project/fed-gen/Waiting_Line/src/S2.lf"
    self->_lf__reaction_0.self = self;
    #line 27 "/home/plutonh/project/fed-gen/Waiting_Line/src/S2.lf"
    self->_lf__reaction_0.deadline_violation_handler = NULL;
    #line 27 "/home/plutonh/project/fed-gen/Waiting_Line/src/S2.lf"
    self->_lf__reaction_0.STP_handler = NULL;
    #line 27 "/home/plutonh/project/fed-gen/Waiting_Line/src/S2.lf"
    self->_lf__reaction_0.name = "?";
    #line 27 "/home/plutonh/project/fed-gen/Waiting_Line/src/S2.lf"
    self->_lf__reaction_0.mode = NULL;
    #line 35 "/home/plutonh/project/fed-gen/Waiting_Line/src/S2.lf"
    self->_lf__reaction_1.number = 1;
    #line 35 "/home/plutonh/project/fed-gen/Waiting_Line/src/S2.lf"
    self->_lf__reaction_1.function = s2_mainreaction_function_1;
    #line 35 "/home/plutonh/project/fed-gen/Waiting_Line/src/S2.lf"
    self->_lf__reaction_1.self = self;
    #line 35 "/home/plutonh/project/fed-gen/Waiting_Line/src/S2.lf"
    self->_lf__reaction_1.deadline_violation_handler = NULL;
    #line 35 "/home/plutonh/project/fed-gen/Waiting_Line/src/S2.lf"
    self->_lf__reaction_1.STP_handler = NULL;
    #line 35 "/home/plutonh/project/fed-gen/Waiting_Line/src/S2.lf"
    self->_lf__reaction_1.name = "?";
    #line 35 "/home/plutonh/project/fed-gen/Waiting_Line/src/S2.lf"
    self->_lf__reaction_1.mode = NULL;
    #line 24 "/home/plutonh/project/fed-gen/Waiting_Line/src/S2.lf"
    self->_lf__outputControlReactionTrigger.last = NULL;
    #line 24 "/home/plutonh/project/fed-gen/Waiting_Line/src/S2.lf"
    #ifdef FEDERATED_DECENTRALIZED
    #line 24 "/home/plutonh/project/fed-gen/Waiting_Line/src/S2.lf"
    self->_lf__outputControlReactionTrigger.intended_tag = (tag_t) { .time = NEVER, .microstep = 0u};
    #line 24 "/home/plutonh/project/fed-gen/Waiting_Line/src/S2.lf"
    #endif // FEDERATED_DECENTRALIZED
    #line 24 "/home/plutonh/project/fed-gen/Waiting_Line/src/S2.lf"
    #line 24 "/home/plutonh/project/fed-gen/Waiting_Line/src/S2.lf"
    self->_lf__outputControlReactionTrigger_reactions[0] = &self->_lf__reaction_1;
    #line 24 "/home/plutonh/project/fed-gen/Waiting_Line/src/S2.lf"
    self->_lf__outputControlReactionTrigger.reactions = &self->_lf__outputControlReactionTrigger_reactions[0];
    #line 24 "/home/plutonh/project/fed-gen/Waiting_Line/src/S2.lf"
    self->_lf__outputControlReactionTrigger.number_of_reactions = 1;
    #line 24 "/home/plutonh/project/fed-gen/Waiting_Line/src/S2.lf"
    #ifdef FEDERATED
    #line 24 "/home/plutonh/project/fed-gen/Waiting_Line/src/S2.lf"
    self->_lf__outputControlReactionTrigger.physical_time_of_arrival = NEVER;
    #line 24 "/home/plutonh/project/fed-gen/Waiting_Line/src/S2.lf"
    #endif // FEDERATED
    self->_lf__outputControlReactionTrigger.is_physical = false;
    
    self->_lf__outputControlReactionTrigger.tmplt.type.element_size = 0;
    self->_lf_outputControlReactionTrigger.type.element_size = 0;
    return self;
}
// =============== END reactor class S2
// Array of pointers to timer triggers to be scheduled in _lf_initialize_timers().
trigger_t** _lf_timer_triggers = NULL;
int _lf_timer_triggers_size = 0;
// Array of pointers to startup triggers.
reaction_t** _lf_startup_reactions = NULL;
int _lf_startup_reactions_size = 0;
// Array of pointers to shutdown triggers.
reaction_t** _lf_shutdown_reactions = NULL;
int _lf_shutdown_reactions_size = 0;
// Array of pointers to reset triggers.
reaction_t** _lf_reset_reactions = NULL;
int _lf_reset_reactions_size = 0;
void _lf_initialize_trigger_objects() {
    // Initialize the _lf_clock
    lf_initialize_clock();
    // Create the array that will contain pointers to is_present fields to reset on each step.
    _lf_is_present_fields_size = 1;
    _lf_is_present_fields = (bool**)calloc(1, sizeof(bool*));
    if (_lf_is_present_fields == NULL) lf_print_error_and_exit("Out of memory!");
    _lf_is_present_fields_abbreviated = (bool**)calloc(1, sizeof(bool*));
    if (_lf_is_present_fields_abbreviated == NULL) lf_print_error_and_exit("Out of memory!");
    _lf_is_present_fields_abbreviated_size = 0;
    #ifdef FEDERATED_DECENTRALIZED
    // Create the array that will contain pointers to intended_tag fields to reset on each step.
    _lf_intended_tag_fields_size = 1;
    _lf_intended_tag_fields = (tag_t**)malloc(_lf_intended_tag_fields_size * sizeof(tag_t*));
    
    #endif // FEDERATED_DECENTRALIZED
    int _lf_startup_reactions_count = 0;
    SUPPRESS_UNUSED_WARNING(_lf_startup_reactions_count);
    int _lf_shutdown_reactions_count = 0;
    SUPPRESS_UNUSED_WARNING(_lf_shutdown_reactions_count);
    int _lf_reset_reactions_count = 0;
    SUPPRESS_UNUSED_WARNING(_lf_reset_reactions_count);
    int _lf_timer_triggers_count = 0;
    SUPPRESS_UNUSED_WARNING(_lf_timer_triggers_count);
    int bank_index;
    SUPPRESS_UNUSED_WARNING(bank_index);
    s2_main_self_t* s2_main_self[1];
    SUPPRESS_UNUSED_WARNING(s2_main_self);
    sensor_2_self_t* s2_s2_self[1];
    SUPPRESS_UNUSED_WARNING(s2_s2_self);
    // ***** Start initializing S2 of class S2
    s2_main_self[0] = new_S2();
    bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
    // Initializing action S2.outputControlReactionTrigger
    s2_main_self[0]->_lf__outputControlReactionTrigger.offset = 0;
    s2_main_self[0]->_lf__outputControlReactionTrigger.period = -1;
    s2_main_self[0]->_lf__outputControlReactionTrigger.mode = NULL;
    _lf_initialize_template((token_template_t*)
            &(s2_main_self[0]->_lf__outputControlReactionTrigger),
    0);
    s2_main_self[0]->_lf__outputControlReactionTrigger.status = absent;
    s2_main_self[0]->_lf__reaction_0.deadline = NEVER;
    s2_main_self[0]->_lf__reaction_1.deadline = NEVER;
    {
        // ***** Start initializing S2.S2 of class Sensor_2
        s2_s2_self[0] = new_Sensor_2();
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        // width of -2 indicates that it is not a multiport.
        s2_s2_self[0]->_lf_blocked_width = -2;
        //***** End initializing S2.S2
    }
    //***** End initializing S2
    // **** Start deferred initialize for S2
    {
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_0 of S2.
        s2_main_self[0]->_lf__reaction_0.num_outputs = 0;
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
        }
        
        // ** End initialization for reaction 0 of S2
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_1 of S2.
        s2_main_self[0]->_lf__reaction_1.num_outputs = 0;
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
        }
        
        // ** End initialization for reaction 1 of S2
        // **** Start deferred initialize for S2.S2
        {
        }
        // **** End of deferred initialize for S2.S2
    }
    // **** End of deferred initialize for S2
    // **** Start non-nested deferred initialize for S2
    // **** Start non-nested deferred initialize for S2.S2
    // For reference counting, set num_destinations for port S2.S2.blocked.
    // Iterate over range S2.S2.blocked(0,1)->[S2.S2.blocked(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        s2_s2_self[src_runtime]->_lf_blocked.num_destinations = 1;
    }
    // **** End of non-nested deferred initialize for S2.S2
    // **** End of non-nested deferred initialize for S2
    // Connect inputs and outputs for reactor S2.
    // Connect inputs and outputs for reactor S2.S2.
    {
    }
    {
        // Add action S2.outputControlReactionTrigger to array of is_present fields.
        _lf_is_present_fields[0] 
                = &s2_main_self[0]->_lf_outputControlReactionTrigger.is_present;
        #ifdef FEDERATED_DECENTRALIZED
        // Add action S2.outputControlReactionTrigger to array of intended_tag fields.
        _lf_intended_tag_fields[0] 
                = &s2_main_self[0]->_lf_outputControlReactionTrigger.intended_tag;
        #endif // FEDERATED_DECENTRALIZED
    }
    // Set reaction priorities for ReactorInstance S2
    {
        s2_main_self[0]->_lf__reaction_0.chain_id = 1;
        // index is the OR of level 0 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        s2_main_self[0]->_lf__reaction_0.index = 0xffffffffffff0000LL;
        s2_main_self[0]->_lf__reaction_1.chain_id = 1;
        // index is the OR of level 0 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        s2_main_self[0]->_lf__reaction_1.index = 0xffffffffffff0000LL;
    }
    // Initialize the scheduler
    size_t num_reactions_per_level[1] = 
        {2};
    sched_params_t sched_params = (sched_params_t) {
                            .num_reactions_per_level = &num_reactions_per_level[0],
                            .num_reactions_per_level_size = (size_t) 1};
    lf_sched_init(
        (size_t)_lf_number_of_workers,
        &sched_params
    );
    #ifdef EXECUTABLE_PREAMBLE
    _lf_executable_preamble();
    #endif
    #ifdef FEDERATED
    initialize_triggers_for_federate();
    #endif // FEDERATED
}
void _lf_trigger_startup_reactions() {}
void _lf_initialize_timers() {

}
void logical_tag_complete(tag_t tag_to_send) {
#ifdef FEDERATED_CENTRALIZED
        _lf_logical_tag_complete(tag_to_send);
#endif // FEDERATED_CENTRALIZED

}
bool _lf_trigger_shutdown_reactions() {
    return false;
}
#ifndef FEDERATED
void terminate_execution() {}
#endif
